### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by MinecraftMaster67** [Chessnut/NutScript#108]
1.How do i add myself as owner and how to i add my friends as Admin/Superadmin.
2. Is there a way i can make my own factions such as CWU,Antlion and Zombie.
3. Is there a way i can do a /doorsetunownable and make it perm so when the server restarts it will still be there.

**Comment by Nerolat** [comment]
@Saxithon I believe that command doesn't exist anymore in 1.1.

**Comment by Saxithon** [comment]
I guess its actually not implementet as it is still not finished yet. I
guess for now you need something like ULX. Worked for me in 1.1


Nerolat <notifications@github.com> schrieb am Thu Jan 01 2015 at 12:39:05:
