### ISSUE TITLE
How to add attributes to wearable items.

### ISSUE THREAD

**Issue by Anday-** [Chessnut/NutScript#155]
If you were to wear a bit of clothing per say, is there any way to make the clothes give certain attributes? Such as jump height, run speed, stamina increase & health & Armor? In addition would making resistance profiles on clothes be a valid option too?

If so, how so?

**Comment by Chessnut** [comment]
Late but in 1.1, clothing now has ITEM.attribBoosts which is used like:

`
ITEM.attribBoosts = {
	["str"] = 5,
	["stm"] = 1
}
`
