### ISSUE TITLE
Custom HUD

### ISSUE THREAD

**Issue by TheSmallChild** [Chessnut/NutScript#269]
Hello. I'm having trouble re-creating the special HUD-type-thing you guys made in the HL2RP schema for the MRP/OTA factions. Can I just make/use a custom HUD or is there some special code I need for it? And, if it's possible, bind it to some sort of item, say make a gas mask looking HUD when equipping the gas mask from the Bad Air plugin?

**Comment by rebel1324** [comment]
Bad Air getting remastered: http://www.youtube.com/watch?v=e-ZhG56eKIE
