### ISSUE TITLE
Making Framework-wise Notification Message.

### ISSUE THREAD

**Issue by rebel1324** [Chessnut/NutScript#273]
I'm thinking of adding framework-wise notification message which broadcasts some message over the server but the messages are brought from the github repo.

But, The server owner must able to disable the default texts that loaded from github repo.

How about this idea?

**Comment by Saxithon** [comment]
Actually a good idea to tell (super)admins if there's a Update, smiliar to my Suggestion making autoupdate.

**Comment by Thadah** [comment]
I think autoupdate is too dangerous in NutScript, specially for people who runs servers in other languages and have to change core files to translate it 100%

This would be a better idea.

**Comment by Saxithon** [comment]
The lang is stored in a separate file, it can be excluded (?)
