### ISSUE TITLE
Building up a Wiki

### ISSUE THREAD

**Issue by Saxithon** [Chessnut/NutScript#274]
The Help Menu could contain a link to the/a offical NutScript Wiki.
 I know theres no offical one yet but chess (or you?) COULD make one. 
Or simply upload somewhere a WikiCMS and it will build up almost automatically.. or you choose some persons who start off managing the wiki.

**Comment by Chessnut** [comment]
https://github.com/Chessnut/NutScript/wiki

**Comment by Saxithon** [comment]
Yeah i've already seen this but this one is only for Dev's. I mean build it up for Owners *and* Players

**Comment by rebel1324** [comment]
What do you mean Owners and Players.
To build up your own RP, You need to know some lua.

2015-01-05 23:09 GMT+09:00 Kai-Nico <notifications@github.com>:

**Comment by Saxithon** [comment]
Well a Wiki thats not just designed for Developers.

For example a Wiki-Page which describes the commands detailed, like  /doorsetunownable.

Or for regular Players
(Next example is for "not-experienced" Users)
How to create a char and set attributes.

and some declarations what things in the NS config files / NS 1.1 config tab does.

and of course the Dev stuff, what explains which hooks do what thing.

**Comment by Chessnut** [comment]
Hovering over configs tells what they do. Commands are self-explanatory.

**Comment by Saxithon** [comment]
Well looks like I dont win this discussion. 

We can close this.

**Comment by Nerolat** [comment]
Honestly - it is very simple: This is how you can do this, Saxithon:
If unsure, what other commands are there, you can explore gamemodes/Nutscript/plugins files and see where there is "addCommand", "registerCommand", or something similar. One of the text strings in the arguments of the function will be the command itself, and possibly, explanation. Then note every command you want on the notepad, and either establish some sort of forum post on your website, or well, you can add a wiki page to our already existant github wiki.
