### ISSUE TITLE
Need good font for NutScript 1.1

### ISSUE THREAD

**Issue by rebel1324** [Chessnut/NutScript#275]
Honestly, Default Font sucks ass. 
I rather put 1MB on the resource.

**Comment by rebel1324** [comment]
1. ![http://www.fontsquirrel.com/fonts/Aurulent-Sans](Aurulent Sans)
2. ![http://www.fontsquirrel.com/fonts/Bitstream-Vera-Sans](Bitstream Vera Sans)
3. ![http://www.fontsquirrel.com/fonts/Bebas?filter%5Bclassifications%5D%5B0%5D=display&filter%5Bclassifications%5D%5B1%5D=script&filter%5Bclassifications%5D%5B2%5D=serif](Bebas)

I'm thinking of those.
Any suggestions?

**Comment by skarphet** [comment]
Bitstream one looks nice

**Comment by Saxithon** [comment]
Roboto, Noto?

skarphet <notifications@github.com> schrieb am Mon Jan 05 2015 at 22:46:09:

**Comment by Thadah** [comment]
I like Bitstream more than Aurulent because of how the g letter os made.
Bebas is a no no for me.
