### ISSUE TITLE
No opition to make door a combine/ faction door. 

### ISSUE THREAD

**Issue by Isaiahfeldt** [Chessnut/NutScript#279]
There should be a option to set a door to be accsesable by a certain faction or factions. You would think this would be already implemented, and it probably already is. I just can't find out how to do it. The wiki should have this kind of information.

**Comment by Saxithon** [comment]
It will on ns 1.1

Isaiahfeldt <notifications@github.com> schrieb am Tue Jan 06 2015 at
16:10:51:

**Comment by Isaiahfeldt** [comment]
Thank you.
