### ISSUE TITLE
How to remove display text for unownable doors 

### ISSUE THREAD

**Issue by Isaiahfeldt** [Chessnut/NutScript#280]
It would be nice if door that are unownable could display either no text at all or a custom door title.

**Comment by Isaiahfeldt** [comment]
I knew about that command, just didnt know about the adding the letter part. Usually it would come up saying the door has been unhidden after using the /doorsethidden command.

**Comment by Saxithon** [comment]
Just add a letter after the command ex: /doorsethidden f   aand its hidden

Isaiahfeldt <notifications@github.com> schrieb am Mi., 7. Jan. 2015 19:01:
