### ISSUE TITLE
Suggestion: Force door titles on

### ISSUE THREAD

**Issue by Isaiahfeldt** [Chessnut/NutScript#281]
Instead of doors displaying "Door for Sale", It would be amazing if server owners had the option to set default door titles on any door, even if they don't own it. 

For example, server owners could displau apartment doors as Apartment A1, Apartment B6, etc.

Having bathrooms or closets labeled by default would also be nice than just having " Door for Sale"

**Comment by Saxithon** [comment]
I highly suggest you read the hell of NutScript. You can do it...
Am 06.01.2015 19:20 schrieb "Isaiahfeldt" <notifications@github.com>:

**Comment by Isaiahfeldt** [comment]
Well I obviously don't know how to go about doing that. May you be so kind to tell me?

**Comment by Saxithon** [comment]
F1-Menu -> Help? Theres also a Command Section, a list of voice commands
and stuff

2015-01-07 19:02 GMT+01:00 Isaiahfeldt <notifications@github.com>:
