### ISSUE TITLE
[1.1] F1 Error

### ISSUE THREAD

**Issue by Trixioks** [Chessnut/NutScript#282]
[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_information.lua:115: attempt to call method 'GetSubMaterial' (a nil value)
  1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:115
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:77
    3. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
     4. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:527
Just want report that.

**Comment by Nerolat** [comment]
You are supposed to use the dev branch for now, until the dev branch is merged into the release branch, which might take up to a month, I am not aware of Garry's team system.

http://garry.tv/2013/05/28/steampipe-beta/ (old post, but just use the image to see how you can convert your gmod to dev)

**Comment by Trixioks** [comment]
Ohh okay. Thanks.
