### ISSUE TITLE
Issue with nut.item.list with META:add 

### ISSUE THREAD

**Issue by 0Oskar** [Chessnut/NutScript#289]
After changing data on a item, then for example using the business menu or /chargiveitem and giving yourself such a item, it somehow grabs the changed data, did a PrintTable on itemTable = nut.item.list([uniqueID]) (Thought I could use that data if it was ok) in the meta:add function, and it brought me the changed data aswell(Wierd).
However when printing it in another function, returns the data as it should.

So meta:add works gr8 when you give it all the data, but fucks up when using /chargiveitem or from the business menu. (Since you don't provide any data)

**Comment by rebel1324** [comment]
confirmed. I'm working on it.

2015-01-29 4:43 GMT+09:00 Oskar <notifications@github.com>:
