### ISSUE TITLE
Vendor (Plugin)

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#291]
Hello!
When the settings of the goods (for the vendor), the following error (NutScript 1.1):

Warning: vgui.Create failed to create the VGUI component (DProperty_Combo)
TEST [lua/vgui/dnumslider_legacy.lua][lua/vgui/dlistview_line.lua]

[ERROR] gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498: attempt to call method 'AddChoice' (a nil value)
  1. OnClickLine - gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498
   2. unknown - lua/vgui/dlistview_line.lua:87

Warning: vgui.Create failed to create the VGUI component (DProperty_Combo)
TEST [lua/vgui/dnumslider_legacy.lua][lua/vgui/dlistview_line.lua]

[ERROR] gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498: attempt to call method 'AddChoice' (a nil value)
  1. OnClickLine - gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498
   2. unknown - lua/vgui/dlistview_line.lua:87

Warning: vgui.Create failed to create the VGUI component (DProperty_Combo)
TEST [lua/vgui/dnumslider_legacy.lua][lua/vgui/dlistview_line.lua]

[ERROR] gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498: attempt to call method 'AddChoice' (a nil value)
  1. OnClickLine - gamemodes/nutscript/plugins/vendor/derma/cl_vendor.lua:498
   2. unknown - lua/vgui/dlistview_line.lua:99

**Comment by Chessnut** [comment]
You need to use the GMod dev branch
