### ISSUE TITLE
SCHEMA ERROR 1.1

### ISSUE THREAD

**Issue by kkj4818** [Chessnut/NutScript#293]
![2015-02-08_00001](https://cloud.githubusercontent.com/assets/5549849/6094766/05ee1e76-af7d-11e4-8bb5-84f1500a24ae.jpg)

**Comment by Tommo-101** [comment]
Same issue here. Happens at random times when players join and I'm using MySQL.

**Comment by kkj4818** [comment]
In spite of I use sqlite, the error occurs.
