### ISSUE TITLE
Babble on item and vendor

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#294]
Nutscript 1.1; HL2RP 1.1. Here are screenshots:
![Pic #1](http://s7.hostingkartinok.com/uploads/images/2015/02/078118b6a6af4efd6eafdb3c66a7a1f8.jpg)
![Pic #2](http://s7.hostingkartinok.com/uploads/images/2015/02/f542eda41bfa94e5b22a5d8b85ac148d.jpg)

**Comment by Chessnut** [comment]
Are you using any addons that might cause this? The bubble isn't included in NS by default.

**Comment by art-gur** [comment]
No, I did not use any add-ons that would be added to the bubbles.

**Comment by Chessnut** [comment]
Well I can't replicate this.

**Comment by Nerolat** [comment]
To help identify what it is, please list your addons, and check that the base gamemode (nutscript) is up to date.
