### ISSUE TITLE
Doorbust charge is duping some doors. Error when you trying to move equipped weapon. Visual glitch when you drop outfit.

### ISSUE THREAD

**Issue by Blackfox2012** [Chessnut/NutScript#298]
Doorbust charge is duping some doors 00:00
Error when you trying to move equipped weapon 00:35
Visual glitch when you drop outfit 01:05

http://www.youtube.com/watch?v=zPbz8eJfwjA&feature=youtu.be

**Comment by Chessnut** [comment]
You need to show what the Lua errors are otherwise I cannot fix it.
As for the visual glitch, does the server have the model?

**Comment by Blackfox2012** [comment]
>does the server have the model?
Yeah, sure.
I will give you some errors later if this not fixed on newest version.
Thanks for answering.

**Comment by Chessnut** [comment]
Do you have the error?

**Comment by Blackfox2012** [comment]
Sorry. I don't have a time to check this. Today gonna give you report if i not gonna busy.

**Comment by Chessnut** [comment]
Just post the error when you can.

**Comment by Blackfox2012** [comment]
no more gun error but visual bug still here when you just drop gas mask and doorbust not fixed but it's easy to fix restrict to some door models

**Comment by Chessnut** [comment]
I know but what's the Lua error for the door

**Comment by Blackfox2012** [comment]
[ERROR] gamemodes/nutscript/gamemode/core/sh_util.lua:397: bad argument #1 to 'SetSkin' (number expected, got no value)
  1. SetSkin - [C]:-1
   2. blastDoor - gamemodes/nutscript/gamemode/core/sh_util.lua:397
    3. Explode - gamemodes/modernrp/plugins/doorbust/entities/entities/nut_dcharge.lua:61
     4. unknown - gamemodes/modernrp/plugins/doorbust/entities/entities/nut_dcharge.lua:75
