### ISSUE TITLE
Weapons dropping upon restart

### ISSUE THREAD

**Issue by DeadiKation** [Chessnut/NutScript#309]
No matter if you're restarting or completely closing the server, It'll drop your equipped weapons upon the place you disconnected or behind/around. Sometimes even causing some weapons to float in a place in the map.

http://cloud-4.steamusercontent.com/ugc/32986915605049896/7D744C389CDF8E7DEB9E6FCDD0FBD730D2F753D5/1024x640.resizedimage

http://cloud-4.steamusercontent.com/ugc/32986915605050065/F338CAEE89B9CC2F0B7AD8CFE1C9763BBAC9415B/

**Comment by Chessnut** [comment]
Check for server-side errors.

**Comment by DeadiKation** [comment]
I pinpointed it to be the persist plugin that I updated to 1.1, Still not able to see any errors that come from it though neither Client or Serverside. Also an issue with taking persist off of items.

`
PLUGIN.name = "Persistent Props"
PLUGIN.author = "Chessnut"
PLUGIN.desc = "Allows administrators to set props to be persistent through restarts."

if (SERVER) then
	file.CreateDir("persist")
	file.CreateDir("persist/nutscript")

	function PLUGIN:LoadData()
		
		local contents = file.Read("persist/nutscript/"..SCHEMA.uniqueID.."/"..game.GetMap()..".txt", "DATA")

		if (!contents) then
			return
		end

		local data = util.JSONToTable(contents)

		if (data) then
			local entities, constraints = duplicator.Paste(nil, data.Entities or {}, data.Contraints or {})

			for k, v in pairs(entities) do
				nut.data.set("persist", true)
			end
		end
	end

	function PLUGIN:SaveData()
	
		local data = {}

		for k, v in pairs(ents.GetAll()) do
			if (nut.data.get("persist")) then
				data[#data + 1] = v
			end
		end

		if (#data > 0) then
			local persistData = duplicator.CopyEnts(data)

			if (!persistData) then
				return
			end

			file.CreateDir("persist/nutscript/"..SCHEMA.uniqueID)
			file.Write("persist/nutscript/"..SCHEMA.uniqueID.."/"..game.GetMap()..".txt", util.TableToJSON(persistData))
		end
	end
end

local PLUGIN = PLUGIN

nut.command.add("persist", {
	syntax = "<string target>",
	adminOnly = true,
	onRun = function(client, arguments)
		local trace = client:GetEyeTraceNoCursor()
		local entity = trace.Entity

		if (IsValid(entity)) then
			local class = entity:GetClass()

			if (string.find(class, "prop_") and !string.find(class, "door")) then
				nut.data.set("persist", !util.tobool(arguments[1]))

				if (nut.data.set("persist")) then
					nut.util.notify("This entity is now persisted.", client)
				else
					nut.util.notify("This entity is no longer persisted.", client)
				end
			else
				nut.util.notify("That entity can not be persisted.", client)
			end
		else
			nut.util.notify("You provided an invalid entity.", client)
		end
	end
})
`

**Comment by Chessnut** [comment]
You're persisting ALL entities which is a terrible idea.
