### ISSUE TITLE
Low Priority: Shotgun SWEPs fire all bullets in one location.

### ISSUE THREAD

**Issue by DeadiKation** [Chessnut/NutScript#310]
I've noticed this with SWEPs from different bases, no matter what the bullets from shotguns that normally spread everywhere in singleplayer, all fire into one location on NutScript. I've attempted changing Spread, as well as creating custom SWEP:ShootBullet functions to get around this to no avail.

**Comment by Chessnut** [comment]
This sounds like a problem with your SWEP base, not NutScript.

**Comment by Rubberbandits** [comment]
Yeah, that's not NS.

Mine work fine.

**Comment by DeadiKation** [comment]
Alright, I'll look into the SWEP Base, It's happened with both of the bases though.
