### ISSUE TITLE
Nutscript Intro and Character Selection Screen

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#314]
Neither of these scale to the proper resolution for some reason if you are in 4:3 (Haven't tested in 16:9, just noticed it whilst developing)

**Comment by Chessnut** [comment]
You may need to rejoin if you're changing resolution since the menus are not re-created on resolution change.

**Comment by Rubberbandits** [comment]
I did.

**Comment by Chessnut** [comment]
Do you have a screenshot I can see?

**Comment by Rubberbandits** [comment]
![2015-03-04_00001](https://cloud.githubusercontent.com/assets/5221483/6500265/14fcb928-c2be-11e4-8180-757d574d4062.jpg)
