### ISSUE TITLE
HOLDTYPE_TRANSLATOR nil value

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#315]
Just updated 1.1 a few hours ago, now upon opening the inventory it returns this error, but functionality isn't changed(?).

[ERROR] gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:744: attempt to index global 'HOLDTYPE_TRANSLATOR' (a nil value)
  1. Run - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:744
   2. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:129
    3. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:77
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      5. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:560

**Comment by Sascha8a** [comment]
I've got the same error.
Am 04.03.2015 06:36 schrieb "Rubberbandits" <notifications@github.com>:

**Comment by Rubberbandits** [comment]
Probably just CN forgetting to define it. or using the wrong shit

**Comment by Rubberbandits** [comment]
I fixed it, creating a pull request.
