### ISSUE TITLE
item:getData returns nil

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#318]
For some reason, using item:getData for (example: item.player:SetArmor()) it will always return nil. Same thing if you try printing the data.

[LOG] pleswark, Equip -> Brown Trenchcoat.
nil
[LOG] pleswark, Equip -> Brown Trenchcoat.

that nil that is being returned is caused by print(item:getData("equip")), but it should be true. i've even tried creating a junk data entry called condition and trying to return that, but it returns nil.

EDIT: Been doing some testing using onInstanced to add the data to the table.

**Comment by Chessnut** [comment]
You're going to need to show some code. If it is nil, it's nil. It means it hasn't been set.

**Comment by Rubberbandits** [comment]
ITEM.name = "Brown Trenchcoat"
ITEM.desc = "Brown Trenchcoat"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.isCloth = false
ITEM.data = { 
	condition = 100,
	equip = false
}
ITEM.setmodel = "models/stalkertnb/banditboss2.mdl"
ITEM.setmodelfemale = "models/stalkertnb/banditboss2.mdl"
ITEM.functions.EquipUn = { -- sorry, for name order.
	name = "Unequip",
	tip = "equipTip",
	icon = "icon16/world.png",
	onRun = function(item)
		local client = item.player
		local character = client:getChar()
		character:setModel(character:getData("permaModel"))
		
		item:setData("condition", client:Armor())
		
		item.player:getChar():setData("bullet_suit", 1)
		item.player:getChar():setData("chemical_suit", 1)
		item.player:getChar():setData("explosion_suit", 1)
		item.player:getChar():setData("shock_suit", 1)
		item.player:getChar():setData("burn_suit", 1)
		item.player:getChar():setData("impact_suit", 1)
		
		item.player:getChar():setData("artifactSlots", 0)
		
		item.player:EmitSound("items/ammo_pickup.wav", 80)
		item:setData("equip", false)
		
		return false
	end,
	onCanRun = function(item)
		return (!IsValid(item.entity) and item:getData("equip") == true)
	end
}

ITEM.functions.Equip = {
	name = "Equip",
	tip = "equipTip",
	icon = "icon16/world.png",
	onRun = function(item)
	
	local character = item.player:getChar()
	item.player:getChar():setData("bullet_suit", 0.9)
	item.player:getChar():setData("chemical_suit", 1)
	item.player:getChar():setData("explosion_suit", 1)
	item.player:getChar():setData("shock_suit", 1)
	item.player:getChar():setData("burn_suit", 1)
	item.player:getChar():setData("impact_suit", 1)
	
	item.player:getChar():setData("artifactSlots", 0)
	
	print(item:getData("condition"))
	
	item.player:SetArmor(item:getData("condition"))
	
	local client = item.player
	
	local character = client:getChar()
		
	if (character:getData("gender") == "female") then
		character:setModel(item.setmodelfemale)
	else
		character:setModel(item.setmodel)
	end
		
		item.player:EmitSound("items/ammo_pickup.wav", 80)
		item:setData("equip", true)

		return false
	end,
	onCanRun = function(item)
		return (!IsValid(item.entity) and item:getData("equip") != true)
	end
}

hook.Add("ScalePlayerDamage", "nut_SuitDamage", function(client, hitgroup, dmginfo)
	local items = client:getChar():getInv():getItems()
	for k, v in pairs(items) do
		if (v:getData("equip", true)) then
			if (dmginfo:IsDamageType(DMG_BULLET)) then	
				dmginfo:ScaleDamage(client:getChar():getData("bullet_suit"))
			elseif (dmginfo:IsDamageType(DMG_CLUB)) then
				dmginfo:ScaleDamage(client:getChar():getData("impact_suit"))
			elseif (dmginfo:IsDamageType(DMG_SHOCK)) then
				dmginfo:ScaleDamage(client:getChar():getData("shock_suit"))
			elseif (dmginfo:IsDamageType(DMG_BURN)) then
				dmginfo:ScaleDamage(client:getChar():getData("burn_suit"))
			elseif (dmginfo:IsDamageType(DMG_RADIATION)) then
				dmginfo:ScaleDamage(client:getChar():getData("radiation_suit"))
			elseif (dmginfo:IsDamageType(DMG_ACID)) then
				dmginfo:ScaleDamage(client:getChar():getData("chemical_suit"))
			elseif (dmginfo:IsExplosionDamage()) then
				dmginfo:ScaleDamage(client:getChar():getData("explosion_suit"))
			end
		end
	end
end
)

function ITEM:onInstanced(invID, x, y)
	self:setData("condition", 100)
end

**Comment by Chessnut** [comment]
Did you add the onInstanced hook after you created the code before you made the equip code? If so, that hook only affects future instances. The same thing for ITEM.data since that is only used when instancing a new item.

**Comment by Rubberbandits** [comment]
Yes, I added the function then restarting the framework then created a new item
