### ISSUE TITLE
[1.1] Scoreboard is not updating.

### ISSUE THREAD

**Issue by Sascha8a** [Chessnut/NutScript#321]
When antother player joins the server and chooses his char the scoreboard doesn't show him. As soon I reload the server the scoreboard updates. I used the hl2rp ns 1.1 schema with then ewes ns version. I'm not running on the dev version of gmod.

**Comment by Chessnut** [comment]
Have you updated your framework? I fixed this a while ago.

**Comment by Sascha8a** [comment]
Yes. I downloaded it on the 4th of march. I'm getting it from
github.com/cheenut/Nutscrip/tree/1.1 and on the right side download to pc.
Am 05.03.2015 23:56 schrieb "Brian" <notifications@github.com>:

**Comment by Sascha8a** [comment]
I saw your changelog and it should be updated, but u tryed it out with a clean hl2rp schema and a clean modernrp schema. Maybe the error occours, because I removed the recognise plugin. I just removed it from the addona folder.

**Comment by Serconker** [comment]
That would most likely cause the problem you're getting.

**Comment by Sascha8a** [comment]
Negative. I tryed it with and without.
Am 06.03.2015 12:24 schrieb "Serconker" <notifications@github.com>:

**Comment by Serconker** [comment]
Have you made any other modifications?

**Comment by Sascha8a** [comment]
As I said, clean install of ns 1.1 and hl2rp schema.
Am 06.03.2015 12:26 schrieb "Serconker" <notifications@github.com>:
