### ISSUE TITLE
WEAPON ERROR

### ISSUE THREAD

**Issue by kkj4818** [Chessnut/NutScript#324]
![default](https://cloud.githubusercontent.com/assets/5549849/6539895/ccf886d8-c4c6-11e4-8151-5ac77980e6c7.PNG)
![2015-03-07_00001](https://cloud.githubusercontent.com/assets/5549849/6539897/d6d2547c-c4c6-11e4-85a4-f2d1cb8ab464.jpg)

Crossbow has model,class whose is smg

**Comment by Chessnut** [comment]
This is a NS HL2 RP issue. I'll have it fixed, but next time put it on the _HL2 RP Git_, not the NutScript one.
