### ISSUE TITLE
[NutScript 1.1] Plugin - Note (Make error)

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#327]
When you press the button Use, note is not created.

```
[ERROR] gamemodes/hl2rp/plugins/notes/sh_plugin.lua:62: attempt to index global
'WRITINGDATA' (a nil value)
  1. v - gamemodes/hl2rp/plugins/notes/sh_plugin.lua:62
   2. Run - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:379
    3. onRun - gamemodes/hl2rp/plugins/notes/items/sh_note.lua:27
     4. unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:665
      5. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:132
       6. unknown - lua/includes/modules/net.lua:32
```

**Comment by art-gur** [comment]
Video of the bug can be found here http://youtu.be/ecoCPUfXVPU?t=4m40s

**Comment by SchwarzKruppzo** [comment]
There is two entities with "nut_note" name. First - in note plugin. Second - in radio plugin and it's no has functions. The second simply overriding the first, and causing this issue.

**Comment by FlorianLeChat** [comment]
It's still a problem in 2021. I don't even understand why this file still exists. I think a lot of people think that the plugin doesn't work anymore when all you have to do is delete a file and everything works normally again, such a shame...
