### ISSUE TITLE
[Nutscript 1.1] Cursor remaining active after hitting enter twice.

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#333]
Sometimes when using the chat box addedto the new NS 1.1, when you hit enter, the chat box remains, but the field where you type remains with a flashing line/type cursor. Then when you hit enter again, it goes away, but your mouse stays out and you can't click, hit 'c' or 'q' or move or do anything. It winds up being a rejoin/restart to fix.

**Comment by Rubberbandits** [comment]
Press F3. or type in console fixchatplz

that should reload the chatbox and remove the cursor

**Comment by Chessnut** [comment]
I can't seem to get the cursor to stay even though it has happened a very few times before.

**Comment by CaptJack92a** [comment]
I have tried to recreate it, but it's like it's random, like putting the cursor away misses a tick/frame. Maybe if simply a small line was added to refresh it every time someone releases the 'c' or 'q' button?

I also tried to look for lua/console errors when/if it happened. Its clear of any of that.

**Comment by CaptJack92a** [comment]
This is still an issue. One of my most recent players just encountered it.

**Comment by Chessnut** [comment]
It's an issue that rarely occurs which makes it extremely hard to replicate. Just type `fixchatplz` in console.

**Comment by CaptJack92a** [comment]
Alright. I'll still try to keep an eye out for anything that might appear
in the console that might help identify it.
