### ISSUE TITLE
[Nutscript 1.1] Large screen resolution = tiny text

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#334]
Using Nutscript with a large resolution (2560x1440) makes the text in the game, such as the item descriptions, player name etc very small font, you need to really look closely to see such small font-size.

The chatbox takes almost 1/4 of the screen, and the text-size there is tiny as well, I could maybe fit up to 30 lines before I need to scroll..

I suppose this might be caused of the fonts not scaling to screen sizes? 
I'll try to post some screenshots if you wish to.

**Comment by Chessnut** [comment]
Post some screenshots so I know which font to add scaling to.

**Comment by blt950** [comment]
Here are two screenshots. First one you see the small text size and size when looking at players and char. Second shows how the "Inventory" gets cut on the bottom, this happens also in Config and Help.

![2015-03-11_00003](https://cloud.githubusercontent.com/assets/2505044/6600599/df738b44-c810-11e4-9e06-981ef5adf7c5.jpg)
![2015-03-11_00004](https://cloud.githubusercontent.com/assets/2505044/6600604/e3be1d0e-c810-11e4-9799-c918caf13a2c.jpg)

**Comment by blt950** [comment]
Not sure why you referenced to this issue, though this issue is not fixed, it's exactly the same.

**Comment by blt950** [comment]
Lastest commit fixes most of it, great! :)
Though chat one needs a little bit tweaking.

The text in writing box is cutting a bit and the IC / OOC etc buttons on top are a little bit too big :)

![2015-03-14_00001](https://cloud.githubusercontent.com/assets/2505044/6650999/f1edce1c-ca2f-11e4-8549-2addfcb0fab8.jpg)
