### ISSUE TITLE
[NutScript 1.1] The choice of weapons

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#336]
When a character is in a swoon (unconscious), using the mouse wheel can scroll weapons.

**Comment by Chessnut** [comment]
How'd you get weapons when fallen over?

**Comment by art-gur** [comment]
Using the mouse wheel.

**Comment by art-gur** [comment]
Also, when a character is dead, you can write in the IC chat.

**Comment by Chessnut** [comment]
I don't have weapons when fallen over. Are you giving yourself the?

**Comment by Daishii** [comment]
I can't reproduce this on my installation.

**Comment by art-gur** [comment]
After the update, this bug is no longer observed.
