### ISSUE TITLE
[NutScript 1.1] Bug with double doors

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#337]
When opening the double doors, one of them opens, the other is not. Commands /droosetparent and /doorsetchild not help.

![Screen](http://s1.hostingkartinok.com/uploads/images/2015/03/0ace8b01696eead6a59c77e91db53e62.jpg)

**Comment by Chessnut** [comment]
What map is this?

**Comment by art-gur** [comment]
rp_city17_build192

**Comment by Daishii** [comment]
This isn't happening on rp_industrial17_v1 with the same type of doors seen in the picture.
