### ISSUE TITLE
[NutScript 1.1] Adding custom spawns not working

### ISSUE THREAD

**Issue by Daishii** [Chessnut/NutScript#343]
Hi! I'm getting the following error while trying to add spawns in the HL2RP schema.

Commands tried:
/spawnadd metropolice
/spawnadd metropolice unit

> [ERROR] gamemodes/nutscript/plugins/spawns.lua:125: bad argument #1 to 'pairs' (table expected, > got nil)
>  1. pairs - [C]:-1
>   2. onRun - gamemodes/nutscript/plugins/spawns.lua:125
>    3. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:140
>     4. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:175
>      5. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:236
>       6. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:84
>        7. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:132
>         8. unknown - lua/includes/modules/net.lua:32

I am not receiving any messages in-game, this only appeared in the server console. The spawn isn't added.

**Comment by Daishii** [comment]
ERROR] gamemodes/nutscript/plugins/spawns.lua:99: attempt to index field 'spawns' (a nil value)
  1. onRun - gamemodes/nutscript/plugins/spawns.lua:99
   2. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:140
    3. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:175
     4. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:236
      5. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:84
       6. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:132
        7. unknown - lua/includes/modules/net.lua:32

**Comment by Chessnut** [comment]
On the server, run `lua_run PrintTable(nut.plugin.spawns)` and tell me the output

**Comment by Daishii** [comment]
[ERROR] lua/includes/extensions/table.lua:745: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:745
    3. PrintTable - lua/includes/util.lua:42
     4. unknown - lua_run:1

[ERROR] lua/includes/extensions/table.lua:745: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:745
    3. PrintTable - lua/includes/util.lua:42
     4. unknown - lua_run:1

[ERROR] lua/includes/extensions/table.lua:745: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. GetKeys - lua/includes/extensions/table.lua:745
    3. PrintTable - lua/includes/util.lua:42
     4. unknown - lua_run:1

**Comment by Chessnut** [comment]
Try updating now.

**Comment by Daishii** [comment]
Spawns get added. But it seems to be ignoring the [string class] of the faction.

/addspawn metropolice cp_rct will add the spawnpoint, but in the spawns.txt it shows up as cp_elite - if the factions have no class, then the spawn works correctly.
