### ISSUE TITLE
[NutScript 1.1] Chat error

### ISSUE THREAD

**Issue by Daishii** [Chessnut/NutScript#344]
The chat will randomly give out this error:

> [ERROR] gamemodes/nutscript/plugins/chatbox/derma/cl_chatbox.lua:70: unfinished capture
>  1. match - [C]:-1
>   2. unknown - gamemodes/nutscript/plugins/chatbox/derma/cl_chatbox.lua:70

It will appear multiple times in the console, and cause the game to print out "Something is creating script errors".

**Comment by Chessnut** [comment]
What are you typing?

**Comment by Daishii** [comment]
Just regular chatting with players.
