### ISSUE TITLE
[NutScript 1.1] Faction owned doors don't lock/unlock

### ISSUE THREAD

**Issue by Daishii** [Chessnut/NutScript#346]
Doors owned by a faction can not be locked/unlocked by the members of the faction.

**Comment by Chessnut** [comment]
Well the door can only be opened/closed by members of that faction so it wouldn't really matter.

**Comment by Daishii** [comment]
Would it then be possible to implement it like so that the factions are given lock/unlock access to the doors, instead of blocking other people for opening the doors completely?

**Comment by Daishii** [comment]
This seems to have broken the saving of faction owned doors. Other door modifications save normally, but new faction owned doors don't save.
