### ISSUE TITLE
Add /doorsethidden like in NS 1.0 (suggestion)

### ISSUE THREAD

**Issue by Daishii** [Chessnut/NutScript#351]
There was a feature in NS 1.0 called /doorsethidden and I think it would be a very good addition to NS 1.1 as well.

**Comment by art-gur** [comment]
This command already has /doorsetdisabled

**Comment by Daishii** [comment]
It isn't the same command. When you do /doorsetdisabled on a door, you are unable to interact with it.

**Comment by SchwarzKruppzo** [comment]
Yes, It was very useful in NS 1.0, and would be in NS 1.1 too.

**Comment by blt950** [comment]
Ah yes, this would be great.
On a side note, is there a way to make all doors hidden by default?

**Comment by Daishii** [comment]
I like BLT's idea of having a command to set all doors hidden by default. Should be implemented as well!

**Comment by blt950** [comment]
More like a setting, but yes.

**Comment by Daishii** [comment]
I don't want to make a new issue - so I'll bump this one. Hidden doors can be purchased and locked/unlocked by the owner.
