### ISSUE TITLE
[Nutscript 1.1] Suggestion: Weapon Attachments

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#353]
Would be nice if you could make items who are equipped attach as a dummy model on the player itself. Such as if you got a equipped MP7, but not unholstered, it'll be on your back. 9mm on your side and so on.

**Comment by art-gur** [comment]
Good idea. Still, it is desirable to add a list that could regulate to display a weapon.

**Comment by Trixas** [comment]
ModernRP schema has it, porting it into NS 1.1 plugin would be great.
Why plugin? Because some people doesnt like that.
+Support

**Comment by Daishii** [comment]
I agree, this is a great idea!

**Comment by DemetriussXVII** [comment]
NS 1.0 had a plugin to do so. I might try to port it or simply make a brand new one for NS 1.1. I'll see about that.

**Comment by blt950** [comment]
I figured it out, there is already function for this. Just add shared side anywhere. Example under.

HOLSTER_DRAWINFO["weapon_pistol"] = { bone = "ValveBiped.Bip01_R_Thigh", model = "models/weapons/w_pistol.mdl", pos = Vector(2, 5, -3), ang = Angle(-10, 180, 60) }

**Comment by PrestonGarvey** [comment]
So Im new to developing, however I would like to get this into a gamemode. How would I get to doing this?
