### ISSUE TITLE
[Nutscript 1.1] /me is unknown. [PhysDesc] Says stuff.

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#356]
When speaking ICly, the physical description works, but when using a /me, it turns to "Unknown does something."

Rolls are also as unknown.

**Comment by Chessnut** [comment]
Did you alter something that changes your name?

**Comment by CaptJack92a** [comment]
Not for the factions o tested this on, no. Only thing I added/altered was a
replacement for the mpf faction so their names were automatically generated
with ranks and numbers. But that's only in that one faction file.

**Comment by DeadiKation** [comment]
Can confirm same, It's quite confusing to get a PM from "unknown" as well as to see "unknown has rolled a 76"

**Comment by Chessnut** [comment]
Was this after a certain update?

**Comment by CaptJack92a** [comment]
Not that I can remember. It's been like this for a bit. I'l look for something in the recognition system...

Speaking, yelling, and whispering icly all work fine. Here's a strip of code I found in the nutscript recognition system. Perhaps this has something to do with it?

if (CLIENT) then
	local whitelist = {}
	whitelist["ic"] = true
	whitelist["y"] = true
	whitelist["w"] = true

**Comment by Chessnut** [comment]
No, the thing was unknown was being returned by default even if the chat type existed and not explicitly defined to use the recognition system. The chat type provided for the `GetPlayerName` hook is nil when drawing the name, like on a character or on the scoreboard, which is when unknown should be returned. I fixed it so it will only return unknown if the chat type passed is nil, so only show unknown when drawing the player's name or on the scoreboard.

**Comment by CaptJack92a** [comment]
I see, so that's why it covers PM's and /me's and a few other things, because it doesn't see it as ooc, but also doesn't see anything telling it to replace it with the description?

**Comment by Chessnut** [comment]
The white list is the types that explicitly use the recognition system. Everything else does not by default.

**Comment by Chessnut** [comment]
So I assume this is fixed.

**Comment by CaptJack92a** [comment]
Checking...
