### ISSUE TITLE
[NutScript 1.1] Recognize

### ISSUE THREAD

**Issue by OniChanChan** [Chessnut/NutScript#357]
I took some code from NS 1.0 for a faction to recognize eachother. You recognize a person on the scoreboard, but when looking at them it's still unknown.

function SCHEMA:IsPlayerRecognized(client)
	if (client:Team() == FACTION_(faction)) then
		return true
	end
end

**Comment by blt950** [comment]
Ah yes, was just about to suggest the same. 
Should be more like a variable at the top like:

FACTION.isCommonlyRecognised = true/false

**Comment by OniChanChan** [comment]
Ya, I agree

**Comment by art-gur** [comment]
A very useful thing!

**Comment by Trixas** [comment]
I was thinking about it, useful thing
+support

**Comment by Daishii** [comment]
I like BLT's suggestion on this. I was going to suggestion myself when I noticed that the Combine don't recognize each other by default.

**Comment by Chessnut** [comment]
Added `FACTION.isGloballyRecognized`
