### ISSUE TITLE
[1.1] Menu Suggestion

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#358]
I've not yet found a use of F2 or F4 button. What about making them as a shortcut to open inventory?

Also: When you press "Characters" from F1 menu, it should be able to press F1 again to exit. Easier than pressing return and waiting for everything to fade.

**Comment by Trixas** [comment]
It would make access to inventory or something else faster, because sometimes every second matters.
+Support

**Comment by Chessnut** [comment]
We'll have to see about this because the keys may be used by schemas/plugins which would make conflict. It's better to set a standard for these keys not to be used by the menu because when a schema/plugin does override the keys, it will cause a conflict with what is expected.

**Comment by blt950** [comment]
Fair enough, though at least implementing functionality for F1 while in character menu (when directed from F1 menu), to close it could be done?
