### ISSUE TITLE
[1.1] Texts bugs/improvement required

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#360]
Impossible to see the text due to brightness or maybe missing outlines or something.
Schema: HL2RP

![2015-03-14_00004](https://cloud.githubusercontent.com/assets/2505044/6651543/88ba8184-ca47-11e4-810f-c4adbd5b1ec8.jpg)
![2015-03-14_00005](https://cloud.githubusercontent.com/assets/2505044/6651544/8b5f437a-ca47-11e4-8164-8c7472333248.jpg)

**Comment by blt950** [comment]
Also a clipping bug in the texts..

![2015-03-14_00006](https://cloud.githubusercontent.com/assets/2505044/6651604/6f5ef0e2-ca49-11e4-98b1-6a39803e0a4f.jpg)

**Comment by Chessnut** [comment]
You'll either need to turn off HDR/Bloom or change the color of the text to be more grey. As for the clipping, not much I can do about it.

**Comment by blt950** [comment]
Overriding the bloom effect in Q menu suppose did improve. Though I had to change the default font to like Arial to make it more readable.

I suppose I'm not the only one having this issue with brightness, as it's implemented in the schema itself?

**Comment by Chessnut** [comment]
The brightness is from the engine.

**Comment by blt950** [comment]
Oh well, I understand. Thanks though.
