### ISSUE TITLE
[1.1] Whitelist bug?

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#361]
I got two factions. "Vortiguant" and "Enslaved Vortiguant".

When I do whitelist "Vortiguant", I get whitelist for "Enslaved Vortigaunt". I think the command needs to be more sensitive.

/plywhitelist test "Vortiguant" -> Enslaved Vortigaunt whitelist

**Comment by OniChanChan** [comment]
I am pretty sure you can call it by the FACTION_(Name).
So if FACTION_VORT was regular vortigaunt, then you could do /plywhitelist "Name" Vort, thats how I did it for me.

**Comment by blt950** [comment]
That says invalid faction to me.

Though I think the issue here is that when it searches for the faction with the name, it chooses Enslaved first because there are two results, and Enslaved is the alphabeticly first one.

**Comment by Chessnut** [comment]
You should now be able to enter the _exact_ uniqueID (usually the file name without the sh_ infront) which is case sensitive to specify which faction.
