### ISSUE TITLE
[1.1] Suggestion: Presist

### ISSUE THREAD

**Issue by TheOnlyDusk** [Chessnut/NutScript#362]
It would be kinda nice to have a presist system in 1.1 like there were in 1.0

**Comment by Chessnut** [comment]
Hold C, Persist.

**Comment by CaptJack92a** [comment]
The problem with that method is that if anyone touches whatever you persist with a physgun, it falls and restarting the server does not fix it. The mess remains.

**Comment by OniChanChan** [comment]
Another problem is, on restarts the props are deleted.

**Comment by CaptJack92a** [comment]
That one isn't necessarily true. If you use the _restart command in console or Rcon they will remain.

**Comment by daxxom** [comment]
Wait, what happens if the server crashes?
Sorry for the necro posting but i'm currently having an issue with objects persisting through my restarts.
