### ISSUE TITLE
[Nutscript 1.1] Radio bug

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#371]
A minor error causes the radio to every now and then, most often when the player using it lags even for barely a moment, the radio makes its sounds and works, but does not show up in the text. A temporary solution I have found is to toggle it off then on, but this does not work every time.

**Comment by Sascha8a** [comment]
I've got the same error.
Am 15.03.2015 06:19 schrieb "CaptJack92a" <notifications@github.com>:

**Comment by Chessnut** [comment]
See #371.
