### ISSUE TITLE
[Nutscript 1.1] Business menu available to all

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#374]
I know I put up a TON Of bug reports left and right, but it's because I am testing ns 1.1 full force by running a server in full on alpha/beta mode and players helping me find things brings up a lot of issues to bring here.

The business menu is not hidden to anyone. Having/not having a permit, doesn't matter. If you have the money to buy it, you can.

**Comment by blt950** [comment]
Agree here, I've the same. Would be nice with a setting or/and a flag that gives you access to it, so it's easier to restrict :)

**Comment by Daishii** [comment]
It was like that in NS 1.0 - there was a FACTION.businessAllowed = true/false

**Comment by blt950** [comment]
That would work, but that sucks if you want to give citizens possibility to run business, but only if they got a permit for it. Maybe make an additional item like "Business permit" which can be given to the characters who even got FACTION.businessAllowed on true, so it overrides that decision.

**Comment by Daishii** [comment]
That would be an even better idea.

**Comment by Chessnut** [comment]
This is all schema specific.
