### ISSUE TITLE
Console Error and All item codes are same

### ISSUE THREAD

**Issue by kkj4818** [Chessnut/NutScript#377]
![default](https://cloud.githubusercontent.com/assets/5549849/6654904/7ffd54b0-cb26-11e4-9fdc-b534ee03d1fd.PNG)

Item code video
https://www.youtube.com/watch?v=IUr5bDBPIqg

**Comment by Chessnut** [comment]
Use `nut_recreatedb` since it seems like your database structure is corrupted or something

**Comment by kkj4818** [comment]
It got solved, thank you
