### ISSUE TITLE
[1.1] entity:IsPlayerHolding() 

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#383]
I believe this function is nil, tried to use it myself somewhere else as well.
And this probably produces a bug:

When you pick up a object with your hand, and press right mouse button again while holding a object, it drops it and picks it up again quickly in air. I believe this happens due to IsPlayerHolding() doesn't know if the player is holding the item or not?

Another small annoying thing: Since E is the button to drop items, I think it should be changed to R, or at least don't make the item menu pop-up if it's pressed E on just to drop it.

**Comment by Chessnut** [comment]
The pick-up system is in the engine. I can't change which letter does what for the dropping.

**Comment by blt950** [comment]
I understand. Thought it should be possible to detect at least if you've something in your hand or not?
So you could fix that drop-pick "bug".

On the other hand, is there ways to tweak the pick-up system? Because running with a object in your hand doesn't work that well, as the object stops your speed.

**Comment by Chessnut** [comment]
I already fixed that, try updating. And again, I can't teak it because it is handled in the engine.

**Comment by blt950** [comment]
Yeah, I saw it now in the commit log after I posted it. Thanks.
