### ISSUE TITLE
[1.1] Save Intervals

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#386]
I noticed the only place the server runs SaveData() on plugins and similar is on GM:ShutDown()

There should be an interval as well, what if the server crashes? GM:ShutDown() does not get called then? And I loose every change in plugins on that run.

**Comment by Chessnut** [comment]
Most plugins should already save their data as soon as something is created or changed.

**Comment by blt950** [comment]
Fair enough point really.
