### ISSUE TITLE
[1.1] Sub-folders/menus

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#389]
Two suggestions that would be nice to have.

1. Would be nice if it was possible to add sub-menus on scoreboard derma menu (when you click on players) menu.

2. Would be also nice if F1 HELP menu could have sub-folders. So I could add like "Guides" and then some guides underneath it.

**Comment by Chessnut** [comment]
1. `function PLUGIN:ShowPlayerOptions(client, options)
	options["Say Name"] = function()
		RunConsoleCommand("say", client:Name())
	end
end`

2. Okay

**Comment by blt950** [comment]
First thing: I'm aware of this one, this creates one menu. I'm talking about sub-menu within it like..
|- Say Name
|--- My name
|--- Your name

Second thing: Not sure what you mean here.

**Comment by Chessnut** [comment]
You're just going to have to do this manually, sorry.
