### ISSUE TITLE
Pistol and Revolver crouch models are T-POSE

### ISSUE THREAD

**Issue by kkj4818** [Chessnut/NutScript#397]
![2015-03-18_00001](https://cloud.githubusercontent.com/assets/5549849/6707357/a9e180d2-cda9-11e4-9d6c-68ea68e9a420.jpg)
![2015-03-18_00002](https://cloud.githubusercontent.com/assets/5549849/6707358/a9ea47b2-cda9-11e4-8289-06defdba7df6.jpg)

**Comment by art-gur** [comment]
I have on the server does not have these errors, but in the choice of the character he is in the T position.
