### ISSUE TITLE
[NS 1.1] Intro problems

### ISSUE THREAD

**Issue by Turnip0** [Chessnut/NutScript#399]
I installed NS 1.1 and the hl2rp 1.1 branch on both a lan server and singleplayer modes and they both give me the same problem. Every time I join/rejoin or start a game it just gives me this in both singleplayer (set as a 2-player LAN server), and a local dedicated,
![](http://puu.sh/gGmID/8720e038c4.png)
and nothing else. I've no idea what's causing this, since there aren't any errors in console or anything.

**Comment by CaptJack92a** [comment]
I know there is an intro, but I never see it at all. I thought it was simply because I already had characters made, but I miss it. While this is being looked into, can we have in the config two options? "Only show intro for first timers." Or "Show for all."

**Comment by Chessnut** [comment]
Did you check for server-side errors?

**Comment by Turnip0** [comment]
There weren't any errors at all, strangely enough
![](http://puu.sh/gJk08/53f64380dd.jpg)
I press space to continue and this pops up as well, but only for a fraction of a second. That's really the only thing that's noteworthy, though.

**Comment by Turnip0** [comment]
I sent both the nutscript and schema folders to a friend to see if he had the same problem, and he got past the intro fine. Same everything. Could it be a problem with an addon or my os?

**Comment by Turnip0** [comment]
Got it fixed. The issue was a few conflicting addons;
NextBot Zombies, Nightmare House 2 Zombies, and Underhell Infected NextBots all by sean. You can go ahead and close this.

**Comment by Chessnut** [comment]
That doesn't explain why the NextBoxs would cause this.

**Comment by Turnip0** [comment]
I have no idea, but as soon as I removed them, both PAC3 and the schema worked perfectly.
