### ISSUE TITLE
[NutScript 1.1] Inventory bug

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#409]
In some strange way, jar drove a weapon. And when you collect your inventory new items, writes that there is no free space.
![Screen](http://s1.hostingkartinok.com/uploads/images/2015/03/531a2eef64316b26b0e5e92788efcae1.jpg)

**Comment by Chessnut** [comment]
You made your inventory get out of sync somehow. Try rejoining.

**Comment by art-gur** [comment]
Yes, rejoining helped.

**Comment by Chessnut** [comment]
Is this fixed?

**Comment by art-gur** [comment]
Yes.
