### ISSUE TITLE
Store plugin data in the database

### ISSUE THREAD

**Issue by Chessnut** [Chessnut/NutScript#414]
It would be easier to manage tables and allows for cross-server use of data. Hopefully this can resolve some issues with data being deleted. If one row is corrupted for some reason, the whole data will not be deleted either.

**Comment by art-gur** [comment]
Good idea. In many ways, will be useful.

**Comment by Chessnut** [comment]
Problem is, will this require each plugin to create their own tables?

Or should there be one giant table that holds all data.
| _id | _name | _value | _map | _schema |

**Comment by art-gur** [comment]
I think the are best stored a large table in the database.

**Comment by Chessnut** [comment]
The plugins are going to have to create their own tables if this were to be implemented.
