### ISSUE TITLE
Not recieving paychecks

### ISSUE THREAD

**Issue by KillingPigs123** [Chessnut/NutScript#415]
My paychecks were not working, even if I changed FACTION.pay to FACTION.salary, it would still not work. Here is my code:

FACTION.name = "Survivor"
FACTION.isDefault = true
FACTION.desc = "A good-reputation survivor which has survived some of the nuclear bombs in the past."
FACTION.color = Color(20, 150, 15)
FACTION.pay = 10

local CITIZEN_MODELS = {
	"models/humans/group01/male_01.mdl",
	"models/humans/group01/male_02.mdl",
	"models/humans/group01/male_04.mdl",
	"models/humans/group01/male_05.mdl",
	"models/humans/group01/male_06.mdl",
	"models/humans/group01/male_07.mdl",
	"models/humans/group01/male_08.mdl",
	"models/humans/group01/male_09.mdl",
	"models/humans/group01/female_01.mdl",
	"models/humans/group01/female_02.mdl",
	"models/humans/group01/female_03.mdl",
	"models/humans/group01/female_04.mdl",
	"models/humans/group01/female_06.mdl",
	"models/humans/group01/female_07.mdl"
}
FACTION.models = CITIZEN_MODELS
FACTION_SURVIVOR = FACTION.index

**Comment by Chessnut** [comment]
Are you updated to the most recent commit? Are there errors in the server console?

**Comment by art-gur** [comment]
Chesnut, there is a bug where you come for a fraction, for example civil defense play for her, and then choose the character of a citizen, then you get the salary that the employee was a civil defense.

**Comment by KillingPigs123** [comment]
Yes, @Chessnut, and there are no errors in the console

**Comment by Chessnut** [comment]
Just an FYI, there is a close button next to the comment button if you need to close it.

**Comment by PapaFitta** [comment]
HOW DID YOU FIX THIS

**Comment by GlorifiedPig** [comment]
this is 3 years old on an outdated version lol

**Comment by PapaFitta** [comment]
LMAO Im amazed you actually replied to this but yeah probably. Doesnt work and everyone Ive spoke to says its
FACTION.pay and FACTION.payTime
but that doesnt work
