### ISSUE TITLE
[1.1] Help Webpages

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#418]
Could you make it possible to add webpages to the Help tabs? 
So I can make a link "Forum" which opens the forums in the box.

**Comment by Chessnut** [comment]
I accidently implemented it on the menu buttons too. So now you can do:

``` lua
hook.Add("CreateMenuButtons", "showGoogleTab", function(tabs)
    tabs["Google"] = "https://google.com"
end)
```
