### ISSUE TITLE
[1.1] Overriding Names

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#419]
Could there be added a way to override names of players?

I tried overriding function PLUGIN:GetDisplayedName(client, chatType), though it had no effect before a LUA refresh due to other changes I made on server. 

Such override is ment to replace the text "Unknown" or even the real name if it's recognized.
If you don't feel to add this, could you explain how I can properly override this function?

**Comment by Chessnut** [comment]
Can you show me your code for the function?

**Comment by blt950** [comment]
It seems that it suddenly works properly again, maybe I just did something wrong.
I'll re-post a new issue if the issue presists again.
