### ISSUE TITLE
[1.1] Add Observer canAccess hook

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#421]
Observer plugin should have a hook so you can manually define who can access observer, or a config in the nutscript itself.

**Comment by blt950** [comment]
Be sure to merge #406 and #407 before you do this please :+1:

**Comment by Chessnut** [comment]
Well observer is just no-clip. If you want to disable observer, then return false on PlayerNoClip

**Comment by blt950** [comment]
That's true, though my operators don't have access to "Nutscript Observer". As we use ULX, they can now only get into observer by typing !noclip, and they're not inivisble or anything such as the "Nutscript Observer" covers for normal admins and superadmins.

I don't wish to disable the observer.

**Comment by Chessnut** [comment]
Shouldn't client:IsAdmin() return true for operators then?

**Comment by blt950** [comment]
I doubt it does that, because none of my "adminOnly = true" commands work for my operators, and I haven't seen any setting which ULX defines operator as IsAdmin() == true.
