### ISSUE TITLE
[1.1] Multiple Models for Factions

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#423]
I can seem to only have on model each faction, or one as "male" and "female". More than one creates errors.

Example of list that makes error:
FACTION.models = {
	"models/humans/group17/female_01.mdl",
	"models/humans/group17/female_02.mdl",
	"models/humans/group17/female_03.mdl",
	"models/humans/group17/female_04.mdl",
	"models/humans/group17/female_06.mdl",
	"models/humans/group17/female_07.mdl"
	"models/humans/group17/male_01.mdl",
	"models/humans/group17/male_02.mdl",
	"models/humans/group17/male_03.mdl",
	"models/humans/group17/male_04.mdl",
	"models/humans/group17/male_05.mdl",
	"models/humans/group17/male_06.mdl",
	"models/humans/group17/male_07.mdl",
	"models/humans/group17/male_08.mdl",
	"models/humans/group17/male_09.mdl"
}

**Comment by Chessnut** [comment]
Can you list the error?

**Comment by blt950** [comment]
Ah yes, I forgot to add you that.

```
[ERROR] gamemodes/hl2rp/schema/factions/sh_minister.lua:12: '}' expected (to close '{' at line 5) near '"models/humans/group17/male_01.mdl"'
  1. unknown - gamemodes/hl2rp/schema/factions/sh_minister.lua:0
```

```
FACTION.name = "Minister"
FACTION.desc = "A minsiter of a specific department"
FACTION.color = Color(237, 179, 97)
FACTION.isDefault = false
FACTION.models = {
	"models/humans/group17/female_01.mdl",
	"models/humans/group17/female_02.mdl",
	"models/humans/group17/female_03.mdl",
	"models/humans/group17/female_04.mdl",
	"models/humans/group17/female_06.mdl",
	"models/humans/group17/female_07.mdl"
	"models/humans/group17/male_01.mdl",
	"models/humans/group17/male_02.mdl",
	"models/humans/group17/male_03.mdl",
	"models/humans/group17/male_04.mdl",
	"models/humans/group17/male_05.mdl",
	"models/humans/group17/male_06.mdl",
	"models/humans/group17/male_07.mdl",
	"models/humans/group17/male_08.mdl",
	"models/humans/group17/male_09.mdl"
}
FACTION.pay = 20
FACTION.isGloballyRecognized = true

FACTION_MINISTER = FACTION.index
```

**Comment by tltneon** [comment]
You forgot a comma at line 12

**Comment by blt950** [comment]
Well that's embarrasing - haha. Thanks.

**Comment by Comrade11111** [comment]
One question how does one add models to factions and the models also have body groups that where checked?
