### ISSUE TITLE
[1.1] Too long descriptions error required

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#427]
Once a player adds a too long description on character creation, they get "An error has occured", which I see in console is a MySQL error, due to the description being too long. 
Could be the case at F1 menu description as well, haven't tested that part.

**Comment by Chessnut** [comment]
What's the MySQL error say?

**Comment by blt950** [comment]
I beleive it's this one. It prints out as red in the console.

```
* INSERT INTO nut_characters (_model, _faction, _steamID, _lastJoinTime, _createTime, _money, _schema, _name, _desc) VALUES ('models/humans/group01/male_07.mdl', 'citizen', 76561198079438973, 1427567006, 1427567006, 100, 'hl2rp', 'Jericho Galloway', '6\'0ft | Dark brown hair[Cropped on the sides]| Blue eyes | Short brown beard /w dashes of grey | Scarring on neck | Old scar on top lip | Straight posture | Medium built physique | Rolled up sleeve blue shirt[White T-shirt]| Black leather belt | Blue Jumpsuit Pants | Brown Duty Boots | Bandaged wrap around each hand | | ')
```

**Comment by Chessnut** [comment]
Isn't there another line that gives a specific error?

**Comment by blt950** [comment]
Nope, there is a blank line underneath each of them, could be a error that was supposed to be printed there but did not.

**Comment by Chessnut** [comment]
You'll need to re-create the database structure since I altered the type of data for the character description.
