### ISSUE TITLE
[1.1] chargiveitem return

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#432]
The /chargiveitem returns a language path that doesn't exist, in addition to another notification saying "false". Probably some leftover debugging.

**Comment by Chessnut** [comment]
It probably means that the item could not fit or might not exist.

**Comment by blt950** [comment]
Yeah, I mean it does the langauge thing (which doesnt exist) "invalidItem". So when I try to give a player a thing that doesn't exist, it says in notify:

|- false
|- invalidItem

I ment to say to remove the false and maybe add language for invalidItem :)

**Comment by Chessnut** [comment]
Well this is just printing the output of trying to add an item to the inventory. This command was really for developers, so there isn't a big need.

**Comment by blt950** [comment]
I would say "invalidItem" kind of covers that, but it's up to you :P
