### ISSUE TITLE
NS 1.1 Intro

### ISSUE THREAD

**Issue by vingard** [Chessnut/NutScript#433]
[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_intro.lua:33: attempt to concatenate field 'author' (a nil value)
1. OnEnd - gamemodes/nutscript/gamemode/core/derma/cl_intro.lua:33
   1. unknown - lua/includes/extensions/client/panel/animation.lua:48

When I start the server and I go in I am stuck at the NS 1.1 Screen and get this.

**Comment by Chessnut** [comment]
Did you not have `SCHEMA.author` in your sh_schema.lua file?

**Comment by Chessnut** [comment]
Fixed in the recent update anyways, so it would not matter.
