### ISSUE TITLE
NS Gamemode 

### ISSUE THREAD

**Issue by vingard** [Chessnut/NutScript#434]
When i fire up the Sample Schema I get this:

[ERROR] gamemodes/sample/gamemode/cl_init.lua:3: attempt to index field 'schema' (a nil value)
1. unknown - gamemodes/sample/gamemode/cl_init.lua:3

Couldn't Load Init Script: 'sample/gamemode/cl_init.lua'
Default clips will be not be modified
Couldn't include file 'sample\schema\sh_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 32))
 And the menu just says Disconnect.

**Comment by Chessnut** [comment]
You can't use a 1.0 schema with 1.1
