### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by Spygas** [Chessnut/NutScript#438]
I'm having an issue where, when hosting a dedicated server and when I've set myself as owner/admin/superadmin, the script will not allow me to add any characters to whitelists? 
It simply says, "You are not allowed to do that" followed by the character name. 

Is there any way I can get around this to allow myself to add or change whitelisting? 
Typing in console doesn't work either, it simply goes into chat...

**Comment by Chessnut** [comment]
Works fine for me?

**Comment by ValeTheVioletMote** [comment]
I am having the same issue. Attempting to whitelist myself after I've placed myself in superadmin via ULX, and I'm getting "You are not allowed to do this." Same issue for giving and taking flags. It's as if I'm not getting superadmin in the eyes of nutscript.

**Comment by Chessnut** [comment]
NutScript just uses GMod's client:IsSuperAdmin() function so it sounds like something with your rank is set wrong

**Comment by ValeTheVioletMote** [comment]
I pulled the latest ULX release from git. Could that be the problem, or is it something messed up deeper? I could try looking for a assured stable ULX, I suppose. I'll post back here if I resolve the issue.

**Comment by ValeTheVioletMote** [comment]
[ERROR] lua/includes/extensions/string.lua:68: attempt to index local 'str' (a nil value)
1. PatternSafe - lua/includes/extensions/string.lua:68
   1. findPlayer - gamemodes/nutscript/gamemode/core/sh_util.lua:94
   2. findPlayer - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:130
      1. onRun - gamemodes/nutscript/gamemode/core/sh_commands.lua:470
      2. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:145
      3. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:180
      4. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:248
         1. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
         2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
         3. unknown - lua/includes/extensions/net.lua:32

I got this when I demoted myself to just admin and tried the command (/plywhitelist).

(and for some reason github comments is displaying this weird, but it's numbered 1-10, not 1, a, b, ii, etc

**Comment by Chessnut** [comment]
That means you didn't enter a name/faction for /plywhitelist

**Comment by Chessnut** [comment]
Updating should fix that error.

**Comment by ValeTheVioletMote** [comment]
Tried it, worked. So for whatever reason, setting myself as "superadmin" via ULX didn't work, but "admin" gave me the appropriate privileges. Thanks for helping me, on an already closed thread at that. Only reason I posted in here is because it's well indexed by google as a search result for this issue, so anyone else searching for a resolution might find the answer here.

**Comment by ValeTheVioletMote** [comment]
To note, there are different permissions. I have to be set as superadmin to modify the server's configuration in the main menu (the Config tab). Superadmin (for me at least) does not have access to the commands admin has access to: flag modification & whitelisting

**Comment by LukeCall** [comment]
I can also relate to this bug. It's kind of annoying switching from admin to super admin just for the config and vice versa for the admin commands.

**Comment by Misterbobbie** [comment]
ULX doesnt let the gamemode load

**Comment by ColinLutter** [comment]
Wich version of nutscript do  you use ?

**Comment by Misterbobbie** [comment]
^^ I fixed it
