### ISSUE TITLE
Viginette not downloaded with workshop collection, obscures screen

### ISSUE THREAD

**Issue by botchi09** [Chessnut/NutScript#439]
Sometimes the viginette is not downloaded and I think this is because my friend is using a command line workshop collection to manage all the downloading. The viginette not being present means the entire screen is obscured and the user can't see anything.

A fallback/workshop of the NS content might be useful here

**Comment by tltneon** [comment]
You can use this addon http://steamcommunity.com/sharedfiles/filedetails/?id=300746843

**Comment by botchi09** [comment]
Thanks for the help, but I'm not really looking for the rest of that content- I just want this file available or a workaround

**Comment by Chessnut** [comment]
Look in the content folder for NutScript
