### ISSUE TITLE
[NutScript 1.1] Inventory vehicle bug

### ISSUE THREAD

**Issue by FlammableAce** [Chessnut/NutScript#442]
Buying a vehicle bugs your inventory and returns this error 

[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105: bad argument #2 to 'L' (no value)
1. L - [C]:-1
   1. setInventory - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105
   2. callback - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:401
      1. DoClick - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:171
      2. unknown - lua/vgui/dlabel.lua:218

**Comment by Chessnut** [comment]
Your item is either missing a name or a description.

**Comment by FlammableAce** [comment]
Here is one of the vehicle files, even the default vehicles that come with rebels' vehicle plugin return the error which makes me think the plugin may be broken

ITEM.name = "Ferrari 458"
ITEM.model = "models/lonewolfie/ferrari_458.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.maxGas = 1000
ITEM.price = 35000
ITEM.vehicleData = {
    type = TYPE_GENERIC,
    model = ITEM.model,
    script = "scripts/vehicles/LWCars/ferrari_458.txt",
    name = ITEM.name,
    physDesc = ITEM.physDesc,
    maxGas = ITEM.maxGas,
}

**Comment by art-gur** [comment]
Try adding, as Chessnut said, description. For example: ITEM.desc = "The best Ferrari car"

**Comment by FlammableAce** [comment]
Wow lol, how did I miss that after chessnut said it. I will blame it on not having my morning cup of tea yet. 

Thanks for pointing it out

**Comment by FlammableAce** [comment]
Adding a description still didn't fix the problem

**Comment by Chessnut** [comment]
I updated NS1.1 to have a default item description.
