### ISSUE TITLE
Mysql problem

### ISSUE THREAD

**Issue by Aberidius** [Chessnut/NutScript#443]
So i am using Xampp to use my own database instead of the sqlite (it deletes the characters after a while) but when i change to mysqloo or mysql14 is just shows an error in console.

What should i do?

**Comment by Chessnut** [comment]
What's the error?

**Comment by Aberidius** [comment]
Here's my sv_config.lua

http://pastebin.com/kZBXYcdX

When i start the server, this error pops up:

Couldn't include file 'includes\modules\mysqloo.lua' (file not found)

I havent added any mysqloo files myself or so.

**Comment by Chessnut** [comment]
How do you expect mysqloo to work if you did not install it?

**Comment by Aberidius** [comment]
But where do i install it then?

**Comment by Chessnut** [comment]
You need to download mysqloo (google it) and place the module into lua/bin
and libmysql.dll where srcds is
