### ISSUE TITLE
[1.1] Flickering Shadows

### ISSUE THREAD

**Issue by zambony** [Chessnut/NutScript#444]
I just recently updated to 1.1 and immediately I notice player shadows and dynamic prop shadows flicker frantically, as in suddenly they're very sharp and detailed, and then they're very blurry and scattered with no discernable detail. This happens every like, 0.2 seconds. Everyone on my server notices it too.

**Comment by Chessnut** [comment]
Does this only happen on 1.1?

**Comment by zambony** [comment]
As far as I can tell. As well, I transitioned over like one file at a time to preserve my custom edits, and I noticed it happening after I replaced the animations system with the new one. I have no edits made to how animations work, so I'm fairly certain it's nothing I've done.

**Comment by Chessnut** [comment]
The animation system doesn't affect rendering.

**Comment by zambony** [comment]
I should hope not, but that's when I noticed it happening. I'll look around for other files I replaced as well.

**Comment by Chessnut** [comment]
Can you list your addons too?

**Comment by zambony** [comment]
Atmos
Beta Citizen Models
My forcefield addon
Combine Sniper
Combine APC
HL2 Beta Weapons
LuaPad
Metropolice Pack
Male/Female Conscripts
Physgun Buildmode
Serverguard
SubMaterial Tool
Vortigaunt Beam SWEP

That's all of them.
