### ISSUE TITLE
[NutScript 1.1] C flag

### ISSUE THREAD

**Issue by art-gur** [Chessnut/NutScript#445]
In the code there with the C flag, which is responsible for spawning _vehicles_, but in the issuance of this flag, the _vehicles_ still can not put.

**Comment by Chessnut** [comment]
The C flag is for vehicles

**Comment by art-gur** [comment]
@Chessnut, I meant them.

**Comment by Chessnut** [comment]
https://dl.dropboxusercontent.com/u/24983881/ShareX/2015/04/rp_c18_v1%202015-4-5%2021-38-44.webm

Can't replicate.

**Comment by art-gur** [comment]
Thanks, now it works.
