### ISSUE TITLE
[1.1] Suggestion: PlyMdl support

### ISSUE THREAD

**Issue by TheOnlyDusk** [Chessnut/NutScript#447]
I've encountered a few playermodels/models that works well in 1.0, but doesn't in 1.1
(T-pose, sp anims and other stuff)

So, I was curious if you could try and allow for a wider support of animations for models? I dunno if this is the issue, but I just think it could be nice to have.

**Comment by Chessnut** [comment]
There's already support for vortigaunt animations, regular player models, metro-police, citizen, and Combine soldiers. What else do you need?
