### ISSUE TITLE
[1.1] Scoreboard Recognizion v2

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#449]
The current scoreboard recognition is a bit - what to call it.. bothersome?

Suggestion of how it could be improved:
- You don't see the people's icons unless you've recon'ed them, because this can currently be metagamed in terms of you would see if someone has a rebel suit equipped, as it uses their current model, and everyone can see them. Not known players could be a icon question mark for example.
- In exchange you see their full name (nice for knowing who you speak to in OOC and who that is on Steam), though not their description unless recon'ed.

Why to add this:
- It's easier for admins and everyone interacting with people from OOC to find the Steam profile of the people who are talking. Because let's say "John" says to add him on Steam, in observer I won't see their OOC name, and the scoreboard hints only tell me which Steamprofile this guy is.
- The icons can be more metagamed then the names itself.

**Comment by Chessnut** [comment]
How about this:
![meh](http://i.imgur.com/WxJlNvu.png)
