### ISSUE TITLE
[1.1] Ragdoll Improvements

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#450]
Few improvements on the ragdoll system would be great:
- If a character falls unconscious, it could say in a notice when looking at their name, just like "Is Tied", though like "Is Unconscious" or similar sentence. So you know if this character has just fallen over, knocked over or "Deceased".
- Regarding deceased, would be nice if they got that once they die, and that their ragdoll doesn't disappear almost instantly/when they spawn as it's now. Rather a config where you can config how long you want dead ragdolls to stay, before they fade away. As usually you roleplay with the bodies maybe a few minutes before you leave them/incenerate (HL2RP e.g.).

**Comment by Chessnut** [comment]
The death ragdoll is the Source one

**Comment by blt950** [comment]
Remove the source one and create a dummy one by Nutscript or similar?
Clockwork can do this somehow, I believe this can be done here as well :+1: 

Some useful code that shows you it's possible. Probably more behind this, but I just mean to give you hints where to start.

### Line 2569

https://github.com/CloudSixteen/Clockwork/blob/6674827bdc20302576e1320fe893fba148c26114/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/server/sv_player.lua

### Line 3072

https://github.com/CloudSixteen/Clockwork/blob/6674827bdc20302576e1320fe893fba148c26114/Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua

**Comment by Chessnut** [comment]
I know it is doable but it does not seem like there is really a point to it.

**Comment by blt950** [comment]
I get that this might not be the most prioritized one. It's more of a roleplay enchantment, so you can still interact with the dead players, since they disappear like 5 seconds after death.

What I mostly ask for except of that is to get the "Is unconscious" status on their ragdolls when they've been hit unconcious by stunstick or similar.
