### ISSUE TITLE
/spawnadd doesnt work

### ISSUE THREAD

**Issue by Aberidius** [Chessnut/NutScript#453]
I type the command /spawnadd and it seem to work fine, no errors or so but when someone go on their character on that faction, it puts them in the originial map spawn.

**Comment by Chessnut** [comment]
Does it give the message that the spawn as added?

**Comment by Aberidius** [comment]
Yes it does

**Comment by Chessnut** [comment]
You checked the _server_ console for errors right?

**Comment by Aberidius** [comment]
Yes, no errors are displayed

**Comment by Chessnut** [comment]
Did you try updating

**Comment by Aberidius** [comment]
Updating what? I tried adding another spawn, same thing, but it doesnt spawn them at the point.

**Comment by Chessnut** [comment]
Updating the framework

**Comment by Aberidius** [comment]
How would i update the framework? I got the latest version of nutscript

**Comment by Chessnut** [comment]
You download it and replace the server files with the downloaded files.

**Comment by Aberidius** [comment]
mind linking me to it, since i think i am miss understanding you. I already have the latest.

**Comment by Chessnut** [comment]
Redownload the framework
