### ISSUE TITLE
[1.1]Doors not opening for nexus.

### ISSUE THREAD

**Issue by gmanc2** [Chessnut/NutScript#455]
The nexus doors refuse to open for combine and/or any other class  a screen shot of the door can be found below.

http://cloud-2.steamusercontent.com/ugc/530638916533436542/FC7FC161C0D0C26715D338BF71813857D0CCDD99/

**Comment by Chessnut** [comment]
This issue belongs to the HL2RP Git issues, not the NutScript one.
