### ISSUE TITLE
Armor add and take off on equip

### ISSUE THREAD

**Issue by Aberidius** [Chessnut/NutScript#461]
So i've done the following

ITEM:AddQuery("add 8 armor on wear") It works fine but when i take it off and equip it again, it just stacks it. How can i make so that it removes the same amount of armor on unequip?

**Comment by Chessnut** [comment]
`remove 8 armor on takeoff`?

**Comment by Aberidius** [comment]
Would i put that in a seperate ITEM:AddQuery or do i make a function out of this? i already tried with making a function but it still keeps adding more and more armor.
