### ISSUE TITLE
1.1 Suggestion: Clothing base

### ISSUE THREAD

**Issue by TheOnlyDusk** [Chessnut/NutScript#463]
I'd like to suggest a clothing base like in NS 1.0 that allows one to create equipable 'uniforms,' that can be equipped and unequipped through the inventory.

**Comment by Chessnut** [comment]
PAC Outfit

**Comment by Rubberbandits** [comment]
what? that is a thing.

what the hell are you even talking about

like its already in why did you make a fucking thing man

**Comment by Chessnut** [comment]
What? Look in the item base folder

**Comment by Rubberbandits** [comment]
i'm telling him it already exists why would he suggest it

im so confused

**Comment by TheOnlyDusk** [comment]
It was one way to figure out how the clothing works in 1.1
\o/

**Comment by Rubberbandits** [comment]
i made a clothing base like when 1.1 first came out

a proper one.

**Comment by Rubberbandits** [comment]
and i put it up on the repository so

**Comment by TheOnlyDusk** [comment]
https://github.com/Chessnut/NutScript/tree/1.1/gamemode/items/base

I don't see a 'clothing' base here tho.

**Comment by Chessnut** [comment]
Didn't I JUST say pacoutfit earlier?

**Comment by TheOnlyDusk** [comment]
I know chessnut, but it was mainly a 'play' at the thing Rubberbandits said.

Lemme quote him/her
"i made a clothing base like when 1.1 first came out

a proper one."
