### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Aberidius** [Chessnut/NutScript#466]
There's a problem with the mysql. The database is completely fine although, people get stuck on loadingscreen and it just shows errors in console

Query Error: UPDATE characters SET inv = '', chardata = '~\"attrib_acrv\":n4.315;\"clip1v\":n-1;\"idv\":n1112362532;\"attrib_spdv\":n5.1;\"attrib_endv\":n6.2;\"ammov\":{}\"flagsv\":\"petcnrv\"\"attrib_strv\":n5;', charname = 'Albin Stroström', faction = 4, money = 0, model = 'models/half-dead/civilians/male_04.mdl', gender = 'male', description = '6\'4|Bald|Light Skin|Scottish Dialect|Thick Jacket|Ring Finger Cut Off|Bandage Over Wound|' WHERE steamid = 76561198019375670 AND id = 1 AND rpschema = 'finalhourrp'

MySQL server has gone away

**Comment by Chessnut** [comment]
Try using tmysql instead

**Comment by Aberidius** [comment]
I just did, same issue.

**Comment by Aberidius** [comment]
Example of the error i get in console:

Query Error: UPDATE players SET plydata = '', whitelists = 'military,' WHERE steamid = 76561198019375670 AND rpschema = 'finalhourrp'

**Comment by Chessnut** [comment]
Did you import the SQL tables?

**Comment by Aberidius** [comment]
Yes i did

**Comment by Chessnut** [comment]
tmysql should not give the server has gone away error unless it's a problem with your MySQL server. Also I'd advise updating to 1.1 if you can.

**Comment by franzhoog** [comment]
The same thing is happening to me on 1.0. How would we go about fixing this? I'd ask you on Steam, but you deleted me as you tend to do periodically.

**Comment by Chessnut** [comment]
The database handler for 1.1 and 1.0 are pretty much identical so I don't
know.

**Comment by franzhoog** [comment]
Why would both of our databases break simultaneously? Is this related to a recent game update, or what?

**Comment by Chessnut** [comment]
There hasn't been a recent game update anyways and the server has gone away
usually happens when you use mysqloo and the DB has been idle because
nothing has happened (like having no players online) so it disconnects.

**Comment by franzhoog** [comment]
How would I go about wiping my database, then? I'll try that and see if that fixes it.

**Comment by Chessnut** [comment]
nut_recreatedb I think, or you can just use phpMyAdmin if you have that, or
use the mysql command line directly.

**Comment by zack-w** [comment]
You don't need to wipe your database. Just have a timer to poll the database once every few minutes with a basic query like...

```
SELECT 1+1
```

Or alternatively overwrite the database connection timeout limit (although this requires SUPER) privileges. Wiping the database will do literally nothing.

**Comment by Chessnut** [comment]
By the way Hoog, 1.1 does this if you don't mind upgrading ;)

**Comment by franzhoog** [comment]
I'm told by a friend that this is pretty easy to fix.

1.1 is a mess as it stands right now - I don't want to deal with that - and I'd lose a ton of functionality if I even attempted to upgrade.

**Comment by Chessnut** [comment]
1.1 has more functionality and stability than 1.0 if anything

**Comment by zack-w** [comment]
@Chessnut the migration can be a pain due to major functional changes between the two versions

**Comment by franzhoog** [comment]
Sure, but the schema I'm working on is a year's worth of work. I'm not going to lose all that just for greater stability.

@Chessnut 

also, thanks zack for the attempts to help, but that's gibberish to me - i'll have my guy help me out

**Comment by Chessnut** [comment]
Check if this update fixes it.

**Comment by franzhoog** [comment]
I was able to fix the issue by wiping my database. Seems that it breaks down periodically.

**Comment by Chessnut** [comment]
The issue has nothing to do with your database tables.
