### ISSUE TITLE
Cant create Character Issue.

### ISSUE THREAD

**Issue by 7beat** [Chessnut/NutScript#467]
Hello!
I've recenty updated NS to 1.1 and 1.0 was working fine but after istallation newer version i cant create character on my serv. I have this in my console. 

[Johnny Sins|2|STEAM_0:0:22000040] Lua Error:
Couldn't include file 'hl2rp\schema\sh_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 32))

[Johnny Sins|2|STEAM_0:0:22000040] Lua Error:

[ERROR] gamemodes/hl2rp/plugins/radio/sh_plugin.lua:73: attempt to call field 'Register' (a nil value)
1. unknown - gamemodes/hl2rp/plugins/radio/sh_plugin.lua:73
   1. include - [C]:-1
   2. include - gamemodes/nutscript/gamemode/core/sh_util.lua:32
      1. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
      2. loadFromDir - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:175
      3. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:166
      4. unknown - gamemodes/nutscript/gamemode/shared.lua:65

**Comment by Chessnut** [comment]
Don't use 1.0 schemas with NS1.1?

**Comment by 7beat** [comment]
I've downloaded ur hl2rp. At same moment so could you tell which is up to date?

**Comment by FlammableAce** [comment]
https://github.com/Chessnut/hl2rp/tree/1.1 

Up to date 1.1 version

**Comment by 7beat** [comment]
Thanks chess for help and flamable for link :)
