### ISSUE TITLE
[1.1] Wearing an item with pac glitches animations in vehicles

### ISSUE THREAD

**Issue by FlammableAce** [Chessnut/NutScript#468]
Once a PAC item has been equiped the animations glitch out in a vehicle, the player is stuck in a constant loop of standing up and sitting down in the vehicle. 

Things to note

*Removing the PAC item doesn't fix the issue. once it has been equiped the only way to fix is rejoin.
*There are no lua errors

**Comment by Chessnut** [comment]
Does this happen before the player has a PAC outfit equipped?

**Comment by FlammableAce** [comment]
Nope, only afterwards.

**Comment by Chessnut** [comment]
What does your PAC do?

**Comment by FlammableAce** [comment]
I currently only have the default pac outfits included in ModernRP schema. Maybe it's just a ModernRP schema bug ? 

They are head items (helmet/hat) that seem to cause the bug.

**Comment by Chessnut** [comment]
Note to self: May be a result of bone manipulation
