### ISSUE TITLE
[1.1] Business menu line in sh_schema no longer controls whether business can be used

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#469]
function SCHEMA:CanPlayerUseBusiness(client, uniqueID)
    return false
end

Stopped working sometime in one of the recent updates.

**Comment by Aberidius** [comment]
there is the following function in the config file:

-- If any player can see the business menu.
nut.config.businessEnabled = true

**Comment by CaptJack92a** [comment]
Which config file? There are several and none contain this that I can see.

**Comment by Chessnut** [comment]
This may be because some plugin you had or another section of your schema already returned something earlier before.

**Comment by CaptJack92a** [comment]
You were half right. There was a single conflicting command hiding among the config script. Thanks.
