### ISSUE TITLE
[1.1] Encountered this error

### ISSUE THREAD

**Issue by TheOnlyDusk** [Chessnut/NutScript#475]
[ERROR] gamemodes/nutscript/gamemode/core/hooks/sh_hooks.lua:203: attempt to index a nil value
1. unknown - gamemodes/nutscript/gamemode/core/hooks/sh_hooks.lua:203

I am unsure if we're the only one having this issue, so I wanted to post it here. It's better for it to be noticed and 'fixed' than not. :)

(This error kept popping up each time I fired a weapon, crouched or jumped etc.)

**Comment by Chessnut** [comment]
What's your playermodel set to?

**Comment by TheOnlyDusk** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=341801125&searchtext=generic+bad+guys

**Comment by Chessnut** [comment]
Did you set the model class to something that isn't available?

**Comment by TheOnlyDusk** [comment]
The thing is, we are attempting to fix its animations because these models worked fine with proper idle anims and such in 1.0 but uses SP idle pose instead in 1.1
Sorry, lemme answer your question now.

We didn't set any model classes, we just changed into the playermodel from that package and experienced these errors and that they for some reason use different anims than in 1.0 which kinda sucks.

**Comment by Chessnut** [comment]
Are you sure you didn't use `nut.anim.setModelClass` for your playermodels anywhere?

**Comment by TheOnlyDusk** [comment]
nut.anim.setModelClass("models/mfc_new.mdl", player)
gamemodes/dow/schema/sh_schema.lua

**Comment by Chessnut** [comment]
You didn't put player in quotes so you ended up defining it wrong. So you
ended up making this error yourself.

**Comment by Chessnut** [comment]
I also updated 1.1 to give an error for invalid animation classes now so you should update to prevent mistakes like this again.
