### ISSUE TITLE
[1.1 Suggestion] BodyGroup selection

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#478]
It would be really awesome if you could implement an bodygroup selection on character creation. Where you can scroll through bodygroups and skins to select them to your character. (If you want to expand it even more,  maybe submaterials as well)

Only available on models which has bodygroups and/or skins of course. Sometimes there are skins/bodygroups you don't want players to choose, so a blacklist could maybe be an idea to add as well.

I would be extremely happy if we could get this in Nutscript! :smiley: :smile:

**Comment by axiDl** [comment]
I agree with this idea.
Would be an interesting addition to the gamemode and other servers.

**Comment by Chessnut** [comment]
Make a plugin that adds a new character variable? Search for
nut.char.registerVar in the code.

**Comment by blt950** [comment]
I understand this could be made as an plugin, the purpose of this suggestion was to have this as a default part of Nutscript, as it's none (to my knowledge) frameworks which have this function by default.

**Comment by Chessnut** [comment]
Plugins packaged with the framework are only for things that are necessary. The lack of bodygroups isn't going to harm roleplay.

**Comment by Rubberbandits** [comment]
_cough_ player:SetBodyGroup _cough_

**Comment by Chessnut** [comment]
Look at how the model selection is used with `nut.char.registerVar` and just change it from setting a model to setting bodygroups using that function.

**Comment by blt950** [comment]
@Rubberbandits : I know how to set a BodyGroup, again: I'm suggesting it should be a default part of Nutscript to choose bodygroups when creating characters.

Though as Chessnut doesn't feel it's needed as a standard function, then it's ok :)

**Comment by NDKilla** [comment]
Personally I feel as few things like this should be default. It could be a plugin and included on the official NSPlugin directory, but not installed in the framework by default.
