### ISSUE TITLE
[1.1] Vehicle Inventory Error

### ISSUE THREAD

**Issue by FlammableAce** [Chessnut/NutScript#481]
Looking at your inventory after buying a vehicle gives this error, you can still use the vehicle but the inventory is all messed up and is in the top left corner of the screen.

Console error

<pre>
 [ERROR] gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105: bad argument #2 to 'L' (no value)
  1. L - [C]:-1
   2. setInventory - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105
    3. callback - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:401
     4. DoClick - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:171
      5. unknown - lua/vgui/dlabel.lua:218 </pre>

The vehicle lua file
<pre>
ITEM.uniqueID = "F458"
ITEM.name = "Ferrari 458"
ITEM.model = "models/lonewolfie/ferrari_458.mdl"
ITEM.desc = "A brand new vehicle"
ITEM.width = 1
ITEM.height = 1
ITEM.physDesc = "Simple desc"
ITEM.maxGas = 1000
ITEM.cost = 8000
ITEM.vehicleData = {
    type = TYPE_GENERIC,
    model = ITEM.model,
    script = "scripts/vehicles/LWCars/ferrari_458.txt",
    name = ITEM.name,
    physDesc = ITEM.physDesc,
    maxGas = ITEM.maxGas,
    cost = ITEM.cost,
}
</pre>

The top part of sh_vehicles.lua

<pre>
TYPE_GENERIC = 1
TYPE_SCAR = 0

ITEM.name = "Car"
ITEM.model = "models/buggy.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.maxGas = 1000
ITEM.desc = "Simple Desc one"
ITEM.cost = 1200
ITEM.category = "Vehicles"
ITEM.physDesc = "An Object that has 4 wheels and rolls forward."
ITEM.noDrop = true
ITEM.vehicleData = {
    type = TYPE_GENERIC,
    model = "models/buggy.mdl",
    script = "scripts/vehicles/jeep_test.txt",
    name = ITEM.name,
    physDesc = ITEM.physDesc,
    maxGas = ITEM.maxGas,
    cost = ITEM.cost,
}
</pre>

I have tried the following trying to get it to work -

I have tried changing Price to Cost
Added ITEM.cost to both lua files
Added ITEM.phsyDesc to the actual vehicle file
Added ITEM.desc to the actual vehicle file
Added ITEM.category
Added Unique ID

Still nothing :(

**Comment by Chessnut** [comment]
Well it sounds like something isn't returning a valid description. The line of the error is:
`icon:SetToolTip("Item #"..item.id.."\n"..L("itemInfo", L(item.name), L(item:getDesc())))`

item.name is already set so you will need to check if item:getDesc() returns a string.

**Comment by FlammableAce** [comment]
No idea what it is, if you have access to ModernRP github you might want to remove the broken vehicle plugin until a viable solution comes around.

**Comment by snwdaaa** [comment]
Same Problem

**Comment by FlammableAce** [comment]
Any updates or progress with this ? It's a pretty game breaking bug for RP servers. 

Also a vehivle system similar to this would be awesome - https://www.youtube.com/watch?v=7DkR3rQWVJU

Also with the current vehicle plugin is there a way to save changes to cars (colour, body groups, etc)

**Comment by Rubberbandits** [comment]
This is a ModernRP issue, not a Nutscript issue. Please keep ModernRP issues on the repository for ModernRP.

**Comment by FlammableAce** [comment]
Well it would be a bit pointless posting to the modern rp GitHub since rebel is no longer maintaining it because he had to go in the army, but chessnut has the ability to update the ModernRp repo and I don't think he reads the issues there.
