### ISSUE TITLE
NS 1.1 F1 Menu Issue

### ISSUE THREAD

**Issue by vingard** [Chessnut/NutScript#482]
I get this error when I open F1 menu:

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:47: attempt to perform arithmetic on a nil value
1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:47
   1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
      1. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      2. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

**Comment by NDKilla** [comment]
Did you edit that file or any files in your ns/core folder?
Are you running a schema and not trying to use NS as the base?
I'm running up-to-date NS 1.1 and HL2RP 1.1 and I haven't had this error.
