### ISSUE TITLE
1.1 Suggestion

### ISSUE THREAD

**Issue by snwdaaa** [Chessnut/NutScript#486]
Class Delay, like OOC delay

**Comment by Chessnut** [comment]
Like a chat class delay?

**Comment by NDKilla** [comment]
class chat?
Delay between switching characters?
I noticed if a player onCanBe 2 different classes, they can switch classes back and forth almost instantaneously

**Comment by snwdaaa** [comment]
No, The delay of choose class (Like Civil Protection Elite,Civil Protection Recruit )

**Comment by snwdaaa** [comment]
Sorry. I am not good at English

**Comment by kkj4818** [comment]
Another Suggestion, Limit on the number of persons for classses

**Comment by Chessnut** [comment]
Like `CLASS.limit`?

**Comment by kkj4818** [comment]
Yes. Like 'Class name 0/10'

**Comment by Chessnut** [comment]
Yeah it already exists

**Comment by snwdaaa** [comment]
I found it. Thank you
