### ISSUE TITLE
Zoomed-In Playermodel on Character Menu

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#489]
With the new update of Garry's Mod (6/1/15), I have noticed that on the character selection menu/main schema menu the playermodels are zoomed in. I have tried reinstalling, using it from a fresh server, etc. and this issue still persists.

Here's what it looks like:

![characterchoose](https://cloud.githubusercontent.com/assets/6519678/7925927/223291ac-0888-11e5-97f4-1b80168d0690.png)

**Comment by snwdaaa** [comment]
Same problem

**Comment by blt950** [comment]
Same problem here.

**Comment by Chessnut** [comment]
This is an issue with the GMod update.

**Comment by ghost** [comment]
Is there any way to fix it on NutScript's side?
