### ISSUE TITLE
[1.1] Tying Suggestion

### ISSUE THREAD

**Issue by stnngfm** [Chessnut/NutScript#490]
Player can see and take items from other players inventory when other player restricted by handcuff

**Comment by NDKilla** [comment]
Should be made as a plugin. I was working on it but haven't been on my computer lately.

**Comment by maxyii** [comment]
I agree, this is something that clockwork has and it's very good.

**Comment by blt950** [comment]
Agree, this should be at least included in the default Nutscript as an plugin.

**Comment by Rubberbandits** [comment]
chessnut just added it
