### ISSUE TITLE
Schema NOT Loading

### ISSUE THREAD

**Issue by BradIsABadName** [Chessnut/NutScript#494]
Unknown title and description.
Only option is leave, this is for the sample schema.

**Comment by Chessnut** [comment]
This usually means you used a 1.0 schema for NS1.1. Also, there isn't a
sample schema for 1.1

**Comment by BradIsABadName** [comment]
This explains the situation.
Could you possibly create a sample-schema for your 1.1 ?

I also had a 1.0 schema, how could I update to 1.1?

**Comment by Chessnut** [comment]
https://www.youtube.com/watch?v=bXtrdZoGxoI
https://docs.google.com/document/d/1pNbu4byKFmsaYca4T9G-yM_my6WGf4kNfL4hbyyyZH4/edit
