### ISSUE TITLE
nutModelPanel Rotation

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#496]
I'm a bit unsure if it's the models or something in the script itself which causes this. All my BMS models are wrongly rotated in the nutModelPanel, though correctly in F1 menu?

Tried to rotate them manually in script by model paths, but then F1 menu gets wrong because it's originally correct, heh.. The animation is also not quite there, it's a T-pose (only in char selection as well). Though not sure how to fix that, as they work fine in game and I've added nut.anim.setClassModel() on all those models.

![2015-06-09_00001](https://cloud.githubusercontent.com/assets/2505044/8066293/252d724a-0ee7-11e5-84ec-1e8ef616a219.jpg)
![2015-06-09_00002](https://cloud.githubusercontent.com/assets/2505044/8066294/2791e6d8-0ee7-11e5-8744-95e2278d6ae1.jpg)

**Comment by Chessnut** [comment]
What act is used for the model's idle stance?

**Comment by blt950** [comment]
How do I check that? This is at least start of GetSequenceList() of this model.

0   =   ragdoll
1   =   idle
2   =   idle_subtle
3   =   idle_angry
4   =   LineIdle01
5   =   LineIdle02
6   =   LineIdle03
7   =   LineIdle04
8   =   Crouch_idleD
9   =   layer_crouch_walk_no_weapon
10  =   layer_crouch_run_no_weapon

**Comment by Chessnut** [comment]
It's weird since they use the same exact thing.

**Comment by blt950** [comment]
I know right, that's what confuses me as well. It obviously works in F1 menu?

The most weird part is how it's wrongly rotated in character menu, but in F1 menu it's correct, meaning I can't hard-code a fixed rotate in the modelPanel as then it appears correct in character selection but not in F1 ( i tried ). But I suppose there is some difference between character selection and F1 modelPanel, as they appear differently?

**Comment by Chessnut** [comment]
Your server has these models installed right?

**Comment by dhkatz** [comment]
I can confirm, models on my server different from this are having the same issue.

**Comment by Chessnut** [comment]
That doesn't answer my question if you're having this issue

**Comment by smt923** [comment]
I have the same issue randomly for some of my models (different to these), and yeah they're fully installed on the server

**Comment by dhkatz** [comment]
Ok, yes the server does have the models installed.

**Comment by blt950** [comment]
Yes the models are installed both server and clientside.

Been on vacations, hence the late reply.

**Comment by Chessnut** [comment]
Well I won't be back from vacation so I can't test anything for another 2
weeks so just deal with it for now.

**Comment by blt950** [comment]
We can wait until then :)

**Comment by blt950** [comment]
Any progress on this issue or #562 ?

**Comment by blt950** [comment]
Can't seem to recreate the issue anymore, I believe it's solved.
