### ISSUE TITLE
Nutscript Moderation

### ISSUE THREAD

**Issue by BradIsABadName** [Chessnut/NutScript#497]
Due to the wiki having an update, the moderation part of nutscript isn't functioning and nutscript has many commands that cannot be accessed.

**Comment by Chessnut** [comment]
What does the wiki have to do with moderation?

**Comment by BradIsABadName** [comment]
Normally the wiki had all the commands for the moderation on the previous one.
I don't see any form of moderation like it did before. There is however commands which cannot be accessed due to this.

**Comment by Chessnut** [comment]
The wiki doesn't affect which commands are available in-game and the wiki never listed the commands. It only contains coding documentation.

**Comment by BradIsABadName** [comment]
I may of worded this incorrectly. What happened to the moderation part of NS?

**Comment by Chessnut** [comment]
It is removed from NS1.1 in favor of using an actual admin mod.

**Comment by BradIsABadName** [comment]
Alright, thank-you.
Just wanted to clarify. 
Because I thought that the moderation or admin mod idea was good on the previous version.

**Comment by NDKilla** [comment]
I thought it was too but it's whatever

NutScript do you know of an easy way to make !commands like ulx !god not show up in local chat?
I can use the console for commands but it's not as convenient for me
