### ISSUE TITLE
Setting: Doors disabled & hidden by default

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#499]
There should be a setting which makes all doors disabled and hidden by default. This way you don't need to go all over the map to disable and hide all doors manually, as you also need to sometimes to this on elevators and such.

**Comment by DefenderVex** [comment]
A feature like this would be really useful.

**Comment by Rubberbandits** [comment]
Use a loop.

for k, v in pairs( ents.FindByClass( "door_*" ) ) do
    v:setNetVar("disabled", true)
end

done, and if your doors have entdata in hammer, you can use:

http://wiki.garrysmod.com/page/ents/FindByName

**Comment by blt950** [comment]
I'm aware of how to do this Rubberbandits, I'm though suggesting it should be a setting (or default setting).

**Comment by Rubberbandits** [comment]
Pull request then brah

**Comment by blt950** [comment]
If I had the time to do it, I would do it. I'm suggesting because I don't. We're not here to discuss how I should do it or that I should pull request it. I'm here to give my suggestion so Chessnut or who ever wants can pull it to the framework.
