### ISSUE TITLE
Does armor have a base?

### ISSUE THREAD

**Issue by maxyii** [Chessnut/NutScript#502]
I've been trying to find out how to add armor function onto clothing for around a week now and I just don't get it. Does armor have a base like pac and weapons do? If so where can I get this?

**Comment by maxyii** [comment]
For the love of god a Christ all mighty, why does this code not work!

ITEM.name = "Armor test"
ITEM.desc = "A test"
ITEM.model = "models/items/healthkit.mdl"
ITEM.price = 60
ITEM.functions.Use = {
    sound = "items/medshot4.wav",
    onRun = function(item)
        client:SetArmor(50)
    end
}

**Comment by Chessnut** [comment]
Where's client defined?

**Comment by maxyii** [comment]
? Sorry I don't understand

**Comment by maxyii** [comment]
What code would I need to define client, and would It need to be in the function or out of it?

**Comment by Chessnut** [comment]
You can't just use random variables from nowhere. If you checked your
server for errors, you would've seen Lua errors, so next time check the
server console too before saying something doesn't work. You need to change
client to item.player

**Comment by maxyii** [comment]
Alright thank you, sorry for complaining im just new to lua coding and stuff.

**Comment by maxyii** [comment]
Alright thank you, just one more question, how would you apply the armor feature on PACclothing, I've now got it working on items which I'm thankful for, however when I equip clothing from now on it removes the script, is there anyway to overcome this?

**Comment by Chessnut** [comment]
Use ITEM:hook()

**Comment by maxyii** [comment]
Is it just ITEM.hook() and then the code inside the brackets
e.g.
ITEM.hook(
sound = "items/medshot4.wav",
onRun = function(item)
client:SetArmor(50)
)

?

**Comment by Chessnut** [comment]
https://github.com/Chessnut/NutScript/wiki/Item
