### ISSUE TITLE
Custom MP3's for voices

### ISSUE THREAD

**Issue by gmanc2** [Chessnut/NutScript#503]
Yeah, this should be added.

**Comment by Chessnut** [comment]
You can add it yourself? Look at how the other voices are added.

**Comment by gmanc2** [comment]
Yes there added from the hl2_sound_misc_dir.vpk I can't call them from anything else from what I've seen.

**Comment by Chessnut** [comment]
What?

**Comment by gmanc2** [comment]
The sound directory you're using is the C:\Program Files (x86)\Steam\SteamApps\common\Half-Life 2\hl2\hl2_sound_misc_dir.vpk correct?

... How are you calling the sound files?

**Comment by Chessnut** [comment]
What do you mean by calling the sound files?

**Comment by gmanc2** [comment]
nut.voice.Register("combine", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")

This is under the marked as the function nut.voice.Register
Which I assume is using the hl2_sound_misc_dir.vpk to call the voices. correct?

**Comment by Chessnut** [comment]
Yes, it's uses a HL2 sound file.

**Comment by gmanc2** [comment]
So, how would I add a costom sound?

**Comment by Chessnut** [comment]
Use your own sound path instead of a HL2 one?

**Comment by gmanc2** [comment]
Where is the sound path defined? Its not defined in that file?

**Comment by Chessnut** [comment]
Where you put the sound file.

**Comment by Chessnut** [comment]
`nut.voice.Register("combine", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")`

Here, the sound like DOES NOT have to be from HL2. It can be from anywhere.

So you can replace "npc/metropolice/vo/stabilizationjurisdiction.wav" with "myserver/coolsound.mp3" if you wanted.

**Comment by gmanc2** [comment]
hl2rp\gamemode\schema\voices\death-Roman_K-1190383229.mp3

That is where I put my custom mp3.

**Comment by Chessnut** [comment]
It needs to be under the sound folder just like every other sound file.

**Comment by gmanc2** [comment]
Thank you very much... Also if it is not a huge hassle could you add me on steam I have few more questions and hope you can awnser... Much appricated.
