### ISSUE TITLE
[Suggestion] Weapons on back

### ISSUE THREAD

**Issue by maxyii** [Chessnut/NutScript#504]
If there is someone with a plugin they can send to me with a feature where all weapons equipped appear on the players back, that would be great.

**Comment by Trixas** [comment]
I'm pretty sure modernRP do have it

**Comment by Chessnut** [comment]
Turns out Black Tea added a HOLSTER_DRAWINFO table that you use like:
`HOLSTER_DRAWINFO["weapon_pistol"] = {bone = "bone here", pos = Vector(1, 2, 3), ang = Angle(1, 2, 3)`

So one just needs to set this up for the desired weapon.

**Comment by Chessnut** [comment]
Closed. Duplicate of #353.
