### ISSUE TITLE
Invalid method getChar()

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#507]
Maybe I'm not calling it correctly, because I've tried both a networking the call from clientside to serverside, but I was getting a WriteString error.

```
    statpanelplus = vgui.Create("DButton", statpanel)
    statpanelplus:SetText("Add Strength")
    statpanelplus:Center()
    statpanelplus:SetSize(300, 300)
    statpanelplus.DoClick = function(character)
        character:setData("strength", character:getData("strength") + 1)
    end
```

I'm using it inside of a netstream hook and calling it Serverside. Anyone know how to get this working?

[ERROR] gamemodes/nstest/schema/hooks/cl_hooks.lua:32: attempt to call method 'getData' (a nil value)

Even using netstream, for some reason client from clientside returns nil, and using LocalPlayer() won't work because that's userdata and netstream needs String

EDIT: It's because I'm using the wrong arguments, it's supposed to just be the name of the Netstream hook, not the activator included.

**Comment by Chessnut** [comment]
You do know how function arguments work right? You can't just name certain
arguments certain things and expect it to be that. In this case character
refers to the panel that is being clicked. DoClick does not pass a
character object.

**Comment by Rubberbandits** [comment]
It was just a test, but my real problem was with Netstream. It's closed anyway.
