### ISSUE TITLE
getMoney() returning a boolean

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#508]
I'm not entirely sure if it actually is or not, but using a check to see if getMoney is greater than or equal to another number returns as this error:

[ERROR] lua/entities/slotmachine/init.lua:32: attempt to compare number with boolean

**Comment by Chessnut** [comment]
What's the slot machine entity? Also can you show me the line.

**Comment by Rubberbandits** [comment]
```
if( !tonumber(client:getChar():getMoney()) >= ArgToUse  ) then client:notifyLocalized( "You can not afford to bet $" .. tostring( ArgToUse ) .. "!" ) return end
```

ArgToUse prints 100, but so does getMoney(). I've tried it with ToNumber and without ToNumber

**Comment by Rubberbandits** [comment]
I now happen to get [ERROR] gamemodes/nstest/schema/hooks/sh_hooks.lua:2: attempt to perform arithmetic on a nil value

It's just some math, the line doesn't matter. What really matters is the AdjustCreationData hook im using serverside.

function SCHEMA:AdjustCreationData(client, character)
    client:getChar():setData("strength", 5)
    client:getChar():setData("perception", 5)
    client:getChar():setData("endurance", 5)
    client:getChar():setData("charisma", 5)
    client:getChar():setData("intelligence", 5)
    client:getChar():setData("agility", 5)
    client:getChar():setData("luck", 5)
    client:getChar():setData("energywep", 10)
    client:getChar():setData("explosive", 10)
    client:getChar():setData("guns", 10)
    client:getChar():setData("lockpick", 10)
    client:getChar():setData("medicine", 10)
    client:getChar():setData("meleewep", 10)
    client:getChar():setData("repair", 10)
    client:getChar():setData("science", 10)
    client:getChar():setData("sneak", 10)
    client:getChar():setData("speech", 10)
    client:getChar():setData("survival", 10)
    client:getChar():setData("unarmed", 10)
    client:getChar():setData("totalTagged", 0)
    client:getChar():setData("playerStatsChosen", 0)
end

apparently, that's not setting any data. Is there a limit to how many entries I can make?

**Comment by Chessnut** [comment]
The player doesn't have a character object yet which is why you use the
passed character object (see the 2nd argument named character)

As for the money thing I need to see more of the context to understand why
it isn't working.

**Comment by Rubberbandits** [comment]
I've tried both the Character object and using client:getChar()

Here you go:

if( not tonumber( args[ 1 ] ) or client.DoingSlots ) then return end
    local ArgToUse = tonumber( args[ 1 ] )
    print(ArgToUse)
    print(client:getChar():getMoney())
    if( !tostring(client:getChar():getMoney()) >= ArgToUse  ) then client:notifyLocalized( "You can not afford to bet $" .. tostring( ArgToUse ) .. "!" ) return end

```
if( GetConVarNumber( "slotmachine_maxbet" ) < GetConVarNumber( "slotmachine_minbet" ) ) then
    ArgToUse = GetConVarNumber( "slotmachine_minbet" )
    client:notifyLocalized( "Your bet has been automatically lowered to $" .. ArgToUse .. " due to the minimum being higher than the maximum. Contact an admin" )
elseif( ArgToUse > GetConVarNumber( "slotmachine_maxbet" ) ) then 
    ArgToUse = GetConVarNumber( "slotmachine_maxbet" ) 
    client:notifyLocalized( "Your cannot bet more than $" .. ArgToUse .. " due to the betting limit." )
    return
elseif( ArgToUse < GetConVarNumber( "slotmachine_minbet" ) ) then 
    ArgToUse = GetConVarNumber( "slotmachine_minbet" )
    client:notifyLocalized( "You cannot bet less than $" .. ArgToUse .. " due to the betting limit." )
    return  
end
```

I've added the two prints, and when they print, they both return a number.

**Comment by Chessnut** [comment]
I don't know where you got the arguments from but the arguments are client,
data, newData. You would need to use newData.data = {} newData.data["foo"]
= "bar" since it is creation data. The character object has not been made.

**Comment by Chessnut** [comment]
Also: !tostring(client:getChar():getMoney()) >= ArgToUse

Why did you use tostring?

**Comment by Rubberbandits** [comment]
Oh, that's me testing if I can get it to work. I've tried tostring, tonumber, and just leaving it alone.

I get the same error everytime.

**Comment by Chessnut** [comment]
Pastebin the whole file and link it here.

**Comment by Rubberbandits** [comment]
http://hastebin.com/ehanuxagez.coffee ArgToUse is being networked from cl_init, and it's an input box that only contains numbers.

**Comment by Chessnut** [comment]
Looks fine to me. What's the line for the error because it doesn't match up.

Also :notifyLocalized() is for translated messages. You should just use
:notify()

**Comment by Rubberbandits** [comment]
[ERROR] lua/entities/slotmachine/init.lua:34: attempt to compare number with boolean
1. unknown - lua/entities/slotmachine/init.lua:34
   1. unknown - lua/includes/modules/concommand.lua:54

**Comment by Chessnut** [comment]
The reason why: !tostring(123) >= ArgToUse

The ! is negating the number, turning it into a boolean. Then you are comparing if the boolean is greater than or equal to ArgToUse. So instead just check if it is less than ArgToUse rather than checking if it not greater than or equal to.

**Comment by Rubberbandits** [comment]
Yep, just removed it and it fixed it..
