### ISSUE TITLE
What is 'L'?

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#510]
Hey chessnut, since this is the only place to ask questions, what is L used for in the framework? I see it being used in derma to return character object stuff, but is there a place I can find the function so I can use it in my own derma?

Example of what I'm talking about: 

```
self.money:SetText(L("charMoney", nut.currency.get(LocalPlayer():getChar():getMoney())))
```

**Comment by Chessnut** [comment]
https://github.com/Chessnut/NutScript/wiki/nut.lang

**Comment by Rubberbandits** [comment]
Thanks.
