### ISSUE TITLE
getInv() not being passed to item.player?

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#514]
Not entire sure why, but i'm getting the error of getInv() being an invalid method on item.player, but then if i try to pass client in the item function arguments, I get the error of GetEyeTraceNoCursor being an invalid method. Maybe it's because the item functions are being passed serverside(?)

here is the code: http://hastebin.com/eqojaceren.coffee

**Comment by Chessnut** [comment]
How are you using the place item function? Menu? Entity? For some reason
item.player is not defined which shouldn't happen.

**Comment by Rubberbandits** [comment]
It's via the inventory.

**Comment by Chessnut** [comment]
Did you try printing what item.player is?

**Comment by Rubberbandits** [comment]
It prints the player. Player [1][dank memes]

**Comment by Chessnut** [comment]
:getInv() is a method of the character object not the player.

**Comment by Rubberbandits** [comment]
so getChar():getInv() gg

**Comment by Rubberbandits** [comment]
Okay, even though this netstream hook is shared/client its not being passed the getChar object, even after networking the entity activator: http://hastebin.com/osuhorozud.coffee

i've tried activator, client, player. even using the function arguments and whatnot.

**Comment by Chessnut** [comment]
On line 36, change player to LocalPlayer()

You should probably add a break after sending the netstream on line 37 to prevent multiple net messages from being sent.

**Comment by Rubberbandits** [comment]
Yep, the break keeps the loop from running (thanks) and it all works now. I'll post a video soon to show you what i've done with it.
