### ISSUE TITLE
1.1 Suggestion

### ISSUE THREAD

**Issue by stnngfm** [Chessnut/NutScript#515]
Player become unconscious when player be hit by fist more than 5.

**Comment by Chessnut** [comment]
Maybe I should add a fake damage system so you can register a type of fake damage with a certain level of fake health. You don't actually lose real health and take actual damage, but the number of damage is stored.

Something like:

```
client:setupFakeDamage("punch", 50, function(client)
  client:ChatPrint("Knock out")
end)
```

And then this can also be used in the HL2 RP baton and such. Or in this case for knocking the player out. 

Also, how long should the player be knocked out for? I'm thinking either 45 seconds or a minute.
