### ISSUE TITLE
1.1 Spawnable Guns

### ISSUE THREAD

**Issue by pronyacat** [Chessnut/NutScript#516]
So, only works on ns1.1. If you are not admin, or admin...I dont care who you are, but you can spawn weapons. Go to Q>Weapons and press Mouse3. And here we go!

**Comment by Rubberbandits** [comment]
thats a big problem

edit: created a pull request to fix it

**Comment by pronyacat** [comment]
Cool, thanks!

**Comment by Chessnut** [comment]
Was this resolved or something?

**Comment by pronyacat** [comment]
Yes, its works.
