### ISSUE TITLE
Nutscript has failed to connect to database

### ISSUE THREAD

**Issue by valberts** [Chessnut/NutScript#518]
I installed tmsql4 for nutscript and configured the hostname, username and password in the sv_database.lua file, however nutscript still doesn't connect to the sql database.

**Comment by Chessnut** [comment]
Means your server can't connect just as it says. Something else is blocking the connection.

**Comment by Chessnut** [comment]
Also is there a MySQL error on the server console that shows up? There should be one. It can also show up on the NS loading screen.

**Comment by valberts** [comment]
Yes, on the console it says the error. Also, when you connect to the server it returns the error, making it impossible to create or load characters.

**Comment by Chessnut** [comment]
Well what's the error?

**Comment by Chessnut** [comment]
Also of course you can't load a character. How are you suppose to retrieve
a character from a database if it can't connect to a database?

**Comment by valberts** [comment]
Nutscript has failed to connect to the database.
Access denied for user 'gamersmovement_nutscript'@'%' to database 'nutscript'

**Comment by Chessnut** [comment]
So your MySQL server isn't allowing the server to connect. Make sure to
allow the server's IP to connect and have proper privileges to the database.

**Comment by valberts** [comment]
This is what the sv_database.lua file looks like at the bottom atm:
- Which method of storage: sqlite, tmysql4, mysqloo

nut.db.module = "tmysql4"

-- The hostname for the MySQL server.

nut.db.hostname = "gamersmovement.com"

-- The username to login to the database.

nut.db.username = "gamersmovement_nutscript"

-- The password that is associated with the username.

nut.db.password = "blank"

-- The database that the user should login to.

nut.db.database = "nutscript"

-- The port for the database, you shouldn't need to change this.

nut.db.port = 3306

i hope this helps in any way, I'm looking into the permission on the mysql also

**Comment by Chessnut** [comment]
Look at the MySQL error
