### ISSUE TITLE
[1.1] Vendor's "Sell price scale" resets/stays at 0.0

### ISSUE THREAD

**Issue by smt923** [Chessnut/NutScript#520]
So whenever we make the vendor's sell price scale 1.0 it only seems to apply for certain people (if I set it to 1.0, another friend may still see it as 0.0), when it's set to 1.0 for me then the sell price scale works as intended, but if it's only 1.0 for another person and not for me then the scale works as if it was on 0.0 for everyone, but that person (which doesn't seem possible so maybe I'm a bit wrong) either way the price scale doesn't appear to be setting correctly and it doesn't save over restarts

Just to sum up some testing we just did: an admin set it to 1.0 and it showed 1.0 on his end, a non admin used the vendor and the affects were as if it was 0.0

Should probably have said this in the first place but there's no errors or anything, checked server and client, plus we're running on linux (centos 7)

**Comment by Chessnut** [comment]
You need to keep the slider at one position for one second after every time you move it for the scale to get set. So if you quickly move the slider and close the editor then the change won't get sent.

**Comment by smt923** [comment]
That seems to kinda work? this is really hard to explain, I set it to 1.0 and someone who was in the server already can see it fine, plus the price's are correct for me, but someone who joined after still sees it as 0.0, even if i set it to 0.0 then back to 1.0 again, he STILL sees it as 0.0, really not sure why

if he then sets it to 1.0 him self, it's fine for everyone now

Edit: vendor is back at 0.0 for me now too, this is after a restart or two

**Comment by Chessnut** [comment]
Does it play a sound when you edit the scale?

**Comment by smt923** [comment]
Yeah, it plays the little beep noise thing whenever we edit it, I made sure everyone who edits it can hear it but it still doesn't change for everyone even with the beep

**Comment by Chessnut** [comment]
I realize that it only changes for people viewing the menu. However this does not affect the server so prices will still scale correctly.

**Comment by smt923** [comment]
It still seems to affect the prices for people depending on if they can see the scale properly or not, plus it isn't saving through restarts either

**Comment by Chessnut** [comment]
The price label isn't going to be accurate, but the prices will be the same on the server. As for it not saving, it may be an issue where a file cannot be written to your server.

Also the default scale is 0.5 so I don't see how it is "resetting" to 0

**Comment by smt923** [comment]
Okay so yeah I think the value it's self is working okay, the slider + value on the menu resets to 0.0 (I set it to 1.0 and then rejoined to test it, and yeah I know the value its self is 0.5 by default [but on the panel for me it's reset to 0.0](http://i.imgur.com/MtqDiFG.png)), and when you click an item to sell [it displays the price as if the scale was 0.5](http://i.imgur.com/vqXr1Wa.png), but of course [sells for the full amount as if it was 1.0](http://i.imgur.com/27b9Xdh.png), so I think it's technically fine just the clientside "resetting" stuff is pretty annoying - if I move the slider to 1.0 again, it's obviously 100% fine and "in sync"  

hopefully the images help me explain it a little more clearly

**Comment by Chessnut** [comment]
I can't replicate this.
