### ISSUE TITLE
Error When Opening F1 Menu

### ISSUE THREAD

**Issue by dhkatz** [Chessnut/NutScript#525]
I just started having this issue when opening the F1 menu.

[ERROR] gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:762: attempt to index a number value
1. Run - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:762
   1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:139
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
      1. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      2. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

No core files are modified.

**Comment by Chessnut** [comment]
What player model are you using?

**Comment by dhkatz** [comment]
A playermodel from here: http://steamcommunity.com/sharedfiles/filedetails/?id=127992073

**Comment by Rubberbandits** [comment]
This happens if your playermodels don't have the animations that a holdtype is requesting.
