### ISSUE TITLE
SQL storage

### ISSUE THREAD

**Issue by skarphet** [Chessnut/NutScript#527]
I don't have Garry's Mod or SRCDS installed at the moment -- how does the data Nutscript stores in SQL look? Any sort of encoding, JSON (pls no) or vON or anything?

**Comment by Chessnut** [comment]
Look at the SQL table creation queries in core/libs/sv_database to see the
structure

**Comment by skarphet** [comment]
So if I'm reading that code correctly, you're essentially just actually using SQL properly unlike Clockwork?

**Comment by Chessnut** [comment]
I guess

**Comment by skarphet** [comment]
Awesome, thanks a bunch Chessnut. May hit you up on Steam later if that's alright (whenever you're back to Steam).

**Comment by Chessnut** [comment]
Next time please keep things that aren't actual framework issues to the NS
forums at http://nutscript.rocks/community

**Comment by skarphet** [comment]
Yeah, my bad.
