### ISSUE TITLE
[1.1] sh_pon.lua:205: bad argument #2 to 'sub' (number expected, got userdata)

### ISSUE THREAD

**Issue by smt923** [Chessnut/NutScript#531]
``` lua
[nameeeeeeee|119|steamidddddddd] Lua Error:
NetStream: 'nVar'
gamemodes/nutscript/gamemode/core/libs/external/sh_pon.lua:205: bad argument #2 to 'sub' (number expected, got userdata)
```

Not sure what's making this happen, server's been up quite a while so many just lots of activity, seems to happen twice per player and it's only just started happening

**Comment by Chessnut** [comment]
Did you try networking a function?

**Comment by Chessnut** [comment]
This includes setting a character data to something that is a bad data type

**Comment by smt923** [comment]
I don't think so, most of the stuff is made by other people so I[ll have to check, but that also means it's fairly possible I suppose

**Comment by smt923** [comment]
Okay on closer inspection it seems to happen whenever a player loads a character and spawns, I can't really find any function that's being networked though, like not in any plugins anyways

**Comment by Chessnut** [comment]
It is probably related to setNetVar since the error is coming from the nVar
net message.

**Comment by smt923** [comment]
Well that narrows it down to the notes plugin (from here https://github.com/tltneon/nutscript_plugins/tree/ns-1.1/plugins) and the badair plugin ([from modern rp](https://github.com/rebel1324/modernrp/tree/master/plugins)), 

Maybe badair because in the entire thing there's these two http://i.imgur.com/C5pCHed.png - but as is becoming obvious I don't know a huge amount of lua so can't really debug it much further than guesses and slapping prints around the script

**Comment by Chessnut** [comment]
I'll make the function throw an error with an invalid type once I can.

**Comment by Chessnut** [comment]
Did the update work?

**Comment by smt923** [comment]
So far it seems too, haven't had a huge amount of players to test but haven't seen it so far so it looks to have

**Comment by Chessnut** [comment]
So does that mean it made an error or not?

**Comment by smt923** [comment]
No it didn't make the error, it's fixed

**Comment by Chessnut** [comment]
You've been checking the server console for errors right

**Comment by smt923** [comment]
yeah I'm not that stupid, that's where the errors were, I wasn't sure earlier cause not many people were on (and i hadn't seen it before so assumed it was more likely to happen with more players on or soemthing, didn't seem like a 100% certain thing) but after the whole day it hasn't been there once so it appears to be totally fixed
