### ISSUE TITLE
Networking item changes to clients?

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#536]
Not entirely sure on this, but its more of a question.

How would networking item changes to the client work? There is the displayItemInformation function, but do we set up our changes? 

Using this code here:

for k, v in pairs(Entity(1):getChar():getInv():getItems(true)) do if (v.category == "Other") then v.name = "changed name" end end 

does effect ITEM.name, but do we start a netstream hook that is on the client to verify these changes?

I'd assume my hook would be something like this:

netstream.Hook("updateChange", function()
    for k, v in pairs(LocalPlayer():getChar():getInv():getItems(true)) do
        local itemTable = v

```
    if (itemTable) then
        local oldData = itemTable.data
        itemTable.data = self.getNetVar(self, "data", {})
        itemTable.entity = self
                    itemTable.name = itemTable.name

        local description = itemTable.getDesc(itemTable)

        itemTable.entity = nil
        itemTable.data = oldData
    end     
       end
```

end)

Would this network our changes properly to the client?

**Comment by Chessnut** [comment]
1. If you change a variable on the server, it is only changed on the server. If you change it on the client, it only changes for the client.
2. You're right on needing to network the change to the client.
3. Why do `local itemTable = v`? You can just use `for k, itemTable in pairs(...) do` instead.
4. `self.getNetVar(self, "data", {})` what's self? You have a bad habit of pulling variables from thin air.
5. All you would need to do is network which item you want to change (probably use uniqueID) and the new name. Why are you also modifying the data and entity?

**Comment by Rubberbandits** [comment]
It's just updating the itemtable in general, used it as an example.

PS: those self things are fixed, just forgot to fix it in the post.

**Comment by Rubberbandits** [comment]
This is offtopic, but using the animation tables how can we set what animations play when jumping, or crouchwalking?
