### ISSUE TITLE
Hunger bar issue.

### ISSUE THREAD

**Issue by 7beat** [Chessnut/NutScript#537]
Hello! Its spamming in my console after few mins of playing on server? Any idea how to fix it? I would be grateful :)

[ERROR] gamemodes/stalker/plugins/cookfood/sh_plugin.lua:65: attempt to index upvalue 'hungerBar' (a nil value)
1. v - gamemodes/stalker/plugins/cookfood/sh_plugin.lua:65
   1. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:397

And there are 2 stamina bars!

And also got a question: nut.anim.setModelClass("MODEL", "player") Where do i exactly must write it in sh_schema. Asking cuz if i place it under SCHEMA.desc it doesnt work. (MODEL is just example)

**Comment by Thadah** [comment]
Could you please give a link from where you got the CookFood plugin? And which version of NutScript are you using?

**Comment by 7beat** [comment]
So im using 1.1 ns (downloaded 2days ago) and cook mod is from modern rp.

**Comment by Chessnut** [comment]
Is one of your plugins removing the hunger bar? Also try updating.

**Comment by 7beat** [comment]
Wow after i used cook food from plugins i cant even spawn stove, eat,drink. Is it because modernRP is outdated?

**Comment by Chessnut** [comment]
Are there errors on the server? There haven't been any updates that would
break the schema.

**Comment by 7beat** [comment]
Hmm  it seems to be working correctly now. I've deleted some plugins. Could you answer about my question where in sh_schema must put nut.anim.setModelClass("MODEL", "player") ?

**Comment by Chessnut** [comment]
nut.anim.setModelClass like that should work fine. If the model is
T-posing, it's probably not an actual player model. See the wiki for
reference of available animation classes (
https://github.com/Chessnut/NutScript/wiki/nut.anim)

**Comment by 7beat** [comment]
Oh ye. It's working thanks!

**Comment by 7beat** [comment]
And i discoverd that hungerBar is breaking whenever you save changed files in schema while game is running.
