### ISSUE TITLE
Netstream broke?

### ISSUE THREAD

**Issue by Rubberbandits** [Chessnut/NutScript#538]
I don't get any errors, but all my netstream hooks that worked last time I worked on this seem to have broke.

Any ideas how to fix?

**Comment by Chessnut** [comment]
No

**Comment by Rubberbandits** [comment]
After reinstalling the framework, it still doesn't work. I've been trying to use lua_run netstream.Start("blah") and it still won't do anything. No errors, no anything.

After using requestString i've found that all the nutscript netstream hooks still work somehow when mine don't???

**Comment by Chessnut** [comment]
That's because you use lua_run netstream.Start(nil, "blah")

Also make sure your file with the hook is running (add a print to see if it
loads), and check to see if your script is actually sending anything (add a
print before it sends).

I've noticed most of your NS issues are a result of something you did so
debug your code more.

**Comment by Rubberbandits** [comment]
Somehow my include code got fucked and removed itself or I removed it myself for some reason.

**Comment by Chessnut** [comment]
See what I mean

**Comment by Rubberbandits** [comment]
Yes, yes I do.

I'm guessing this error is something I did too?

[ERROR] gamemodes/nstest/schema/items/sh_bleach.lua:40: attempt to index a string value with bad key ('setData' is not part of the string library)
1. error - [C]:-1
   1. __index - lua/includes/extensions/string.lua:310
   2. unknown - gamemodes/nstest/schema/items/sh_bleach.lua:40
      1. unknown - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:640
      2. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:117
      3. unknown - lua/includes/extensions/net.lua:32

That has to be a netstream error, because even when using a table loop inside of requestString, it always will shit out that error. the error is always the exact same except for 1 thing, the string that it says is NOT a string..

**Comment by Chessnut** [comment]
Show me the line

**Comment by Rubberbandits** [comment]
This is off because that error is old, but it still gets the point across. After our objects, whether it be v, player, client, LocalPlayer()

that same error is returned but the "string value" is different.

according to netstream it's string.

http://hastebin.com/suyakaxequ.coffee

**Comment by Chessnut** [comment]
You do know that the client variable in the requestString method is the
string the client typed right? So you are using player methods on a string
value. Again with the magical variables, you never defined "text".

**Comment by Rubberbandits** [comment]
text is supposed to be returning text of derma_requeststring.

it's automatically defined by it iirc

Alright, lets assume its not. item.player is defined by the onRun callback, and now we've defined text. lets see what happens.

And player is undefined. real nice. Not item, but player. I've tried LocalPlayer because you know, it's being networked to the client.

I thought requestString in the util library just called Derma_StringRequest on the client.

**Comment by Chessnut** [comment]
You aren't using Derma_StringRequest, you're using client.requestString
from the nut.util library.

Also why would a function define a global variable to use? That's not how
it works.

**Comment by Rubberbandits** [comment]
I thought requestString in the util library just called Derma_StringRequest on the client.

At this point I've tried every player object there is. LocalPlayer(), item.player, player, client.

LocalPlayer() is apparently an undefined global variable, if I use item.player, player is apparently undefined.

Player is apparently undefined, and same with client.

**Comment by Chessnut** [comment]
Yes it does but you're saying that the Derma_RequestString:
1. Defines a global variable called "text" which it doesn't. Keep in mind
   how function arguments work. Also just because you name a variable/argument
   something doesn't make it something else than what is passed.
2. The variable is somehow set on the server from the client.

Read your code again and print what client is. It will be a string. In your
item you end up trying to do ("something
here"):getChar():getInv():getItems(true) which doesn't make any sense.

**Comment by Chessnut** [comment]
LocalPlayer is defined on the client only. onRun only runs server side.
item.player is probably out of the scope of the callback so you should put
local client = item.player outside of the callback.

**Comment by Rubberbandits** [comment]
Let's try defining client like that.

And it happens to work. Getting any player object to fit into the scope of the callback is odd and creates a dickload of errors.

Now let's try networking the change to the client. How would we go about that? I've tried alot of things related to it. I'm not entirely sure how to grab the actual change. Maybe we can do it like this.

On Server, in our requestString:

netstream.Start(client, "updateItemChangeName", text)
print("hook called")

And since now that text variable is being passed to our hook, we can do this on client:

netstream.Hook("updateItemChangeName", function()
  for k, v in pairs(client:getChar():getInv():getItems(true)) do
    if (v:getData("editing") == "true") then
      print(text)
      print("net received")
      v.name = text
    end
  end
end)

Let's try it out and see how it goes.

alright, after testing it and getting no errors I don't see any prints which is very odd. I'm guessing nothing is actually happening.
