### ISSUE TITLE
Lootable Plugin [Error]

### ISSUE THREAD

**Issue by 7beat** [Chessnut/NutScript#540]
Hello! Is there any way to update it or fix? I really need it for my server.

[ERROR] gamemodes/stalker/plugins/sh_lootable.lua:13: table index is nil
1. unknown - gamemodes/stalker/plugins/sh_lootable.lua:13
   1. include - [C]:-1
   2. include - gamemodes/nutscript/gamemode/core/sh_util.lua:32
      1. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
      2. loadFromDir - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:179
      3. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:166
      4. unknown - gamemodes/nutscript/gamemode/shared.lua:65

**Comment by Chessnut** [comment]
What's the lootable plugin? Also this issue tracker should only be for the framework itself

**Comment by 7beat** [comment]
Uhm i thought u know this plugin. Its about droping weapons on the ground from backpack after death. And i got little question: is there any way to add gasmask's overlay to pac outfit. For example you are equiping hazmat outfit and you got respirator's overlay.

**Comment by Chessnut** [comment]
Lootable isn't included in the NutScript framework. Also the gasmask plugin already has a mask.

**Comment by 7beat** [comment]
Hmm i downloaded it from plugins page.

**Comment by Thadah** [comment]
This plugin repository https://github.com/Chessnut/NSPlugins is only for NutScript 1.0, so it won't work with NS 1.1, although I think someone ported it to 1.1, not sure tho.

**Comment by Chessnut** [comment]
Post your plugin issue on the NutScript forums. Keep this issue tracker to framework issues only.

**Comment by 7beat** [comment]
Thanks for respond.
