### ISSUE TITLE
getNutData (shared) not working clientside.

### ISSUE THREAD

**Issue by voxelizedworld** [Chessnut/NutScript#541]
I'm trying to use getNutData, It only provides info to the server, unless the data is about the localplayer. Is there a different function I should be using to store data on the player, or is getNutData broken?

**Comment by Rubberbandits** [comment]
are you attempting to get player data or character data?

doesn't seem broken. it does what it's supposed to as far as i know

**Comment by voxelizedworld** [comment]
I'm trying to get player data. for other players.

**Comment by Rubberbandits** [comment]
then network it from the server to the client

done

**Comment by voxelizedworld** [comment]
Yes, but shouldn't getNutData/setNutData do this?

**Comment by Rubberbandits** [comment]
probably not.

**Comment by Rubberbandits** [comment]
lets go look at the function

**Comment by Rubberbandits** [comment]
```
if (SERVER) then
```

then you have an else statement, which then has your function which stores the return in a table

then it networks it to the client, line 30 and line 35.

**Comment by Chessnut** [comment]
Why would data (white lists, play time, last join time, etc...) for other
players be networked to other players than yourself?

**Comment by voxelizedworld** [comment]
I'm starting to work on an administrative menu, So that kind of data would be nice.

**Comment by Rubberbandits** [comment]
if you're making an administrative menu you should know how to network.

**Comment by voxelizedworld** [comment]
I do, I was just asking to see if getNutData was intended to do this.
