### ISSUE TITLE
Props and toolguns don't spawn!

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#542]
Whenever i join my server as a superadmin i can't spawn props, vehicles, or toolguns but i can spawn in guns, and WAC Aircraft. I use ULX admin and i dont know how to fix this.

My server is base off of the moderRP base

**Comment by kawht** [comment]
Where do i find all flags?
And i can't spawn vehicles

**Comment by Rubberbandits** [comment]
cC is for vehicles. i think you can use the help menu or you can just give yourself every alphabet letter capital and lowercase and it should let you do everything

**Comment by kawht** [comment]
ok
