### ISSUE TITLE
couldn't include file 'sh_config.lua' (line 32) + sh_dat.lua:49 attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by FlavorTown** [Chessnut/NutScript#543]
Couldn't include file 'sh_config.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 32))

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:49: attempt to perform arithmetic on a nil value
1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:49
   1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
      1. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      2. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

Running latest NS base.

Happens every time you open up F1 menu, sometimes even opens up the spawn menu with it.

**Comment by Chessnut** [comment]
Check if sh_config is inside nutscript/gamemode/core/libs

**Comment by FlavorTown** [comment]
It isn't.
...
is it supposed to be in /libs?

**Comment by Chessnut** [comment]
Wait it shouldn't be there anyways. I don't see how you're getting this error because the load order puts the config stuff before the libraries, so this shouldn't happen.

**Comment by FlavorTown** [comment]
here's the sh_data.lua

nut.date = nut.date or {}
nut.date.cache = nut.date.cache or {}
nut.date.start = nut.date.start or os.time()

if (!nut.config) then
    include("sh_config.lua")
end

nut.config.add("year", 2015, "The starting year of the schema.", nil, {
    data = {min = 0, max = 4000},
    category = "date"
})
nut.config.add("month", 1, "The starting month of the schema.", nil, {
    data = {min = 1, max = 12},
    category = "date"
})
nut.config.add("day", 1, "The starting day of the schema.", nil, {
    data = {min = 1, max = 31},
    category = "date"
})

if (SERVER) then
    function nut.date.restore()
        nut.date.start = nut.data.get("time", os.time(), false, true)
    end

```
function nut.date.get()
    local unixTime = os.time()

    return (unixTime - nut.date.start) + os.time({
        year = nut.config.get("year"),
        month = nut.config.get("month"),
        day = nut.config.get("day")
    })
end

function nut.date.send(client)
    netstream.Start(client, "dateSync", CurTime(), os.time() - nut.date.start)
end
```

else
    function nut.date.get()
        local realTime = RealTime()

```
    -- Add the starting time + offset + current time played.
    return nut.date.start + os.time({
        year = nut.config.get("year"),
        month = nut.config.get("month"),
        day = nut.config.get("day")
    }) + (realTime - (nut.joinTime or realTime))
end

netstream.Hook("dateSync", function(curTime, offset)
    offset = offset + (CurTime() - curTime)

    nut.date.start = offset
end)
```

end

**Comment by Chessnut** [comment]
You don't need to copy and paste a file, they're all on GitHub.

**Comment by FlavorTown** [comment]
I blame my severe autism for being able to forget this obvious fact.

I'm just showing that i haven't changed a thing.

**Comment by Chessnut** [comment]
Are there any errors in the server console?

**Comment by FlavorTown** [comment]
On server startup

[AddCSLuaFile] Couldn't find 'sh_config.lua' <@gamemodes/nutscript/gamemode/core/sh.util.lua (line 29))

Couldn't include file 'sh_config.lua' (fFile not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 32))

When connected to the server : 

Couldn't include file 'sh_config.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 32))

And ofcourse, pressing F1 causes this : 

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:49: attempt to perform arithmetic on a nil value
1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:49
   1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
      1. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      2. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

**Comment by Chessnut** [comment]
Do you have sh_config in nutscript/gamemode/core? Also make sure the file is not empty

**Comment by FlavorTown** [comment]
Yes, it is entirely - not empty.

**Comment by Chessnut** [comment]
Try re-installing the gamemode and restart the server. The file isn't loading for some reason

**Comment by FlavorTown** [comment]
Re-installed, problem still persists.

**Comment by Chessnut** [comment]
Not sure then, something is wrong with your files

**Comment by Thadah** [comment]
If you are using a Linux server be sure that the permissions for the file are well configured. I've had a lot of issues because of the permissions.

**Comment by Imacc2009** [comment]
I'm also getting this problem on a Windows server.
