### ISSUE TITLE
[1.1] General error: Vending machine

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#544]
[ERROR] gamemodes/nsscifirp/schema/hooks/sv_hooks.lua:44: attempt to call method 'saveVendingMachines' (a nil value)
1. unknown - gamemodes/nsscifirp/schema/hooks/sv_hooks.lua:44
   1. Run - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:406
   2. unknown - gamemodes/nutscript/gamemode/core/sv_data.lua:83

**Comment by Chessnut** [comment]
Did you define saveVendingMachine?

**Comment by CaptJack92a** [comment]
I haven't messed with most of that part of the script, no. Originally the schema was the super basic version of hl2rp, but the error was new, so I just reported it in case a change in the framework was weird.

**Comment by Chessnut** [comment]
Well it seems like you just removed one part of the schema's code without
removing another dependent part.

**Comment by CaptJack92a** [comment]
Well, darn. I haven't done anything with them that I can remember, the code's super simple change wise. It's mainly plugins I make and alter and faction scripts in the schema and hooks and such so certain factions have access to certain things, but I don't recall doing anything like this... Oh well.
