### ISSUE TITLE
[1.1] Issues since last few updates

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#545]
## 1- Business menu is seen by all once more

function SCHEMA:CanPlayerUseBusiness(client, uniqueID)
    if (client:Team() == FACTION_BMD) then
        return true
        else
        return false
    end
end

No longer works.
## 2- The click boxes on some menu items is kinda wonky.

Not 100% sure if it's clientside or NS yet.
## 3- General load-up Errors.

[ERROR] gamemodes/nsscifirp/schema/sh_config.lua:17: table index is nil
1. unknown - gamemodes/nsscifirp/schema/sh_config.lua:17
   1. include - [C]:-1
   2. include - gamemodes/nutscript/gamemode/core/sh_util.lua:32
      1. unknown - gamemodes/nsscifirp/schema/sh_schema.lua:134
      2. include - [C]:-1
      3. include - gamemodes/nutscript/gamemode/core/sh_util.lua:32
      4. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
         1. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:163
         2. unknown - gamemodes/nutscript/gamemode/shared.lua:65

[CaptJack92a|3|STEAM_0:0:21715433] Lua Error:

[ERROR] gamemodes/nsscifirp/schema/sh_schema.lua:173: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
   1. unknown - gamemodes/nsscifirp/schema/sh_schema.lua:173
   2. include - [C]:-1
      1. include - gamemodes/nutscript/gamemode/core/sh_util.lua:32
      2. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
      3. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:163
      4. unknown - gamemodes/nutscript/gamemode/shared.lua:65

**Comment by Chessnut** [comment]
These errors are from your schema, not the framework.

**Comment by CaptJack92a** [comment]
Well item number three might be, but the first issue was definitely something that happened since the framework update and were fine before.

As the the weird clicking, It may be client side. Trying to figure out what scripts I have if any were recently changed otherwise.

**Comment by Chessnut** [comment]
[ERROR] gamemodes/nsscifirp/schema/sh_config.lua:17: table index is nil ??
What's the line? When you post errors you're going to need to provide
context. I'm not magically able to read your code.

As for the business it could be a plugin overwriting the hook return.

**Comment by CaptJack92a** [comment]
Yeah, turns out it is crashing the game as well now. I have been messing with plugins, but didn't see anything that could cause conflicts in the code. It's more than likely I'll just remove the business menu since it's easier to just do so and give the BMD faction a vendor rather than let them magically 

As for line 17, it's a closing bracket for...

-- Customize the beep sounds here, before and after voices.
SCHEMA.beepSounds = {}
SCHEMA.beepSounds[FACTION_MILITARYCDT] = {
    on = {
        "npc/overwatch/radiovoice/on1.wav",
        "npc/overwatch/radiovoice/on3.wav",
        "npc/metropolice/vo/on2.wav"
    },
    off = {
        "npc/metropolice/vo/off1.wav",
        "npc/metropolice/vo/off2.wav",
        "npc/metropolice/vo/off3.wav",
        "npc/metropolice/vo/off4.wav",
        "npc/overwatch/radiovoice/off2.wav",
        "npc/overwatch/radiovoice/off2.wav"
    }
}

**Comment by Chessnut** [comment]
nil index means FACTION_MILITARYCDT isn't defined

**Comment by CaptJack92a** [comment]
I hate myself sometimes. You are now permitted to hate me too.
