### ISSUE TITLE
How do i assign flags to a certain ulx group

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#546]
Like if i want all of the super admins to have "/flaggive petrC" and the users to have "/flaggive pet" then how would i do that?

Also, where would i find all of the flags available?

**Comment by Chessnut** [comment]
You can check the player's usergroup when they initially spawn and give the player any missing flags.

I'll make a flag list once I get home.

**Comment by kawht** [comment]
But how?

**Comment by Chessnut** [comment]
Using Lua?

**Comment by kawht** [comment]
Yea but like where and what file, i know lua very well but i don't know nutscript that much

**Comment by Chessnut** [comment]
http://wiki.garrysmod.com/page/GM/PlayerInitialSpawn
http://wiki.garrysmod.com/page/Player/IsUserGroup
https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/libs/sh_flag.lua#L45

**Comment by Brin900** [comment]
Is there any console command to issue flags to people, and this is a different subject but I renamed my ULX ranks and lost perms to issue flags somehow, is there anywhere that defines the name of the rank to the permissions it has to flags?
