### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#547]
Where is the nutscript database located? I need to completely reset it.

Also, where are the server player's faction characters located?

Thanks
- Red

**Comment by Chessnut** [comment]
sv.db in the main Gmod folder. If you need to reset something then use
nut_recreatedb in the server console. As for the factions, they are defined
in your schema's faction folder, hence the name.

**Comment by kawht** [comment]
Thanks, but i want to know where the saves for the server players created faction characters are, not the faction base

EDIT: Nvm found it :P

**Comment by Chessnut** [comment]
In the database?

**Comment by kawht** [comment]
Yea, i figured it out my bad
