### ISSUE TITLE
Cant' remove intro

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#549]
I tried to remove the nutscript intro by commenting out the cl_intro.lua file but when i loaded the server up instead of getting the menu i got a black screen with white text in the middle saying "Loading" and this doesn't go away

**Comment by Rubberbandits** [comment]
just dont remove it

**Comment by johnnyguitarFP** [comment]
The gamemode is actually loading data while the introduction is playing, I recommend you leave it enabled.

**Comment by kawht** [comment]
Ill keep it then
