### ISSUE TITLE
DefMoney value problems - Only applied to new chars upon server restart

### ISSUE THREAD

**Issue by myrrdin** [Chessnut/NutScript#552]
What happens is that when a character is created, his default money-value is 0.
If you try reloading the character, nothing changes.

However, if the server is restarted; he gets the value that he was supposed to be given.
The character cannot buy anything at all up until that point because he has no funds for it as he starts with 0.

I tried creating a new character when I had already created others and restarted, and it ended up with them having money and the new char missing money. They could buy stuff, but the new character could not.

It seems to be the same for Hl2RP and ModernRP.

Leaving the server does not help.
The server has to be restarted.

I have tried redoing it all. Adding the Nutscript gamemode and the Modernrp or HL2RP schema/gamemode and deleting the sv.db file; removing all the configs; but to no avail.

Any ideas?

No errormessages appear.

**Comment by Chessnut** [comment]
I don't understand what you're saying. The default money is used during the character creation query so of course it only applies to new characters.

Also the server doesn't need to be restarted. The default money only affects new characters after the config has been set.

**Comment by myrrdin** [comment]
Sorry, i'll clarify. I have the value set to 400 via the F1 menu (and it said that my character changed the value). If I create a new character after that, it says that the character has 0 dollars. But if I restart the server, he has 400; the value I set that he should have. Until the server restart, he cannot use that money.

**Comment by myrrdin** [comment]
Here are some screenshots

After setting a value
![valuechanged](https://cloud.githubusercontent.com/assets/5229795/8749316/177fafc8-2ca1-11e5-96f3-3093c75a90ac.png)

After creating the new char
![newchar](https://cloud.githubusercontent.com/assets/5229795/8749314/177938fa-2ca1-11e5-8f72-cd42cbb29d9b.png)

After restart
![restart](https://cloud.githubusercontent.com/assets/5229795/8749315/177d5cdc-2ca1-11e5-8426-f72041d965ce.png)
