### ISSUE TITLE
Can't remove the annoying gun safety

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#555]
I'm using FA:S weapons and they don't work until i hold r which is on every gun, even on the half life guns. I really want to remove this but i keeps giving me errors

**Comment by Thadah** [comment]
I might make a plugin about this

**Comment by Chessnut** [comment]
5dfeb8d may help. I'll also use this hook and add a config for weapons always being raised.

**Comment by Chessnut** [comment]
Use the configuration from a3f568140756e77987c8f349e1b13355fcbbf513.
