### ISSUE TITLE
Guns show next to your feet instead of in your hands

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#557]
Title

I've tried everything to fix this, no luck

**Comment by Rubberbandits** [comment]
issue with your models.

**Comment by kawht** [comment]
No because it does this with hl2 guns too

**Comment by Chessnut** [comment]
Did you try it with normal HL2 citizen models?

**Comment by kawht** [comment]
Yea and it is still broken

**Comment by Chessnut** [comment]
Got a screenshot of HL2 citizen with HL2 weapon?

**Comment by kawht** [comment]
It doesnt happen often but when it does ill screencap it
