### ISSUE TITLE
character:giveFlags(flags) is broken

### ISSUE THREAD

**Issue by kawht** [Chessnut/NutScript#558]
Whenever i call this in code, it gives me an error. Note that im using a custom command

[ERROR] gamemodes/nutscript/gamemode/core/sh_commands.lua:124: attempt to call m
ethod 'giveFlags' (a nil value)
1. onRun - gamemodes/nutscript/gamemode/core/sh_commands.lua:124
   1. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:145
   2. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:180
      1. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:240
      2. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
      3. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:117
      4. unknown - lua/includes/extensions/net.lua:32

**Comment by Rubberbandits** [comment]
are you calling just player:giveFlags? you need to include the character object if you are.

**Comment by kawht** [comment]
i am calling the object

**Comment by Chessnut** [comment]
Show code?

Also in the future, only _framework issues_ go here, not personal support for your customizations.

**Comment by kawht** [comment]
Code:

-- Location "C:\gmod_server\garrysmod\gamemodes\tbrfrp\gamemode\cl_init.lua"

DeriveGamemode("nutscript")

function GM:PlayerInitialSpawn( ply )
    if ply:IsUserGroup("superadmin") or ply:IsUserGroup("admin") then
        name = ply:GetName()
        nut.command.run(name, "flaggive", ply.." petrC")
        print("Given flags to " ..ply:GetName())
    end

```
if ply:IsUserGroup("user") then
    name = ply:GetName()
    nut.command.run(name, "flaggive", ply.." petr")
    print("Given user flags to " ..ply:GetName())
end
```

end

Also where should i ask questions based on nutscript instead of here?

**Comment by Thadah** [comment]
What he is telling you is that you cannot post as issue a problem that has appeared because you customized the code in your own way. You could use the forums in http://nutscript.rocks to ask other users for help

**Comment by Chessnut** [comment]
The first argument to `nut.command.run` is a player, not a string. Also, you can't concat a player object to a string. The third argument should be a table anyways.

**Comment by kawht** [comment]
Can you give me some code that will work?
