### ISSUE TITLE
Jittery game after opening character

### ISSUE THREAD

**Issue by DefenderVex** [Chessnut/NutScript#559]
Recently I along with a few other people have noticed some kind of jitter, it's doesn't feel like lag more like split second pauses as if you were constantly pausing an un-pausing a video. It seems to only occur AFTER you have loaded a character, if you are just sitting in the menu when you first join it's fine. I believe it's a recent issue, it only started happening within the last few months. I recorded a video of it, it's not the best res video in the world but you can easily notice what I mean.

https://dl.dropboxusercontent.com/u/55126910/Rec001.avi

**Comment by Chessnut** [comment]
Seems like it could be a plugin/addon. I haven't experienced any spikes like that.

**Comment by DefenderVex** [comment]
I have a feeling it might be something that does HUD painting but i'm going to look into it now.

**Comment by Chessnut** [comment]
Well I haven't changed anything recently with painting.

**Comment by DefenderVex** [comment]
Yea, it was just an idea. I stripped down the gamemode of any plugins and the issue is still happening.

**Comment by Chessnut** [comment]
It could be your server, who knows.

**Comment by DefenderVex** [comment]
I've tried it on a servers that are both on my local machine, a VM and on a regular hosting service, all produce the same result. I may end up having to move back to NS 1.0
