### ISSUE TITLE
[Q] /toggleraise

### ISSUE THREAD

**Issue by 7beat** [Chessnut/NutScript#563]
Hello! I have a little question about typing in chat /toggleraise or holding R. Is there any way to disable it? Asking because im using FA:S weaponry and they have already built holster system and its little annoying when weapon is raised but you still have to type command.

**Comment by Chessnut** [comment]
There's a config to always have weapons raised.

**Comment by 7beat** [comment]
Ok Thanks! Sorry for that question spam but is there any way to disable crosshair ?

**Comment by Chessnut** [comment]
Delete the crosshair plugin

**Comment by 7beat** [comment]
Oh thanks!
