### ISSUE TITLE
[1.1] Chat bug: A common hood between some glitches.

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#569]
Radioing certain phrases doesn't always work, saying certain phrases as a certain faction don't work properly, using certain phrases as a normal/citizen faction causes the chat glitch which keeps the chat bar up until a second hit of enter, but then your mouse doesn't get put away.

fixchatplz fixes all of them.

**Comment by CaptJack92a** [comment]
Update: Combine voice commands do not work.

"Copy"
"Citizen"
"Judge"
"Amputate"

And so on.

fixchatplz command does not work all the time.

Radio refuses to display certain phrases to anyone, but plays the sound.

**Comment by blt950** [comment]
I think you need to post this in HL2RP issues as this is a HL2RP issue, except the chatbox thing.

**Comment by CaptJack92a** [comment]
Thing is, I didn't change anything that would break those commands in the schema, and it's semi-consistent. If I was using a faction character that say was my replacement for combine, letting them use the /objectives and such, the setup I used to confirm them for iscombine faction use would all be stable. And they were at one point. This issue is more recent and no plugins or script changes I've made had any effect o this.

**Comment by Chessnut** [comment]
Check if 5bb02f25dd382cdb19cc1a871e1a5a0d6a7d32b5 fixed this.

**Comment by CaptJack92a** [comment]
This has started to show up.

[ERROR] gamemodes/nsscifirp/schema/sh_voices.lua:27: attempt to index local 'beeps' (a nil value)
1. onModify - gamemodes/nsscifirp/schema/sh_voices.lua:27
   1. unknown - gamemodes/nsscifirp/schema/hooks/sv_hooks.lua:227
   2. Run - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:406
      1. send - gamemodes/nutscript/gamemode/core/libs/sh_chatbox.lua:165
      2. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:253
      3. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
      4. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
         1. unknown - lua/includes/extensions/net.lua:32

It looks like a schema problem, but I've gone through these files and lines and can't figure out what it's doing wrong or what I may have changed that's doing something wrong...?

**Comment by CaptJack92a** [comment]
Anyhow. I'll toss this back into the forums since it's now appearing to be a schema problem.

**Comment by Thadah** [comment]
Maybe adding an IsValid(beeps) could solve that issue

**Comment by CaptJack92a** [comment]
I think the problem is more so that the factions I created to replace the combine factions are being misinterpreted somewhere. I will keep looking, but for now since it's looking more like a schema problem [Since I went back into hl2rp schema as well and the CPs there work fine], I moved this issue to the forums: http://nutscript.rocks/community/showthread.php?tid=236

**Comment by Chessnut** [comment]
So does that mean the original issue is fixed?

**Comment by CaptJack92a** [comment]
So far, yes. But your fix was necessary to reveal that log I needed to track things down, so thank you!
