### ISSUE TITLE
Better ammo loading [suggestion]

### ISSUE THREAD

**Issue by koen24** [Chessnut/NutScript#570]
For lack of a better place, I'll leave this here.
Whenever a weapon is loaded with ammo, its primary clip is filled and the rest goes into its 'secondary clip'. That means that someone could theoretically load infinite boxes of ammo, even though the 6x4 inventory would only allow allow them to carry 24. That seems odd; ammo that isn't directly inside your weapon should take up inventory space.

It would be better if ammo was loaded directly from the inventory into the first clip. Example: If I have an empty .357 magnum with a capacity of 6 rounds, and a box of .357 ammo with 12 rounds, and I would load the box; the box would lose 6 rounds, and the gun would gain 6. No more than its capacity. The remaining 6 rounds in the box would still take up inventory space, while the gun is now loaded

There is also still an issue (#553) where the ammo in the 'secondary clip' disappears whenever the server is restarted that seems hard to fix. This system would also fix that issue, because the secondary clip is ignored altogether.

You would obviously not be able to load any ammo if you do not have the corresponding weapon. 
If someone has 2 weapons equipped that use the same ammo type, it would just pick the one that is equipped, or one at random (or alphabetically)

**Comment by Chessnut** [comment]
Giving player ammo (Player.GiveAmmo) makes it to into the secondary clip.

**Comment by koen24** [comment]
You can set the amount of ammo in a weapon's first clip with weapon:SetClip1(number). You could also add it to the second clip and then force a reload with weapon:DefaultReload(ACT_VM_RELOAD)

I've checked though, and you would need to save the amount of ammo that is in the boxes, also on restart (If someone takes out some ammo, the server should remember that). It suffers from the same issue as weapons in #553, so we're probably better off looking into that issue again. It's odd, because some things (inventory content, characters, amount of money, etc.)  are saved, but other things (secondary ammo, items) aren't.
