### ISSUE TITLE
Spawning Issues

### ISSUE THREAD

**Issue by Pure612** [Chessnut/NutScript#576]
Heyo, I have a couple of issues. Whever I spawn in I can't move I get stuck in Midair (can't move) on top of that if I fallover I can get out but I will not be able to interact with entities and vehicles. also my guns are bugged when so.

_When I freeze and unfreeze myself through Mod its just Fixed_

**Comment by Pure612** [comment]
I also get    50  50  in the console

**Comment by Pure612** [comment]
75 50

**Comment by 7beat** [comment]
Maybe try deleting some shitty mods, reinstalling framework or cleaning schema.

**Comment by Pure612** [comment]
Deleted my plugin folder and it fixed it. Thanks for your support chestnut -_-

**Comment by LukeCall** [comment]
I know this may be old, but to follow up on his issue for people looking at it for help. He was most probably using Moderator plugin. This spits those errors up with 50's 25's and 75's and will not allow you to move, personally I did not try move so I didn't experience the other things involving entities, however I hope this helped as it is the reason.
