### ISSUE TITLE
See weapons that are equipped

### ISSUE THREAD

**Issue by maxyii** [Chessnut/NutScript#577]
Is it possible to locate me to, or tell me a way to be able to make weapons visible on the body when equipped even when not holding the weapon. Thanks

**Comment by blt950** [comment]
Search up this issue with search function, there is a variable you can set and configure to do exactly this. I saw a closed issue about it not long time ago.

**Comment by 7beat** [comment]
Just download modern rp theres plugin for this called css weapons.

**Comment by maxyii** [comment]
Oh yeah, thanks bro. :P
