### ISSUE TITLE
Show bodygroups+skins in Character Load and Scoreboard

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#578]
The character load and scoreboard should be displaying the character's set bodygroups and skin. It does this in F1 information menu, but not in character selection or scoreboard.

**Comment by Chessnut** [comment]
The code for it to show the bodygroups is there, so that's pretty odd.

**Comment by blt950** [comment]
That's odd, doesn't seem to show for me. Funny enough it shows in the F1 information menu.

**Comment by blt950** [comment]
I think you're mistaken @Chessnut , because the only place I find you setting skin and bodygroups is in cl_information.lua, which explains it's not visible other places. 

I think you need to add the lines of bodygroups and skins in character loading and scoreboard, or add it as default in the nutModelPanel.

**Comment by Rubberbandits** [comment]
Adding it to the nutModelPanel would be most advantageous. I've also tried bonemerging models inside of DModelPanels and @Chessnut knows how that turned out.

**Comment by blt950** [comment]
Yeah, I agree that adding it to nutModelPanel would probably be the best as I see no reason of why you would like to show a model without the appropriate bodygroups.

**Comment by Chessnut** [comment]
Skin: https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/derma/cl_scoreboard.lua#L137
Bodygroups: https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/derma/cl_scoreboard.lua#L156
Materials: https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/derma/cl_scoreboard.lua#L164

I'll look into it.

**Comment by blt950** [comment]
That's odd. Though on character load I see no script that applies the groups and skins.

**Comment by Chessnut** [comment]
See if this is fixed in the scoreboard update

**Comment by blt950** [comment]
This solved the issue in the scoreboard. Still missing in character loading.

**Comment by Chessnut** [comment]
Bodygroup and skins aren't networked for character lists since it isn't essential.

**Comment by blt950** [comment]
What? How is that not essential?
I mean, it's more essential in the character loading than the scoreboard you ask me...
