### ISSUE TITLE
Animation Enums Strings

### ISSUE THREAD

**Issue by Zenolisk** [Chessnut/NutScript#581]
The current animation system does not work with Strings.

Look at the Combine Soldier for example, when the hands are equipped it looks like it tries to switch between T-Pose and the Animation Sequence. (string)

Here's an example: http://arcticnexus.biz/shit/2.webm

**Comment by Chessnut** [comment]
What weapon are you using because it works fine for me:

http://i.imgur.com/PgjwcG8.png

**Comment by Zenolisk** [comment]
Default hands that come with Nutscript, I will try removing some things on my side and update NS once more.

Edit: I've switched the string with an Enum and it works perfectly, I have no clue what is causing this.

[ACT_MP_STAND_IDLE] = {"idle_unarmed", ACT_IDLE_ANGRY},

to

[ACT_MP_STAND_IDLE] = {ACT_IDLE, ACT_IDLE_ANGRY},

Worked for me, obviously these are two different animations but strings seem not to work for me.

**Comment by Chessnut** [comment]
Aren't you demonstrating the walking animation though?

**Comment by Rubberbandits** [comment]
strings work fine, you're attempting to use a sequence and not something
that the engine deems as an act, i've had the same problem.

use GetSequenceActivityName to get the ACT_ enumeration from your sequence.

**Comment by Zenolisk** [comment]
The thing I'm trying to say here is that in NS 1.0 for example it works fine with sequence strings such as "idle_unarmed" and now in NS 1.1 it doesn't work for some reason.

Edit: I also go into T-Pose when crouching down with a weapon (pistol) as a Citizen Character (male)

**Comment by Chessnut** [comment]
@Rubberbandits using GetSequenceActivity just makes the models stand still.

**Comment by Rubberbandits** [comment]
I've used it, and I still use it to this day. Translating your sequences into activities solves all of these problems. Use print(Entity(1):GetSequenceActivityName((Entity(1):LookupSequence("sequencename")))

**Comment by Chessnut** [comment]
Right, but using that activity in CalcMainActivity just results in a still animation.

**Comment by Rubberbandits** [comment]
Using it in an animtable works.

**Comment by Chessnut** [comment]
Whatever is in the animation table still ends up being used for CalcMainActivity.

**Comment by Rubberbandits** [comment]
Interesting, it all works fine for me.

**Comment by Zenolisk** [comment]
@Rubberbandits if I use your method to get the ACT_ from sequence strings it still goes into T-Pose, I've made a clean install of gmod and NS plus HL2RP schema, still the same result.

http://arcticnexus.biz/p/test3.webm

EDIT: It must be my client because other people do not have this problem, I will try to fix it somehow.
