### ISSUE TITLE
Help Please 

### ISSUE THREAD

**Issue by GoproMgH** [Chessnut/NutScript#584]
Hello so im making a gtarp gamemode and there will be an npc to get jobs (similar to perp).
can you help me 
is there any way to use the /plytransfer without putting a players name.
I want it to change faction of the local player running the command.
Please Help 
And thanks in advance

**Comment by Chessnut** [comment]
Look at the code for the command.
https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/sh_commands.lua#L660
