### ISSUE TITLE
Sorry still need help 

### ISSUE THREAD

**Issue by GoproMgH** [Chessnut/NutScript#586]
Previously you told me to look at code.
I don't understand much sorry i'm just learning.
can u explain 
target:getChar().vars.faction = faction.uniqueID
https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/sh_commands.lua#L660

i do not understand Sorry man :(

**Comment by Chessnut** [comment]
It sets the faction to whatever faction ID is desired.

Don't make issues on GitHub for Lua help. Go to http://nutscript.rocks for asking questions instead.
