### ISSUE TITLE
Players Spawning Weapons in the F1 Menu

### ISSUE THREAD

**Issue by IamBrett** [Chessnut/NutScript#588]
Players can spawn weapons in the F1 menu, and I can't seem to find the file or line of code that allows me to remove that!! Please help!!!! I set the price of each weapon very high, but I would like the feature gone altogether!! Thank you.

**Comment by Chessnut** [comment]
The F1 menu doesn't have anything to spawn weapons

**Comment by Sascha8a** [comment]
I think he means, that players are able to buy weapons in the F1 menu and
he can't disable the F1 menu Business Tab.

**Comment by halworsen** [comment]
I think you can hook into BuildBusinessMenu and return false to disable it.

**Comment by IamBrett** [comment]
Where would I put the hook, though?

**Comment by NDKilla** [comment]
@IamBrett 
If you changed the price of items, doesn't deleting the file remove it from the business tab? Although this might make the weapon completely unusable. 

You could specify things like ITEM.faction or ITEM.flag to restrict who sees it in shop. If you want the item to exist but only select people can buy it, ITEM.flag is probably good. 

I'm also assuming you only want the weapons not purchasable, not that you want the entire business menu disabled.

**Comment by Chessnut** [comment]
You can also add `ITEM.noBusiness = true`

**Comment by Zenolisk** [comment]
The HL2RP Schema has a Business plugin, open the sh_plugin.lua and change the CanPlayerUseBusiness() function.

if you want that nobody can use it, simply return false like this.

function PLUGIN:CanPlayerUseBusiness(client, uniqueID)
    return false
end
