### ISSUE TITLE
need help making players drop weapons on death

### ISSUE THREAD

**Issue by Shysley** [Chessnut/NutScript#589]
I recently started doing NS servers (1.0 atm, 1.1 is unstable with my server for some reason :/) and with the current schema design i'm doing, a sorta zombie/apocolypse/thing, i wanted to set something up so that when a player dies, they drop all the weapons they have (not counting like, toolgun/fists/that sorta thing)

i DID manage to find a little code that supposedly does it, but i cant get it to work. due to being rather inexperienced with NS, and the fact that finding tuts other then how to setup a base schema is near on impossible it seems, i can't make this work or find out how to do so.

code; 

function PLUGIN:PlayerDeath( client )
....local items = client:getChar():getInv():getItems()
....for k, item in pairs( items ) do
........if item.isWeapon then
............if item:getData( "equip" ) then
...............nut.item.spawn( item.uniqueID, client:GetShootPos(), function()
..................item:remove()
................end, Angle(), item.data )
............end
.......end
....end
end

(ignore the ... for i dont know how to format it into a code style on here)

at the moment, i have it setup as a plugin, in a file called sh_plugin. lua
the only difference in the code here and in the .lua is that i also the PLUGIN.name/desc/author thing added too.

what do?

**Comment by Chessnut** [comment]
What do you mean it doesn't work? Do you not drop weapons? Does it give an error? Do the items themselves not work? Did you check if the item spawning part even runs? Did you check the items you want dropped have `isWeapon` defined?
