### ISSUE TITLE
Vendor Editing Derma

### ISSUE THREAD

**Issue by BillyNovel** [Chessnut/NutScript#590]
So basically, I'm running some customised HL2RP schema, without addition of items. And the issue is that I can't show up editing vendor derma, Never could. I've put myself as superadmin in ULX. The weird thing is that I'm not even getting errors.

Hope, someone'll figure it out. 
Thanks

**Comment by FlammableAce** [comment]
I also had this problem but I found that restarting the server after placing the vendor allows you to edit it.

**Comment by BillyNovel** [comment]
Tried it, my vendors aren't persisting :S. Used PermaAll tool on it, restarted, and tried to edit it, still not working. BTW, I can acces Talkers Editing Derma.

**Comment by FlammableAce** [comment]
Try keeping hold of C and right clicking on the vendor and enable Make Persistent and see if that makes them persist.

**Comment by BillyNovel** [comment]
It's not, even with sbox_persist 1. Could be only for sandbox.

**Comment by Chessnut** [comment]
You aren't suppose to use anything to persist it. It already should load and save on its own. If not, check if the server can write to your data folder properly because that's where vendors are saved.

**Comment by BillyNovel** [comment]
I've some datas in, but seems to be wiped clear each time the server boots.

**Comment by BillyNovel** [comment]
Alright, solved it. An outdated plugin was still on the server, messing with datas and with Editing Derma.  So thanks for getting me on the way of solving this :)
