### ISSUE TITLE
Can no longer edit Vendors

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#591]
The Vendor editing menu no longer comes up, allowing admins to set what vendors can and cannot sell, factions, etc.

**Comment by Chessnut** [comment]
It pops up if the player is considered an admin using client:IsAdmin(). So it may be an issue with your admin mod (rank set up wrong?).

**Comment by FlammableAce** [comment]
Try restarting the server after you have placed the vendor. That is what fixes it for me.

**Comment by CaptJack92a** [comment]
I'm still using ULX. It worked fine before a recent update, but I can't remember which one because I didn't need the vendors for a short while.

**Comment by Chessnut** [comment]
How recent was the update? The last change to vendors was July 16.

**Comment by CaptJack92a** [comment]
Honestly, that's possibly it. I have been exceptionally busy these last
several weeks and that could have easily slipped past my notice.
