### ISSUE TITLE
Score Board is Blank

### ISSUE THREAD

**Issue by reede2** [Chessnut/NutScript#592]
The Score Board Is Blank

**Comment by Sascha8a** [comment]
Did you turn on Scoreboard recognition?

**Comment by reede2** [comment]
where do i turn that on

**Comment by Sascha8a** [comment]
It needs to be off. In the F1 menu you can turn it off.

**Comment by reede2** [comment]
i turn it off and the score board is still blank.

**Comment by reede2** [comment]
other people show up but i dont
