### ISSUE TITLE
Score Board 

### ISSUE THREAD

**Issue by reede2** [Chessnut/NutScript#594]
Some People Show Up on it And Some People DoNT HELP ME please

**Comment by Chessnut** [comment]
Did c2affbe1cefe06aa26b6a27a75101b2b5856a84a fix it?

**Comment by reede2** [comment]
no

**Comment by reede2** [comment]
the score board not showing me on it !!!

**Comment by Chessnut** [comment]
You're using 1.1 right?

**Comment by reede2** [comment]
yes

**Comment by reede2** [comment]
you sould add me on steam and come and see what i mean
