### ISSUE TITLE
Sprint not Working.

### ISSUE THREAD

**Issue by LukeCall** [Chessnut/NutScript#595]
I do not really know what has caused this and I am currently still trying to see if I can fix it myself, but when I updated my Nutscript 1.1 today I noticed I couldn't sprint but it was using stamina. I think its safe to assume at the moment its the framework and not my schema as the only thing I have edited today is a plugin assigning models to models animations using nut.anim. I am still checking my recently edited but I have found nothing so far.

**Comment by reede2** [comment]
has this happined after This update to fix some Proplems

**Comment by LukeCall** [comment]
This happened after the latest update yes. Just tested it with an unedited Schema of HL2RP as well and the sprint still doesn't work.

**Comment by reede2** [comment]
did you remove the old files   when updating it because you could of  used the code from before the update.

**Comment by LukeCall** [comment]
When I tried with a unedited Schema of HL2RP, the Nutscript Framework had old files removed before updating and the Schema obviously new files with old ones removed.

**Comment by reede2** [comment]
what file do you need i can get it for you

**Comment by LukeCall** [comment]
I used old files form before the update but kept the updates to the Vendor plugin just in case because I wanted the new Vendor update as I reported the problem that was fixed but it still didn't work. It might be a data file I will have to check. Or a workshop addon I recently installed for the server.

**Comment by LukeCall** [comment]
Ok I really want to push this issue for some solutions because I have tried everything. I have tried updated nutscript with my schema, a clean schema "HL2RP" with updated nutscript, previous nutscript with updated vendors plugin with my schema and my schema with updated nutscript and refreshed / from scratch data ( the .txt files for plugins and for the config etc. ).

**Comment by Chessnut** [comment]
Updates don't touch the .txt files at all. Sprinting is working fine for me as and the last time the stamina code was touched was 5 months ago. Check your config to see if the runSpeed is actually a high number.

**Comment by LukeCall** [comment]
Before you posted that comment I had been ignoring the problem and developing a friend then when we realised the sprinting mechanic made us slower I searched the config for a "speed thingy" and found runSpeed at 114 and walkSpeed at 130. I would just like to point out however before I close it, it wasn't like this before so it may of automatically done it? Worth looking at I think. Closing now :)

**Comment by LukeCall** [comment]
Ok nvm... I may not know how to close it, Chessnut if you could close it I would appreciate it thanks.
