### ISSUE TITLE
CSS Weapon plugin edition bug.

### ISSUE THREAD

**Issue by BillyNovel** [Chessnut/NutScript#596]
Hi everyone, after editing the CSS weapons plugin and adding some custom weapons based on the plugin code, I've found myself starting the server with this error:
![1440517276-sh-item-bug](https://cloud.githubusercontent.com/assets/13874464/9471553/39aa1fd8-4b51-11e5-9225-06b420cda820.jpg)

It disabled the entities save. I tried to remove the customised plugin, and wipe the DB. None of that worked.

Hope someone'll find a workaround for that :)

**Comment by Chessnut** [comment]
Line 293 is blank.

**Comment by BillyNovel** [comment]
It's line 292 in fact.

**Comment by Chessnut** [comment]
You're trying to restore an inventory that doesn't have an ID.

**Comment by Chessnut** [comment]
Try updating and seeing the new error to trace its origin.

**Comment by BillyNovel** [comment]
Updating the DB ?

**Comment by Chessnut** [comment]
The framework

**Comment by BillyNovel** [comment]
Got this one now:
![sh_item bug2](https://cloud.githubusercontent.com/assets/13874464/9474181/5691c2fa-4b5f-11e5-8fff-ed9122aaf2f1.jpg)

**Comment by Chessnut** [comment]
The error should be gone, but the storage that's responsible for that error will disappear

**Comment by BillyNovel** [comment]
Alright, error's gone but the sh_definitions.lua won't include properly now.

**Comment by Chessnut** [comment]
Are there any other errors?

**Comment by BillyNovel** [comment]
Yep, due to the fact it's not included, storage able props are spawning in pairs and it can't be used as storages.

**Comment by Chessnut** [comment]
sh_definitions is suppose to be included unless you changed the definitions file which may lead to an error.

**Comment by BillyNovel** [comment]
I havn't modified the definitions.lua but I still have the error :O

**Comment by BillyNovel** [comment]
Tried everything, sh_definitions is definitely not including properly.
