### ISSUE TITLE
ITEM.replacements

### ISSUE THREAD

**Issue by fulltimehobo** [Chessnut/NutScript#598]
how do I use 
ITEM.replacements = {
    {"male", "female"},
    {"group01", "group02"}
}
and if I use ITEM.replacement = {"model_name"}
I get 
[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_character.lua:238: bad argument #1 to 'SetModel' (string expected, got table)
1. SetModel - [C]:-1
   1. setModel - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:238
   2. onRun - gamemodes/nutscript/gamemode/items/base/sh_pacoutfit.lua:170
      1. unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:655
      2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
      3. unknown - lua/includes/extensions/net.lua:32

**Comment by Chessnut** [comment]
You can't just use a table with one string in it. To set the model to a
specific one, just use ITEM.replacement = "blah.mdl"

**Comment by fulltimehobo** [comment]
How would I do it then to do specifics

**Comment by Chessnut** [comment]
I just told you.
