### ISSUE TITLE
[ BUG? ] Weapons regain Ammo

### ISSUE THREAD

**Issue by LukeCall** [Chessnut/NutScript#600]
I have noticed that upon equipping then wasting your ammo, you can just unequip and then equip the weapon again to get more ammo. I assume this is a bug as weapons are meant to maintain ammo when dropped, lose ammo and require new ammo from the inventory, etc. I dont believe I have edited anything to cause this myself. I never really noticed it before ( it may of happened I just didnt notice ). I did add the M9K addons to the Server though before I officially noticed it.

**Comment by Zenolisk** [comment]
Set the SWEP.Primary.DefaultClip to 0 for your weapons.

**Comment by LukeCall** [comment]
That would include editing the files for Half Life 2 Weapons as well though, which I would not be looking forward to. Is there an easier way or a better place to put it so all weapons follow that?
