### ISSUE TITLE
Can someone just send me the code to citizen VCs

### ISSUE THREAD

**Issue by maxyii** [Chessnut/NutScript#604]
nut.voice.defineClass("citizen", function(client)
    return client:getChar():hasFlags("y")

end)

Why doesn't this work?

**Comment by Chessnut** [comment]
Did you give yourself the y flag?

**Comment by maxyii** [comment]
yes.

This is the code for the VC:

nut.voice.register("citizen", "ammo1", "I need ammo!", "vo/npc/male01/ammo01.wav")

But nothing is happening when I say ammo1
