### ISSUE TITLE
T-Posing Player Models

### ISSUE THREAD

**Issue by HoboHorse** [Chessnut/NutScript#607]
Made a new schema, factions, items... Everything going fine, tried starting up the server everything worked, get onto to server and try to use the player models.. Instantly it broke, t posing models.

Best I've got to was Add nut.anim.SetModelClass("player", model) and I'm clueless on how to use it, if anyone has some extra time to help, I would respect it.

**Comment by LukeCall** [comment]
Currently cannot reference my own to explain it in detail apart from: make a folder in your schema's to plugins folder and call it for example "tposefix" and inside it make a file called "sh_plugin.lua" and put that code you were unsure about in it along with required plugin details.

Will explain in more detail if needed when home.
