### ISSUE TITLE
Quick Menu Font Error?

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#609]
Wasnt there a cog-wheel and checkboxes instead of `and F ?

![2015-09-07_00001](https://cloud.githubusercontent.com/assets/2505044/9720064/f0ef090e-558a-11e5-9e66-c0221f08f385.jpg)

**Comment by Chessnut** [comment]
Fonts in Workshop add-ons don't mount so you're going to need to add it to
your server's downloads.
