### ISSUE TITLE
Playermodels T-Posing, Again.

### ISSUE THREAD

**Issue by Benji42069** [Chessnut/NutScript#611]
Alright, So i posted about this happening earlier, and it still continues to occur.  I have my playermodels T-Posing still.  Ive done
nut.anim.setModelClass("vort", "models/jessev92/soldier_vietnam/us01.mdl")
ive done vort, citizen_male, metrocop, and citizen female.  I dont know what to do now, But this is a link to the playermodel/npc pack.
http://steamcommunity.com/sharedfiles/filedetails/?id=400601790
The playermodels have been tposing for a while.  And i have no clue wut its doing.

**Comment by Chessnut** [comment]
Don't make a GitHub issue if this isn't an issue with the actual framework itself. Since it's a **player** model, try setting the model class to **player**.

Keep issues you're having with customization to the forums.
