### ISSUE TITLE
Character Loading Bug (HL2RP Schema)

### ISSUE THREAD

**Issue by MuckerMayhem** [Chessnut/NutScript#612]
NutScript and the schema are set up accordingly, using the sqlite database and it loads fine from what I can tell. I've made a character, but every time I press "load" the "return" button appears in a giant list down the left hand side and the model becomes completely green for whatever eason. This error spams in the console: 

```
[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_character.lua:395: attempt to index field 'data' (a nil value)
  1. SetupCharacter - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:395
   2. SetupCharList - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:432
    3. callback - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:448
     4. OnEnd - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:134
      5. unknown - lua/includes/extensions/client/panel/animation.lua:48
```

Any ideas? The server is running on my machine, I've done plenty of searching around and haven't found anything regarding this error specifically.

**Comment by MuckerMayhem** [comment]
Seems I fixed this myself by rolling back the cl_character file two changes, works as it should now - though not exactly a 'fix'.

**Comment by antonpersson99** [comment]
I also have this problem, but I couldn't find a rollback. Could you link me?

**Comment by MuckerMayhem** [comment]
Try this https://github.com/Chessnut/NutScript/commit/b80ba79807c69a392ccaabe9c91f3ef1d7b819ea

**Comment by ghost** [comment]
I have the same problem and at my case it didn´t helped. Any other ideas?

Changed : 

Tried it again and it worked. Thanks Cole.
