### ISSUE TITLE
Radio Issue 

### ISSUE THREAD

**Issue by IamBrett** [Chessnut/NutScript#627]
[ERROR] gamemodes/westfrontww2/plugins/radio/sh_plugin.lua:73: attempt to call field 'Register' (a nil value)
1. unknown - gamemodes/westfrontww2/plugins/radio/sh_plugin.lua:73
   1. include - [C]:-1
   2. include - gamemodes/nutscript/gamemode/core/sh_util.lua:17
      1. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
      2. loadFromDir - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:175
      3. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:166
      4. unknown - gamemodes/nutscript/gamemode/shared.lua:65

**Comment by Chessnut** [comment]
Don't use 1.0 stuff with 1.1
