### ISSUE TITLE
Date Error

### ISSUE THREAD

**Issue by IamBrett** [Chessnut/NutScript#628]
[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45: attempt to perform arithmetic on a nil value
1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45
   1. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
   2. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
      1. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
      2. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

**Comment by Chessnut** [comment]
Probably related to your other issue #627

**Comment by LukeCall** [comment]
I can say that I have something similar with the Date, if you change it when the Server has already been up a while with characters made it will throw an error.

**Comment by LukeCall** [comment]
I have had\* should I say.
