### ISSUE TITLE
Punching when shooting weapons

### ISSUE THREAD

**Issue by SummiTrf** [Chessnut/NutScript#629]
So I'm using nutscript as a base for a serious rp server and some of the star wars weapons I have installed are doing a punching animation whilst shooting. Theres also this error in the console 

[ERROR] gamemodes/nutscript/gamemode/items/base/sh_weapons.lua:174: attempt to index a nil value
1. fn - gamemodes/nutscript/gamemode/items/base/sh_weapons.lua:174
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
   2. Kill - [C]:-1
      1. Call - gamemodes/base/gamemode/player.lua:369
      2. unknown - gamemodes/base/gamemode/player.lua:480

Which I'm fairly sure is the reason for this but I have no clue on how to fix it.

sh_weapons code: http://hastebin.com/payofipido.js

Halp plz

**Comment by cornpop37** [comment]
Its the weapons itself, it isnt the gamemode. I've had this problem before I just changed the playermodel or the weapons.
