### ISSUE TITLE
Couldn't include file

### ISSUE THREAD

**Issue by TheSkullHead** [Chessnut/NutScript#630]
I'm getting the error:
https://gyazo.com/bfa2afa03e7a3ba9e42dea49da2e1c65
Which says that it's missing a file in the core.
What can i do?
EDIT: It's not working for me as a whole. The only button that shows up for me is Leave, the plugins aren't working, there's files missing from the base nutscript folder..

**Comment by TheSkullHead** [comment]
EDIT: It's not working for me as a whole. The only button that shows up for me is Leave, the plugins aren't working, there's files missing from the base nutscript folder..

**Comment by cornpop37** [comment]
I would recommend a fresh install of Nutscript base and HL2RP and try it with no plugins.

**Comment by TheSkullHead** [comment]
I've found the solution:
Apparently my server was thinking it should start Nutscript instead of HL2RP, while the start.bat clearly states: +gamemode hl2rp.
I added 'gamemode hl2rp' without the quotes to my server.cfg, which fixed my issue.
Basically, it was starting nutscript, so no shit it couldn't find the plugins :stuck_out_tongue_winking_eye:
