### ISSUE TITLE
Cant create characters of some factions.

### ISSUE THREAD

**Issue by AngelPlays** [Chessnut/NutScript#632]
I'm having an issue where some factions I've created in my schema work just fine but others that are created the exact same don't work at all. 
Here are some of the working factions:

Named: sh_501st.lua
FACTION.name = "501st Troopers"
FACTION.desc = "501st Troopers"
FACTION.color = Color(0,0,255)
FACTION.isDefault = false
FACTION.models = {
    "models/player/501st/c501st.mdl"
}

Named: sh_Cadet.lua
FACTION.name = "Clone Troopers"
FACTION.desc = "New Clone Troopers"
FACTION.color = Color(255,153,204)
FACTION.models = {
    "models/player/testc/cgi cadet.mdl"
}

Now some non working ones:
Named: sh_Security.lua
FACTION.name = "Security Troopers"
FACTION.desc = "Security Troopers"
FACTION.color = Color(0,0,255)
FACTION.isDefault = false
FACTION.models = {
    "models/player/cguard/cgi cguard.mdl"
}

Named sh_Pilot.lua
FACTION.name = "Clone Pilots"
FACTION.desc = "Clone Pilots"
FACTION.color = Color(255,255,153)
FACTION.isDefault = false
FACTION.models = {
    "models/player/testctp/clonepilot.mdl"
}
I already deleted sv_db so thats not the issue.

**Comment by Chessnut** [comment]
Did you whitelist yourself? And this is for NutScript issues, not customization issues.
