### ISSUE TITLE
Setting custom (TnB) models causes constant stuttering

### ISSUE THREAD

**Issue by aumkarpraja** [Chessnut/NutScript#633]
I will provide info as needed but this issue is happening whenever any custom model is set via the /charsetmodel command. HL2 models don't have this issue and no lua errors / serverside errors are seen. Not sure what to do in this regard.

**Comment by Thadah** [comment]
It probably has something to do with issue #562

**Comment by aumkarpraja** [comment]
Yeah, the legs plugin was at fault. Issue resolved although the legs really should be fixed.
