### ISSUE TITLE
CP Faction keeps breaking.

### ISSUE THREAD

**Issue by TheTwelfthDoctor** [Chessnut/NutScript#634]
No idea why or what I did but every single time I go to create a character on my Stormtrooper faction I get this: 

[ERROR] gamemodes/galactic/schema/factions/sh_metropolice.lua:12: attempt to compare number with nil
1. Run - gamemodes/galactic/schema/factions/sh_metropolice.lua:12
   1. onPostSetup - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:202
   2. setUp - gamemodes/nutscript/gamemode/core/derma/cl_charcreate.lua:78
      1. callback - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:194
      2. DoClick - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:111
      3. unknown - gamemodes/nutscript/gamemode/core/derma/cl_menubutton.lua:52

and I can't create my character, the character creator box never appears.

Now I can't quite figure out what I did wrong as this is the code for the faction thus far:

FACTION.name = "Galactic Empire Stormtroopers"
FACTION.desc = "Your enlisted."
FACTION.color = Color(25, 30, 180)
FACTION.isDefault = false
FACTION.models = {
    "models/nate159/swbf2015/playermodels/stormtrooper.mdl",
    "models/sgg/starwars/stormtrooper_color.mdl"
}
FACTION.weapons = {"nut_stunstick"}
FACTION.pay = 25
FACTION.isGloballyRecognized = true

function FACTION:onGetDefaultName(client)
    if (SCHEMA.digitsLen >= 1) then
        local digits = math.random(tonumber("1"..string.rep("0", SCHEMA.digitsLen-1)), tonumber(string.rep("9", SCHEMA.digitsLen)))
        return SCHEMA.cpPrefix..table.GetFirstValue(SCHEMA.rctRanks).."."..digits, true
    else
        return SCHEMA.cpPrefix..table.GetFirstValue(SCHEMA.rctRanks), true
    end
end

FACTION_CP = FACTION.index

If anyone could help that would be greatly appreciated. I know I'm doing _something_ wrong, I just can't figure out _what_ I'm doing wrong.

**Comment by Rubberbandits** [comment]
SCHEMA.digitsLen

is that actually defined? thing is line 12 looks like the function name to me, but the if statement could be line 12.

**Comment by TheTwelfthDoctor** [comment]
For whatever reason the code works if I completely reset my server and Nutscript. If I try to change the schema color or whatever, it instantly breaks and I have to completely reset the server again.

**Comment by Thadah** [comment]
SCHEMA.digitsLen is defined in sh.config.lua, in line 62
