### ISSUE TITLE
[Suggestion] Player is incapacitated/unconscious when HP is low

### ISSUE THREAD

**Issue by Wibble606** [Chessnut/NutScript#636]
Would it be possible to have players /fallover when their HP drops below a certain number? It would be good for Military RP.

**Comment by Chessnut** [comment]
Yes

**Comment by Wibble606** [comment]
Do you know how to go about coding something like that? I have no idea where to start...

**Comment by Rubberbandits** [comment]
if (client:Health() <= <num>) then 
     client:setRagdolled(true, 25) 
end
