### ISSUE TITLE
Game-mode won't show up in the server listing?

### ISSUE THREAD

**Issue by daxxom** [Chessnut/NutScript#638]
I've gone ahead and used the HL2 schema for nutscript and renamed the folder and the hl2.txt to a different name to attempt to make it show up in a different tab in the sever browser as a test. It's not showing up in the listing and will only show up when I set the folder and .txt back to it's original name.

I suppose what i'm asking is could some one explain to me why it doesn't show up as a different schema? And what would I need to do to ensure that it shows up outside of the HL2 tab?

Thanks.

**Comment by Aberidius** [comment]
You must edit the txt file aswell, not just rename the file.

**Comment by daxxom** [comment]
"sample"
{
    "base"      "nutscript"
    "title"     "HL2 RP"
    "author"    "Chessnut"
    "menusystem"    "1"
}

So if it looks like that, i'd edit the "sample" at the top and the "title" or just the "title" "HL2 RP"?

**Comment by Aberidius** [comment]
same should be the same as the txt files name and the folders name.

title should be the title for the gamemode, the one you want listed.

**Comment by daxxom** [comment]
Wait wait, I think i'm understanding a little better. So i'd edit --> "title" <--  not "HL2 RP"?

**Comment by Aberidius** [comment]
No, edit "HL2 RP"

**Comment by daxxom** [comment]
Let me try this really quickly. (Thanks for the response by the way, this is invaluable.)

**Comment by daxxom** [comment]
Not showing up. Does "sample" at the top need to be renamed to the txt file name and the folder name?

What prevented the server from attempting to launch was renaming the "HL2 RP"

**Comment by Aberidius** [comment]
Change "sample" to your gamemodes name. also, theres a file called sh_schema.lua that has a line saying:

SCHEMA.name = "HL2 RP"   change that aswell!

**Comment by daxxom** [comment]
Aha! That did the trick! thank you so much! I'm new to NS and am going through a trial by fire at the moment. I really appreciate the support!

**Comment by Aberidius** [comment]
No worries bud, glad i could help out :)

**Comment by daxxom** [comment]
Erm, One more issue that i've just found out... I can connect directly via console, But don't actually see the server in any listed tab in the server browser. Any idea?
