### ISSUE TITLE
Voices doesnt play

### ISSUE THREAD

**Issue by Aberidius** [Chessnut/NutScript#639]
Hi, i tried adding voices and changed the faction to "Helghast" instead of combine but it doesn't play any voice. Heres my code:

nut.voice.defineClass("Helghast", function(client)
    return SCHEMA:isHelghastFaction(client)
end)

-- What type of chat modes support voice commands:
nut.voice.chatTypes["ic"] = true
nut.voice.chatTypes["w"] = true
nut.voice.chatTypes["y"] = true
nut.voice.chatTypes["radio"] = true
--[[

-- Example of citizen class that requires the ciitzen to have 'y' flag.
nut.voice.defineClass("citizen", function(client)
    return client:getChar():hasFlags("y")

end)
--]]

nut.voice.register("helghast", "attack", "Attack!", "sound/attack.wav")
nut.voice.register("helghast", "crush you", "I will crush you.", "crush_u.wav")

**Comment by Chessnut** [comment]
Check the console to see if you're missing sounds.

**Comment by Aberidius** [comment]
Aye, it's printing this error:
Failed to load sound "helghast\attack.wav", file probably missing from disk/repository

I changed the voice command line to

nut.voice.register("helghast", "attack", "Attack!", "sound/attack.wav")

Any clue what's going on?

**Comment by Chessnut** [comment]
Means you are missing the sound file.

Also, try removing the sound/ in the front.

**Comment by Aberidius** [comment]
Thats the thing, i already removed the sound/  and i have the sound filea on client and server side

**Comment by Chessnut** [comment]
Running `play sound.wav` should work then if you do have the sound.

**Comment by Aberidius** [comment]
Could it possible be better if i made a plugin of it and add a sound folder in there?

**Comment by Chessnut** [comment]
No
