### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by cornpop37** [Chessnut/NutScript#640]
Is there anyway to reload the Gamemode without changing map or restarting the server?

**Comment by Chessnut** [comment]
Should work automatically if your server uses Windows.

**Comment by Myaats** [comment]
I believe Linux Lua Refresh was added in one of the latest updates also.

**Comment by Thadah** [comment]
Confirming it was added

**Comment by Thadah** [comment]
Confirming, taken from https://wiki.garrysmod.com/page/Auto_Refresh

> As of the August 11 update Autorefresh is now available on Linux servers

If it doesn't work by default, add -withjit to your startup script
