### ISSUE TITLE
Remove weapon switcher

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#643]
Where can I find the code to remove the weapon selector/switcher thing when pressing "1", "2" "3" and so on? 

For the addons I'm currently running, the weapon selector/switcher thing is bugged with the addons thus making it hard to use.

**Comment by ghost** [comment]
I've found it here

```
        elseif (bind:find("slot")) then
            self.index = math.Clamp(tonumber(bind:match("slot(%d)")) or 1, 1, #LocalPlayer():GetWeapons())
            self:onIndexChanged()

            return true
```

but if I remove that, it uses the default gmod weapon selector

**Comment by Thadah** [comment]
You could try returning false instead of returning true and see if it works

**Comment by ghost** [comment]
I'll try that in a few, just a bit busy.
