### ISSUE TITLE
Error in the character load menu

### ISSUE THREAD

**Issue by Beaver420** [Chessnut/NutScript#645]
Whenever I join a nutscript server running 1.1, I get this error message. No one else gets it and I've tried many things such as reinstalling Garry Mod and verifying the cache. This error makes the Load screen unusable, filling the screen with "Return" buttons.

[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_modelpanel.lua:13: attempt to index local 'entity' (a nil value)
1. SetModel - gamemodes/nutscript/gamemode/core/derma/cl_modelpanel.lua:13
   1. SetupCharacter - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:392
   2. SetupCharList - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:425
      1. callback - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:441
      2. OnEnd - gamemodes/nutscript/gamemode/core/derma/cl_character.lua:134
      3. unknown - lua/includes/extensions/client/panel/animation.lua:48

**Comment by Thadah** [comment]
It must be one of your Workshop addons the one that causes the problem
