### ISSUE TITLE
People dont invis when in noclip now :/

### ISSUE THREAD

**Issue by SummiTrf** [Chessnut/NutScript#648]
People dont invis when in noclip now I press v I go invis for a second then it goes back to showing me ? Its just randomly started to do it

**Comment by Chessnut** [comment]
Did you install any add-ons recently?

**Comment by SummiTrf** [comment]
https://steamcommunity.com/workshop/filedetails/?id=565028748 thats all the addons from workshop we have

**Comment by Thadah** [comment]
Maybe the No Collide Everything addon is causing it

**Comment by SummiTrf** [comment]
It cant be that, we've had it before the invis stopped working and it hasnt been updated for 3 years

**Comment by Thadah** [comment]
It's difficult to know which addon can cause it. I would suggest testing without any addons and if it works start testing addon per addon which causes the problem.

If removing all the addons doesn't fix the issue, replace the observer plugin with NutScript's last one.
