### ISSUE TITLE
Craft plugin /craftmenu command not working

### ISSUE THREAD

**Issue by overki11** [Chessnut/NutScript#649]
Not sure if this is the exact right place to put this, but the /craftmenu command on modernrp isn't working. I realize I'm probably doing something stupid, but whenever I type /craftmenu it doesn't do anything. It just says in the console "-name- used "/craftmenu"

**Comment by Thadah** [comment]
I think ModernRP is pretty outdated by now. Anyways the /craftmenu was never implemented, as that crafting plugin was made only partially, see what the code says in that command:

```
nut.command.add("craftmenu", {
    onRun = function(client, arguments)
        -- Will open craft menu
    end
})
```
