### ISSUE TITLE
Why doesn't load m9k weaphon

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#650]
i just input pluggin file (m9k plugin)
and + addon file, but error message
[NutScript] Item 'm9k_299r' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_73winchester' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_acr' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_ak47' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_ak74' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_amd65' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_auga3' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_colt1911' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_deagle' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_f2000' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_fal' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_famas' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_g36' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_g3a3' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_glock' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_hk45' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_l85' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_m4a1' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_m92' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_scar' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_tar21' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_usp' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_val' has a non-existent base! (base_weapon)
[NutScript] Item 'm9k_vikhr' has a non-existent base! (base_weapon)

i can't equip.

**Comment by overki11** [comment]
Because it has a non-existent base. M9K is derived from a base, bobs_gun_base. Look through the plugin and try and change base_weapon to that.

**Comment by ghost** [comment]
there is no base_weapon in my plugin.. what should i do?
