### ISSUE TITLE
Player Models in T-Pose and cant figure out what's causing it

### ISSUE THREAD

**Issue by ChazNN** [Chessnut/NutScript#651]
Ive tried using the nut.anim.setModelClass fix but it hasnt fixed any of the models. Ive tried setting it to both citizen_male and metrocop and so far neither have worked. Ive tried different animations, i tried swapping the model and animation in the code i tried capitalizing Set (Because I kept seeing people capitalize it in old posts) and I also tried placing it in a Plugin, sh_schema and I even resorted to trying to put it in each of the different factions. 

Im still sorta noobish to NS so with my luck its something really simple that im missing but so far I havnt been able to find much help on fixing it. Just people asking about it and then saying "Okay I fixed it" and not mentioning how they did so.

I have had it in my code as all of these each separately tried in three different files, sh_schema, a plugin and in the faction files. 

nut.anim.SetModelClass("models/player/pmc_3/pmc__05.mdl", "metrocop")
nut.anim.SetModelClass("models/player/pmc_3/pmc__07.mdl", "metrocop")
nut.anim.SetModelClass("models/player/pmc_3/pmc__03.mdl", "metrocop")
nut.anim.SetModelClass("models/player/pmc_5/pmc__01.mdl", "metrocop")

and

nut.anim.setModelClass("models/player/pmc_3/pmc__05.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_3/pmc__07.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_3/pmc__03.mdl", "metrocop")
nut.anim.setModelClass("models/player/pmc_5/pmc__01.mdl", "metrocop")

and

nut.anim.setModelClass("metrocop", "models/player/pmc_3/pmc__05.mdl")
nut.anim.setModelClass("metrocop", "models/player/pmc_3/pmc__05.mdl")
nut.anim.setModelClass("metrocop", "models/player/pmc_3/pmc__05.mdl")
nut.anim.setModelClass("metrocop", "models/player/pmc_3/pmc__05.mdl")

Any help would be appreciated. If needed I could probably put what ive got for the schema on github as well.

**Comment by Thadah** [comment]
Maybe you should use normal models rather than playermodels. I don't really know if playermodel animations can be overriden.

**Comment by ChazNN** [comment]
Sadly the models I wanted to use dont have regular model versions. Just
player models.

**Comment by Chessnut** [comment]
Did you try "player"?

**Comment by Boto-thing** [comment]
I and also another person I know are having this same problem. Would really appreciate it if someone could help fix this

**Comment by benmort38** [comment]
If I were to try and fix t-posing for a model, where would I put

nut.anim.SetModelClass("models/tfa/comm/gg/shadow_atin.mdl", "player")

Would I simply make a notepad named tposefix.lua and put it in plugins, or?

**Comment by benmort38** [comment]
I attempted to do the above and got an error saying unknown "SetModelClass" something null

**Comment by Thadah** [comment]
It's setModelClass not SetModelClass
