### ISSUE TITLE
Couldn't find medievalrp/schema/sh_schema.lua

### ISSUE THREAD

**Issue by TheSkullHead** [Chessnut/NutScript#655]
So, whenever I start up my MedievalRP server (MedievalRP built off of the sample schema) I get a few errors. These errors are:
--Startup--
https://gyazo.com/acaec07178f982003d9f898353544712
--Player Joins--
https://gyazo.com/6e11232c59abc2eb28486d2e2b6c76a8
--Info--
So, I have all the files they say are missing. But it STILL doesn't want to work. 
Aaaaaaaany help?

**Comment by TheSkullHead** [comment]
I also cannot create a character.

**Comment by Chessnut** [comment]
This is for NutScript issues, not technical support.

Also notice how there's another error above? Don't use 1.0 code with 1.1
