### ISSUE TITLE
Weapon Toggle

### ISSUE THREAD

**Issue by MikeMurphy247** [Chessnut/NutScript#657]
I am having issues finding the weapon toggle file in the script? 
Could you let me know where I can find it please?
Working on a WW2 RP server and dont want to launch it until this issue is fixed?

**Comment by DefenderVex** [comment]
You can hold down reload to lower and raise your weapon.
The code itself is too deeply embedded to easily remove.

However you can use the 'wepAlwaysRaised' option in the
configuration menu to make it so they are always raised.

**Comment by Chessnut** [comment]
boolean ShouldWeaponBeRaised(client, weapon)

**Comment by khh544** [comment]
hey chessnut your email please
I want to talk to you

inquiry:)

pig4396@naver.com
send your email
