### ISSUE TITLE
Scoreboard + Health Bar Issue

### ISSUE THREAD

**Issue by dragnort1** [Chessnut/NutScript#660]
Scoreboard is displaying skeletons and unknown for names, yes it's been addressed before but there is no fix or a way to remove this. I don't want this to do this. Also, the health bar at the bottom left of the screen is black and flashing and there is a small white box next to it that changes colour when you look around.
 What I'm asking:
1. If you can help me with the scoreboard issue, that is the most urgent.
2. Health Bar isn't that much of an issue just wanted to know if there was a fix.
   Thanks.

**Comment by Thadah** [comment]
Are you using NutScript 1.0? Beause the bars at the bottom left are something from NS1.0, which is not getting support anymore

**Comment by dragnort1** [comment]
I don't care about the bars at the bottom that much all I care for is the leaderboard

**Comment by Thadah** [comment]
What I'm telling you is that you should update your servers to NutScript 1.1 as 1.0 is very old and its use is not recommended

**Comment by dragnort1** [comment]
Yes well we're sticking with NS 1.0 as NS 1.1 changes too much visual and most commands. Unless there is confirmed to be no fix for the scoreboard that is when we will most likely change.
Also it affects most of our server content and the toolgun.

**Comment by Thadah** [comment]
The scoreboard thing you are talking about is the recognition plugin, and I think there is a Config to disable the skeleton stuff.

The bars issue I know it's been addressed before but no fix has been made as everyone has changed to 1.1

I thoroughly recommend you to upgrade to NutScript 1.1 as it fixes lots of problems you may have with 1.0

**Comment by dragnort1** [comment]
Do you have any idea where I can find this option for the skeletons?

**Comment by Thadah** [comment]
I think there's no config option itself but you can change gamemode/derma/cl_scoreboard.lua, the `SetPlayer()` function to look like this:

```
function PANEL:SetPlayer(client)
        self.player = client

        self.model:SetModel(client:GetModel(), client:GetSkin())
        self.model:SetToolTip("Click to open "..client:RealName().."'s Steam profile.")

        self.name:SetText(client:Name())
        self.name:SizeToContents()

        local description = client.character:GetVar("description")

        if (description) then
            self.desc:SetText(description)
        end
    end
```

That will make everyone visible and recognized in the scoreboard

**Comment by dragnort1** [comment]
Fixed
