### ISSUE TITLE
Chat Distance does not measure up and down.

### ISSUE THREAD

**Issue by CaptJack92a** [Chessnut/NutScript#671]
When on a multilayered map, the chat distance seems to have infinite distance if the players are above or ubelow one another. No matter how far down you are, you can hear someone who is a long ways above you.

**Comment by dilbysama** [comment]
Pretty sure you can fix this by replacing this line in core/libs/sh_chatbox.lua:
`return (speaker:GetPos() - listener:GetPos()):Length2DSqr() <= range`

With this:
`return (speaker:GetPos() - listener:GetPos()):LengthSqr() <= range`

Length2DSqr only takes x(front/back) and y(left/right) into account, whereas LengthSqr takes x y AND z (up/down) into account.
