### ISSUE TITLE
Can't type into text boxes, text boxes name coming up differently, config blank

### ISSUE THREAD

**Issue by virtualFear** [Chessnut/NutScript#676]
Hi all,

An issue just came up on my server recently which I'm not quite sure how to go about. Text boxes on the server are coming up blank despite there being stuff in them (on server config, typing into a box brings up a notification that it's been changed but it's still blank), players can't type into the blank text boxes (tested on character creation and chardesc) and the fields in text boxes comes up differently (/chardesc comes up as "chgDesc" and "chgDescDesc", screenshot [here.](http://steamcommunity.com/sharedfiles/filedetails/?id=675480740) 

While I'm here, I was having an issue where when I altered the config it would change back straight away (tried to change chat distance and the server music, both changed back almost straight away and no changes carried), although that's much less important. 

Thanks in advance

**Comment by Rubberbandits** [comment]
you're fucked gmod update broke the entire gamemode. chessnut is no where
to be seen so do not count on an update.

**Comment by GoproMgH** [comment]
not true hes just a busy man and the gamemode is still working for me

**Comment by lyxara** [comment]
Try adding a SetZPos to the textEntry. The text seems to have been written behind the panel.
If this doesn't work, try changing the font and size of the text to default.

**Comment by benmort38** [comment]
Could you give an example code?

**Comment by lyxara** [comment]
Of course. That's an example using the gamemode/core/derma/cl_business.lua file.
If you modified something from that file, be aware to backup it.

```
self:SetZPos(1)

self.search = self:Add("DTextEntry")
self.search:Dock(TOP)
self.search:SetTall(36)
self.search:SetFont("nutMediumFont")
self.search:DockMargin(10 + self:GetWide() * 0.35, 0, 5, 5)
self.search:SetZPos(2)
```

Lower values of ZPos will appear behind higher ones.

If the code above doesn't work, change the font like:

```
self.search = self:Add("DTextEntry")
self.search:Dock(TOP)
self.search:SetTall(36)
self.search:SetFont("Arial")
self.search:DockMargin(10 + self:GetWide() * 0.35, 0, 5, 5)
```

If it still doesn't work, comment below and when I have time I'll look it carefully.

**Comment by benmort38** [comment]
Page not found, but I'll try this out.  Thank you so much

Also I should mention that I use nutscript 1.0 because 1.1 was not working on my server

Also, seeing as this also does it to me on my ulx menu, what would the default font be?

**Comment by benmort38** [comment]
Just tried changing the font, didn't seem to fix it, I'll keep looking

**Comment by lyxara** [comment]
NS1.0 is outdated. I highly recommend you, first of all, to backup all your files. Then,  update your GarrysModDS and NutScript to the last version.

If you don't want (or you can't) to update your GmodDS and NS, give me a moment to mount all the gamemode of NS1.0 and see if it happens to me, too.

**Comment by benmort38** [comment]
I tried using nutscript 1.1 and it bugged out all the weapon holdtypes.  People would hold their guns like fists and punch whenever they shot.  Couldn't get color correction to fix properly.  I like nutscript 1.0 overall more.

**Comment by lyxara** [comment]
Okay, then. I'll try to find out the problem by mounting NS1.0 in my server.

**Comment by benmort38** [comment]
I don't know how I would go about putting that ZPos into NS 1.0, I'm somewhat new to all this.  Also ulx has the same issue now.

**Comment by benmort38** [comment]
Also if yours works please send me the link to the NS1.0 you're using

**Comment by lyxara** [comment]
I tested NS1.0 with HL2RP schema and they work perfectly to me.

![TextEntryTest1](https://cloud.githubusercontent.com/assets/8088613/15588294/6c867ebe-238d-11e6-94cd-592c3dd78174.png)

![TextEntryTest2](https://cloud.githubusercontent.com/assets/8088613/15588053/630cdc6c-238c-11e6-9ccd-221b4f65e124.png)

Ulx works, too.
![TextEntryTest3](https://cloud.githubusercontent.com/assets/8088613/15588066/78eb0d60-238c-11e6-9aa0-85de79871d04.png)

I downloaded all files from here:
HL2RP: https://github.com/Chessnut/hl2rp/archive/master.zip
NS1.0: https://github.com/Chessnut/NutScript/archive/master.zip

Remake all changes you made and be careful when doing it, you can break the gamemode as has happened to you.

EDIT: Maybe you're using an 1.1 schema with a 1.0 framework...

**Comment by benmort38** [comment]
Could it possibly be an addon? Seeing as it does it to ulx and nutscript, and I don't want to do that only to find it didn't work

**Comment by lyxara** [comment]
Which schema are you using? I see that derma and I guess that is a NS1.1 schema, but you're using a NS1.0 framework... did you copied all NS1.1 styles to NS1.0 or are you using a NS1.1 schema on a NS1.0 framework?

**Comment by benmort38** [comment]
What do you mean I'm using a NS1.1 schema? Where do you see that?

**Comment by benmort38** [comment]
I just imported that framework and everything broke.  Not sure what on earth happened there.  

Couldn't include file 'nutscript\gamemode\cl_init.lua' (File not found) (@gamemodes/starwarsrp/gamemode/cl_init.lua (line 1))

**Comment by lyxara** [comment]
As you can see in the screenshot, now I'm in a NS1.1 schema with the NS1.1 framework.

![NS11proof](https://cloud.githubusercontent.com/assets/8088613/15588819/052a49dc-2390-11e6-9710-96c786ca083a.png)

This style of frames are in NS1.1 schemas.
Download this NS1.0 schema and check if all folders matches:
https://github.com/Chessnut/hl2rp/archive/master.zip

**Comment by GoproMgH** [comment]
i have the same exact problem theres text but its invisible

**Comment by benmort38** [comment]
Oh lol yeah I'm running a 1.1 schema on the 1.0 framework

**Comment by benmort38** [comment]
Wait no I'm not even sure.  Hang on

**Comment by benmort38** [comment]
Everything is fixed, just gotta make it less depressing looking in the colors and I gotta fix the recognition.  Thank you so much

**Comment by lyxara** [comment]
I'm glad that it has been solved. ^^

**Comment by benmort38** [comment]
Ahem, I'm very embarrassed to say this but I just put those into the server and nobody can see who anyone else is above their head, and same thing with the tab menu.  "Unknown" with a skeleton

**Comment by lyxara** [comment]
This is because you added the plugin 'recognize'. In NS1.0, unrecognize people is shown as skeletons in the scoreboard. Just type /recognize staring who you want to recognize and press Enter.

If you don't want that plugin, just disable it. I remember that there was an option on Settings in the F1 menu.

**Comment by benmort38** [comment]
Apparently just removing it didn't work either.  Let me look

**Comment by benmort38** [comment]
I got it to work sort of.  You can see the player's name in game.  

However, if you are looking at the tab list, any new player, even when their class is changed, stays as unknown.  I didn't see a disable setting in f1

**Comment by benmort38** [comment]
I'm gonna try and just remove it altogether and see if that breaks anything.  Hold tight

**Comment by benmort38** [comment]
Yeah no, not working

**Comment by lyxara** [comment]
Don't remove code as if they were LEGO blocks xD

Just change that function:

```
function PLUGIN:IsPlayerRecognized(client)
    if (client == LocalPlayer()) then
        return true
    end

    local localPlayer = LocalPlayer()
    if (IsValid(localPlayer) and localPlayer.character) then
        local recognized = localPlayer.character:GetData("recog", {})
        if (recognized[client.character:GetVar("id", 0)] == true) then
            return true
        end
    end
end
```

for that one:

```
function PLUGIN:IsPlayerRecognized(client)
    return true
end
```

**Comment by lyxara** [comment]
That function is in the `/plugins/recognition/sh_plugin.lua` file.

**Comment by benmort38** [comment]
I see that, how do I reverse it?

**Comment by lyxara** [comment]
If you have the .zip, just download again all files you removed. Then go to `nutscript/plugins/recognition`, open the `sh_plugin.lua` file and change the function.

**Comment by benmort38** [comment]
Right, but again, I'm a beginner at this.  Could I just remove the function?

**Comment by lyxara** [comment]
Yes, replace it. Just delete it and rewrite as said:

```
function PLUGIN:IsPlayerRecognized(client)
    return true
end
```

That will make everybody recognize each other.

**Comment by lyxara** [comment]
Uh... I forgot that NS1.0 has too high coupling... there is a hook that doesn't work properly in clientside... maybe in the scoreboard derma... sorry...

I'm going to look for the file where is the 'if clause' that makes the difference between being recognized or not...

**Comment by benmort38** [comment]
Yeah, thank you.  I can't wait to hear back

**Comment by lyxara** [comment]
Forgot what I said...

You can do it by editing the function... as you can see on these images.

Changing the return value to 'false':

```
function PLUGIN:IsPlayerRecognized(client)
    return false
end
```

In this case, even you won't recognize yourself, because to all cases, code won't show your real name and description.
![false](https://cloud.githubusercontent.com/assets/8088613/15592426/0758c558-23a4-11e6-87d1-35a57c99ddb5.jpg)

On the other hand, if you change the return value to 'true':

```
function PLUGIN:IsPlayerRecognized(client)
    return true
end
```

Everybody will recognize each other.

![true](https://cloud.githubusercontent.com/assets/8088613/15592456/5495c46a-23a4-11e6-9327-e2d8e75db4b0.jpg)

I thought that it didn't work because I tried it with bots. But a bot has no description, so... it was a misunderstanding. Sorry.

**Comment by benmort38** [comment]
Mm, alright.  one last question

**Comment by benmort38** [comment]
I'm trying to make it look less like... well.... 1945.  There is a color color correction.  I tried to remove it by just copying and pasting the code of the non-depressing stuff, where it has:

```
color["$pp_colour_brightness"] = brightness * 1
```

I put it into the bottom line inside of the gamemode>core, but instead I get a ton of script errors, which makes no sense to me.

**Comment by lyxara** [comment]
Do you mean these lines?

```
local color = {}
    color["$pp_colour_addr"] = 0
    color["$pp_colour_addg"] = 0
    color["$pp_colour_addb"] = 0
    color["$pp_colour_brightness"] = brightness * -1
    color["$pp_colour_contrast"] = 1.25
    color["$pp_colour_colour"] = math.Clamp(0.7 - color2, 0, 1)
    color["$pp_colour_mulr"] = 0
    color["$pp_colour_mulg"] = 0
    color["$pp_colour_mulb"] = 0
```

**Comment by benmort38** [comment]
Yeah.  I changed the brightness to say \* 1 on the top line and it fixed the color for a minute, so I decided to add it to the bottom line and then it broke the server...

**Comment by benmort38** [comment]
Do you have any clue how to make it colorful now or will I have to live in a depressing world?

**Comment by lyxara** [comment]
Of course it breaks... see what happens:

```
local brightness = 0.01 // In this line, you initialize and declare the brightness variable
local color2 = 0.25
local curTime = CurTime() // CurTime means 'Current Time', so curTime contains the value of 'now'.

if (nut.fadeStart and nut.fadeFinish) then
    brightness = 1 - math.TimeFraction(nut.fadeStart, nut.fadeFinish, curTime)
       // This formula means that the brightness equals 1 (the maximun value of brightness), minus the 
// time fraction of 'now' between the time that the fade starts and the time that the fade ends. 
// For example: time.TimeFraction(0,2,1) will return 0.5, that means that 1 is exactly between 0 and
// 2. time.TimeFraction(1,3,2) will return 0.5, too; time.TimeFraction(0,10,10) will return 1, and so on.
// That means that "brightness" will change progressively as time passes until it become 0 (means 'no change').

    if (curTime > nut.fadeFinish) then
        nut.fadeStart = nil
        nut.fadeFinish = nil
    end
end

if (nut.fadeColorStart and nut.fadeColorFinish) then
    color2 = (1 - math.TimeFraction(nut.fadeColorStart, nut.fadeColorFinish, curTime)) * 0.7

    if (curTime > nut.fadeColorFinish) then
        nut.fadeColorStart = nil
        nut.fadeColorFinish = nil
    end
end

local color = {}
color["$pp_colour_addr"] = 0
color["$pp_colour_addg"] = 0
color["$pp_colour_addb"] = 0
color["$pp_colour_brightness"] = brightness * -1 // That value become a negative number.
color["$pp_colour_contrast"] = 1.25
color["$pp_colour_colour"] = math.Clamp(0.7 - color2, 0, 1)
color["$pp_colour_mulr"] = 0
color["$pp_colour_mulg"] = 0
color["$pp_colour_mulb"] = 0

hook.Run("ModifyColorCorrection", color)

DrawColorModify(color) // And finally, that function will change the color on your screen using the 
// values in the color table. So, if you start in brightness = -1 (brightness = 1 - 0 -> 
// brightness = brightness * -1), you'll have a dark window, because brightness is a value between -1 
// and 1, meaning -1 the darkest and 1 the brightest. As time passes, negative brightness will 
// progressively been reduced until the TimeFraction returns 1, so that means that brightness = 1 - 1 
// -> brightness = 0 -> brightness = 0*-1 -> brightness = 0, so the window will have a normal 
// brightness.
```

This function is called every time.

If you want to change the style of the whole gamemode, you have to edit the `nut.config.sadColors` value to 'false', and then you'll have a normal brightness.

If you want a brightest GUI... then you must change the `/nutscript/vignette.png` file.

**Comment by lyxara** [comment]
You can try to edit the `HUDPaint()` function by yourself to adjust the interface to your likes, but if you don't know how derma works, I don't recommend you do that.

**Comment by benmort38** [comment]
where is the nut.config.sadColors located?

**Comment by benmort38** [comment]
Ah, sweet, I got it working.

**Comment by benmort38** [comment]
Also I found one issue with your schema.  All of my guns do like 500 damage.  What on earth is wrong with the damage multiplier lol

**Comment by lyxara** [comment]
Do you mean this function?

```

function GM:ScalePlayerDamage(client, hitGroup, damageInfo)
    if (hitGroup < 2 and damageInfo:IsBulletDamage()) then
        damageInfo:ScaleDamage(10)
    elseif (limbs[hitGroup]) then
        damageInfo:ScaleDamage(0.75)
    end
end
```

**Comment by benmort38** [comment]
Yes, where is that!

**Comment by benmort38** [comment]
What file is that under? I can't find it

**Comment by lyxara** [comment]
/gamemode/core/sv_hooks.lua

**Comment by benmort38** [comment]
Thank you so much for all the help Cyumus.  I am in your debt.

**Comment by lyxara** [comment]
My pleasure helping you. ^^

**Comment by benmort38** [comment]
Wait where is the nut.config.sadColors located?

**Comment by lyxara** [comment]
/gamemode/sh_config.lua:135

**Comment by benmort38** [comment]
set it to true or false?

**Comment by benmort38** [comment]
I've got it set to false and it didn't seem to be making it cheerful, hang on

**Comment by benmort38** [comment]
Color is all good now, but the lighting makes things almost glow, it hurts to look at

**Comment by benmort38** [comment]
Does anyone have a fix for the lighting? Map lights make it ridiculously bright, it's painful to look at.

**Comment by lyxara** [comment]
Try disabling HDR.

**Comment by benmort38** [comment]
Not sure what that is exactly.  Also, does anyone else have an issue where they stop sprinting even though they're not out of stamina?

**Comment by benmort38** [comment]
How do I disable the HDR?

**Comment by lyxara** [comment]
Sorry, I've been busy.

You can disable HDR in your video configuration menu.

I remember that the stamina didn't work properly in NS1.0 and I had to fix it on my server time ago... I don't know if somebody has fixed it... but don't count on anyone for fixing it, because this version is outdated and there is a newer version that fixes all these bugs.

**Comment by benmort38** [comment]
I'll work with it then.  Do you know how to disable/enable sh_voices in the hl2rp?

**Comment by benmort38** [comment]
Would anyone have any idea on this? I disabled the sh_voices, but I've reconfigured them and I want to enable them again, problem is I forget how to.

**Comment by benmort38** [comment]
Bump

**Comment by benmort38** [comment]
I know this has gone way off track from the title.  I fixed all my issues, except now I've got a random error that appeared on its own, and it's done this three times now.  I just did a fresh re-install and it still does it.

[ERROR] gamemodes/nutscript/gamemode/libs/external/sh_von.lua:131: vON: Malformed data... Can't find a proper type definition. Char#2:1
1. error - [C]:-1
   1. d_findVariable - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:131
   2. unknown - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:198
      1. d_findVariable - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:76
      2. deserialize - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:198
      3. ReadTable - gamemodes/nutscript/gamemode/sh_util.lua:271
      4. unknown - gamemodes/nutscript/gamemode/core/sh_hooks.lua:6

**Comment by benmort38** [comment]
I'm using both the files you used that worked, and the attributes bar also seems to be blank.

**Comment by benmort38** [comment]
A lot of things aren't working, and i think it comes from that error.
