### ISSUE TITLE
Gmod update broken my server

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#677]
Hello !
Someone tell me how to get rid of these errors , all the teams flew nutscript and refuse to work . More than anything, the players also cloned. What to do ?

**Comment by mobman111** [comment]
getting errors aswell, dont feel scared. the almighty chessnut will save us

**Comment by nateabowman** [comment]
What errors? I have been running my server all month and its been fine. Make sure your using 1.1, try just running a fresh copy of hl2rp and nutscript and no addons.
