### ISSUE TITLE
NS - Unknown as gm name

### ISSUE THREAD

**Issue by mobman111** [Chessnut/NutScript#678]
So my server gamemode shows up as NS - Unknown.

anything to troubleshoot this?

**Comment by nateabowman** [comment]
Works fine for me

**Comment by mobman111** [comment]
not only that, but ive used the nutscript gamemode and hl2rp raw, but still get errors, i think gmod update broke it

**Comment by mobman111** [comment]
[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[RWG™|3|STEAM_0:1:54629359] Lua Error:
Couldn't include file 'includes\modules\datastream.lua' (File not found) (@addons/playx/lua/playx/client/playx.lua (line 20))

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] addons/playx/lua/playx/client/playx.lua:20: Module not found!
1. require - [C]:-1
   1. unknown - addons/playx/lua/playx/client/playx.lua:20
   2. include - [C]:-1
      1. unknown - addons/playx/lua/autorun/client/playx_init.lua:19

[RWG™|3|STEAM_0:1:54629359] Lua Error:

[ERROR] addons/itemstore/lua/itemstore/gamemodes/darkrp25.lua:71: attempt to index global 'DarkRP' (a nil value)
1. fn - addons/itemstore/lua/itemstore/gamemodes/darkrp25.lua:71
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

[RWG™|3|STEAM_0:1:54629359] Lua Error:
Couldn't include file 'schoolrp\schema\sh_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))

[RWG™|3|STEAM_0:1:54629359] Lua Error:
Couldn't include file 'nutscript\gamemode\config\sh_config.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_character.lua:74: attempt to index global 'SCHEMA' (a nil value)
1. restore - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:74
   1. callback - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:42
   2. callback - gamemodes/nutscript/gamemode/core/libs/sv_player.lua:35
      1. query - gamemodes/nutscript/gamemode/core/libs/sv_database.lua:31
      2. loadNutData - gamemodes/nutscript/gamemode/core/libs/sv_player.lua:11
      3. unknown - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:33

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_character.lua:74: attempt to index global 'SCHEMA' (a nil value)
1. restore - gamemodes/nutscript/gamemode/core/libs/sh_character.lua:74
   1. callback - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:42
   2. callback - gamemodes/nutscript/gamemode/core/libs/sv_player.lua:35
      1. query - gamemodes/nutscript/gamemode/core/libs/sv_database.lua:31
      2. loadNutData - gamemodes/nutscript/gamemode/core/libs/sv_player.lua:11
      3. unknown - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:33

[[OX:RP] [NG:RP] [G:RP] Zonamann|6|STEAM_0:1:111437847] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

[[OX:RP] [NG:RP] [G:RP] Zonamann|6|STEAM_0:1:111437847] Lua Error:

[ERROR] gamemodes/nutscript/gamemode/core/cl_skin.lua:20: bad argument #3 to 'SetDrawColor' (number expected, got no value)
1. SetDrawColor - [C]:-1
   1. SkinHook - gamemodes/nutscript/gamemode/core/cl_skin.lua:20
   2. unknown - lua/vgui/dframe.lua:210

**Comment by lyxara** [comment]
Try to fix these errors first:

> [RWG™|3|STEAM_0:1:54629359] Lua Error:
> Couldn't include file 'schoolrp\schema\sh_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))
> 
> [RWG™|3|STEAM_0:1:54629359] Lua Error:
> Couldn't include file 'nutscript\gamemode\config\sh_config.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))

If Gmod can't find those files, the gamemode won't run correctly.
