### ISSUE TITLE
Whitelisting issue

### ISSUE THREAD

**Issue by jerodman** [Chessnut/NutScript#681]
[ERROR] gamemodes/nutscript/plugins/sh_commands.lua:14: bad argument #1 to 'SetTeam' (number expected, got string)
1. SetTeam - [C]:-1
   1. onRun - gamemodes/nutscript/plugins/sh_commands.lua:14
   2. RunCommand - gamemodes/nutscript/gamemode/libs/sh_commands.lua:54
      1. ParseCommand - gamemodes/nutscript/gamemode/libs/sh_commands.lua:137
      2. Process - gamemodes/nutscript/gamemode/libs/sh_chatbox.lua:391
      3. Run - gamemodes/nutscript/gamemode/core/sv_hooks.lua:229
      4. unknown - gamemodes/nutscript/plugins/chatbox/sh_chatbox.lua:324
         1. func - gamemodes/nutscript/gamemode/libs/external/sh_netstream.lua:119
         2. unknown - lua/includes/extensions/net.lua:32

**Comment by lyxara** [comment]
As the error message says, you have to send a number as parameter to the 'SetTeam' function, not a string.
That number represents the ID number of the faction. You can get the faction ID by indexing its name on the 'nut.faction.teams' table:

```
local factionname = "Civil Protection"
local id = nut.faction.teams[factionname]
```

If you don't type correctly the factionname you won't get the id, so you can get the id by iterating the nut.faction.indices in a for-each structure and see if the string that the user has typed matches with the name of each existing faction:

```
local id
for _, v in ipairs(nut.faction.indices) do
  if (nut.util.stringMatches(v.name, factionname)) then
    id = v.index
    break
  end
end
```

Then, use that id as the parameter on the 'SetTeam' function.

EDIT: I forgot that some faction names are just keywords for language utilities... so you have to use the `L(string)` function to get the real name in the right language.
