### ISSUE TITLE
Faction Health

### ISSUE THREAD

**Issue by PaXo0** [Chessnut/NutScript#688]
I have been trying to make certern factions spawn with health but i can't find a way to make it work please help asap

**Comment by Thadah** [comment]
You can make a simple plugin that has this function inside it

```
function PLUGIN:PlayerSpawn(client)
    if (client:Team() == FACTION_WHATEVER) then
        client:SetMaxHealth(150)
        client:SetHealth(150)
    end
end
```

I attached an example:
[factionhealth.zip](https://github.com/Chessnut/NutScript/files/311074/factionhealth.zip)

**Comment by PaXo0** [comment]
Can i add multiple functions to one code?

**Comment by Thadah** [comment]
Sure, you can just:

`if (client:Team() == FACTION_WHATEVER or client:Team() == FACTION_WHATEVER2) then`
