### ISSUE TITLE
sh_von errors, things are broken for no reason

### ISSUE THREAD

**Issue by benmort38** [Chessnut/NutScript#689]
I am using nutscript 1.0, all of it was working on my other server.

I decided to make a new server, I used the same original files and just modified them to fit my liking, and I've got a few issues.
1. Huge error: 

[ERROR] gamemodes/nutscript/gamemode/libs/external/sh_von.lua:131: vON: Malformed data... Can't find a proper type definition. Char#2:1
1. error - [C]:-1
   1. d_findVariable - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:131
   2. unknown - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:198
      1. d_findVariable - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:76
      2. deserialize - gamemodes/nutscript/gamemode/libs/external/sh_von.lua:198
      3. ReadTable - gamemodes/nutscript/gamemode/sh_util.lua:271
      4. unknown - gamemodes/nutscript/gamemode/core/sh_hooks.lua:6
1.  Act plugin doesn't seem to work at all, and I know my model works with it
2.  Attribute bar is blank, no matter what

The bottom part of the sh_von is what's screwing up the attributes. Can confirm.

I just need a fix for this.  

Also, the code notes said that the error occurs if the first character in the von code is not right.

**Comment by evilbiggy38** [comment]
The bottom part of the sh_von is what's screwing up the attributes.  Can confirm.

I just need a fix for this.

**Comment by benmort38** [comment]
Someone please help, this is somewhat urgent!

**Comment by Thadah** [comment]
I think using NutScript 1.0 nowadays is not just advised against, but just plain impossible to use since that update that caused some plugins from 1.1 to stop working.

I would like to help you but seeing that I just think it will take less time to change to 1.1 rather than try to fix those problems in 1.0

**Comment by Thadah** [comment]
vON is a external library that has nothing to do with NutScript, maybe changing it with the last update can fix the problem you are facing. Many stuff broke with the May gmod update.
