### ISSUE TITLE
Weapons Non-Equippable in f1 Menu Inventory

### ISSUE THREAD

**Issue by RageLaginGaming** [Chessnut/NutScript#691]
I'm starting a Nutscript Star Wars g-mod server, and I've tried numerous combinations of code to enable equippable weapons yet all of them render the weapons un-equippable from the f1 menu. I hvae the models and everything else I want, but there is absolutely no way to equip a weapon I put in the server. I have a weapons folder under plugins with the sh_plugin.lua in it as well as a folder i title "items". In this folder is sh_weapons.lua previously named sh_wep_dc15a.lua . The weapon will not equip after buying it from a vendor. http://steamcommunity.com/sharedfiles/filedetails/?id=707957848 Any Solutions?

**Comment by JakeyCakey** [comment]
Did you make sure to properly assign 

`ITEM.class =` 

Example

`ITEM.class = "m9k_fal"`

You can find the weapon class by right  clicking the weapon in the menu and then "Copy to clipboard" proceed then to CTRL+V it into the brackets of the ITEM.class

**Comment by Tproll** [comment]
I'm also having troubles with this and my ITEM.class is correctly assigned, here is the code im using:
ITEM.name = "Ithaca M37"
ITEM.desc = "A reliable shotgun."
ITEM.model = "models/weapons/tfa_w_ithaca_m37.mdl"
ITEM.class = "tfa_ithacam37"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 100
ITEM.height = 2
ITEM.iconCam = {    
    ang    = Angle(-0.70499622821808, 268.25439453125, 0),
    fov    = 12.085652091515,
     pos    = Vector(0, 200, 0)
}
ITEM.flag = "y"

Edit: In my issue the "equip" button shows up but does nothing when I press it, If I check console it tells me i have equipped it but there is nothing in my hands.

**Comment by HellMan64** [comment]
Add this line of code see what happens!

ITEM.UniqueID = "tfa_ithacam37"
