### ISSUE TITLE
T-Pose Models

### ISSUE THREAD

**Issue by Novakid50** [Chessnut/NutScript#694]
Okay, so I've tried every option right now.  I've tried the nut.anim.setModelClass fix and it didn't work.  Any fixes?  The models we're trying to fix is:
models/codmw2/codmw2hexe.mdl
models/codmw2/t_codm.mdl
models/codmw2/t_codmw2.mdl
models/codmw2/t_codmw2h.mdl
models/player/pmc_4/pmc__01.mdl
models/player/pmc_4/pmc__07.mdl

Please help me fix this!  Thanks!

**Comment by Misterbobbie** [comment]
Problems with this too^^
