### ISSUE TITLE
Server gamemode changes to folder name

### ISSUE THREAD

**Issue by Aults1002** [Chessnut/NutScript#696]
The name of the gamemode should be American World War 2 Roleplay, but the folder name is americanworldwar2roleplay. The name of the gamemode keeps changing to the name of the folder.
It says this in the console: Changing gamemode to American World War 2 Roleplay (americanworldwar2roleplay)

This is my .txt:

"americanworldwar2roleplay"
{
"base" "nutscript"
"title" "American World War 2 Roleplay"
"author" "Edelweiss Gaming"
"menusystem" "1"
}

This is my sh_schema.lua

SCHEMA.name = "American World War 2 Roleplay"
SCHEMA.author = "Edelweiss Gaming"
SCHEMA.desc = "Live Like a Soldier During WW2"
SCHEMA.uniqueID = "americanworldwar2roleplay" -- Schema will be a unique identifier stored in the database.
nut.currency.set("$", "Dollars","Dollar")

**Comment by Aberidius** [comment]
`Changing gamemode to American World War 2 Roleplay (americanworldwar2roleplay)`

That's suppost to happen. The first part `American World War 2 Roleplay` is the gamemode name itself while the part within () are the calling for gamemode folder, it wont / shouldn't change gamemode's displaying name.
