### ISSUE TITLE
Can't type into text boxes

### ISSUE THREAD

**Issue by TheGpr** [Chessnut/NutScript#699]
Hi all.

I can't type into text boxes ([like this](http://images.akamai.steamusercontent.com/ugc/448482659692192849/23456FB2E58BF85C747547010674E46E56D4FBBA/)) just after updated my Garry's mod DS. I have nutscript framework 1.1 with the schema "modernrp". 

Could you help me ?  
Thanks you.

**Comment by lyxara** [comment]
#676
