### ISSUE TITLE
Making an NPC for nutscript.

### ISSUE THREAD

**Issue by noobly-noobly** [Chessnut/NutScript#703]
I need to know how I can set a player whitelisted through VGUI.  My ending code is this:

`
        continueButton.DoClick = function()
            EndMain:MoveTo( 0 - EndMain:GetWide(), ScrH()/2 - EndMain:GetTall()/2, 0.35, 0, 1 )
            EndMain:NewAnimation( 0.35, 0, 1 )
            timer.Simple(0.35,function() EndMain:Close() end)
            timer.Simple(0.35,function() OpenTestEndCorrect() end)
            RunConsoleCommand( "plywhitelist "..LocalPlayer():Name().." German Recruit" )
        end
`
Please help because I don't know the command to whitelist a player and I am trying to make a button through VGUI that does whitelist them.

**Comment by ColinLutter** [comment]
Do you use NS 1.0 or 1.1 ?

**Comment by noobly-noobly** [comment]
1.1

**Comment by ghost** [comment]
whitelisting command is /plywhitelist (player) (Faction)
