### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Badger9** [Chessnut/NutScript#704]
If you place an item in something with storage, then modify the storage and drop it you're able to have someone pick it up and take the item out. After they've taken it out you can then take it out and you'll both have the item. However, the person that picked up the storage with the item in it is unable to drop the item, but they should be able to sell it to NPCs.

**Comment by Thadah** [comment]
Finally someone who understands that to solve a bug we need to know how to reproduce it.
Any lua error appeared?

**Comment by kngrektor** [comment]
What does "modify the storage" mean?

**Comment by Badger9** [comment]
When you right click on an item with storage (within your inventory) you're able to click modify.
