### ISSUE TITLE
MySql cannot connect

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#706]
Okay so recently i decided i want to run nutscript on mysql instead, but when i join the game after setting it up correctly it says 
Can't Connect to MySQL Server on 'ip' [111]
basicly the thing is im not getting any mysql errors in console except

NutScript has failed to connect to the database.
Can't connect to MySQL server on 'ip' (111)

no other mysql errors

**Comment by Thadah** [comment]
Are you using tmysql4 or mysqloo?
