### ISSUE TITLE
Create is not an option in the main menu

### ISSUE THREAD

**Issue by ThatKrautDucky** [Chessnut/NutScript#710]
When ever I start my server it never has the 'create' option. It's only leave. (This is a 1942RP server)

This is the error I get in the console 

Couldn't include file 'sh_config.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))

[ERROR] gamemodes/1942rp/schema/sh_schema.lua:160: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
   1. unknown - gamemodes/1942rp/schema/sh_schema.lua:160
   2. include - [C]:-1
      1. include - gamemodes/nutscript/gamemode/core/sh_util.lua:17
      2. load - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:44
      3. initialize - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:163
      4. unknown - gamemodes/nutscript/gamemode/shared.lua:65

I'm very new to this idk wtf I'm doing :V

**Comment by ColinLutter** [comment]
Could you please post your sh_schema.lua file, because the error derives from it.
