### ISSUE TITLE
Spawing is messed up

### ISSUE THREAD

**Issue by JoshDuper** [Chessnut/NutScript#719]
When ever i die the screen goes black saying "You Died" and when it fades back out into the game all i see is where i died and i cant do anything, cant noclip, cant do anything but if i ragdoll and unragdoll it fixes it, i tried reseting spawns too

**Comment by Gyaviste** [comment]
What schema are you using?

**Comment by kngrektor** [comment]
If youve installed some death screen or something uninstall that. When you join the server you get instantly killed so you can choose a character

**Comment by its-johnny** [comment]
Hello, We need more information about the problem. As Kngrektor says, if you installed a Death Screen or an addon/script that have interaction with the death hook you can have problems

**Comment by nateabowman** [comment]
Uninstall serverside ragdoll workshop addons, try going thru workshop addons at a time to narrow it down. It was server side ragdoll for me.
