### ISSUE TITLE
error when using vcmod car dealer

### ISSUE THREAD

**Issue by Tendersexpartner** [Chessnut/NutScript#723]
I get this error when i take out a car from the vc mod dealer. i dont know if its a vc mod problem but if anyone knows how to fix it please reply [ERROR] gamemodes/nutscript/gamemode/core/hooks/sh_hooks.lua:101: attempt to index a nil value
  1. unknown - gamemodes/nutscript/gamemode/core/hooks/sh_hooks.lua:101

**Comment by nateabowman** [comment]
Freeman will not update VCMod to work for the Car Dealer, I have asked and even told him I would reimburse him for his work to make it compatible with NutScript currency and jobs. Plus NutScript is pretty dead, Chessnut has been not online for quite some time so I doubt there would be a VCMod compatible car dealer for nutscript.
