### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by loaf2001** [Chessnut/NutScript#729]
[AddCSLuaFile] Couldn't find 'nutscript/schema/sh_schema.lua' (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 14))
Couldn't include file 'nutscript\schema\sh_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 17))

**Comment by Russlyman** [comment]
What schema are you using?
