### ISSUE TITLE
Issue with Inventory when there is an item

### ISSUE THREAD

**Issue by domanhthang2110** [Chessnut/NutScript#731]
[ERROR] gamemodes/nutscript/gamemode/core/ meta/sh_item.lua:26: bad argument #2 to 'L' (no value) 
1. L - [C]:-1 
2. getDesc - gamemodes/nutscript/gamemode/core/ meta/sh_item.lua:26 
3. setInventory - gamemodes/nutscript/gamemode/ core/derma/cl_inventory.lua:105 
4. callback - gamemodes/nutscript/gamemode/core/ derma/cl_inventory.lua:402 
5. DoClick - gamemodes/nutscript/gamemode/core/ derma/cl_menu.lua:171 
6. unknown - lua/vgui/dlabel.lua:232

This happen with the sample schema when I open the inventory which has a brick item in it

**Comment by pmx625** [comment]
What version of NS are you using? 1.0 or 1.1?
