### ISSUE TITLE
Love the "support" on here

### ISSUE THREAD

**Issue by loaf2001** [Chessnut/NutScript#732]
[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45: attempt to perform arithmetic on a nil value
  1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45
   2. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
    3. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569

**Comment by Russlyman** [comment]
It's a dead project mate.
