### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by benmort38** [Chessnut/NutScript#733]
First off, I'm running nutscript 1.1 on a schema that I've reinstalled more than once to make sure that nothing is bugged or any of that crap.

I'm not sure where players are saved, so I don't want to completely delete things, and I'm having little luck with support on here.

Noclipping normally cloaks you when you do it, from my experience on every other ns server. However, when I go into noclip, my character flickers and then just stays visible, which is not what I want. Furthermore, something in my gamemode is breaking ulx god and ulx buddha, because switching gamemodes to sandbox makes it work just fine.

I should also add that godmode does not work, regardless of the admin module.

I fixed the godmode by using a new admin module.

**Comment by benmort38** [comment]
Reinstalled a vanilla hl2rp, nothing fixed.

**Comment by pmx625** [comment]
Is the schema you are using compatible with the framework version? (NS 1.1)
