### ISSUE TITLE
Chat Icontags

### ISSUE THREAD

**Issue by confuseth** [Chessnut/NutScript#734]
I think everyone now using 1.1 finds himself with missing textures as icons for their chat tags.

can this be fixed please because I dont know how to do it myself

**Comment by benmort38** [comment]
bump, this is a serious annoyance

**Comment by pmx625** [comment]
If you dont know to fix it, remove the icons from the chat. For that, check this github link and look at the second comment!!! http://viid.me/qxNObQ

**Comment by Heyter** [comment]
new fix.
https://nutscript.rocks/community/showthread.php?tid=4108&pid=5550#pid5550
