### ISSUE TITLE
Attempting To Use A Custom Hud

### ISSUE THREAD

**Issue by FNSpartan** [Chessnut/NutScript#735]
However the default ammo hud seems to cover it. how do i disable it?

**Comment by nateabowman** [comment]
Maybe you shouldnt be running a server..

**Comment by ghost** [comment]
You should know this if you're running a server....

**Comment by FNSpartan** [comment]
Look  dickheads.

**Comment by FNSpartan** [comment]
You can stop being cocks and help you know?

**Comment by FNSpartan** [comment]
But hey I fixed it so go the hell away
