### ISSUE TITLE
Nutscript Item question.

### ISSUE THREAD

**Issue by WMODEL** [Chessnut/NutScript#736]
So, I'm trying to code Perishable inventory item that gives players Weapons. And I have no idea what function is needed to give Players a weapon. Could someone help me out?

**Comment by art-gur** [comment]
Try to use this code:
```
local inv = ply:getChar():getInv() // Get player inventory
inv:Add("itemName", 1) // First argument - item unique name(example radio), second argument - amount
```

**Comment by WMODEL** [comment]
What I wish to do is not giving player Inventory Item. I wish to give them swep when they open it.

**Comment by WMODEL** [comment]
Sorry, I should have made my question clear.

**Comment by art-gur** [comment]
If I understood you correctly, you want give to player some kinds of weapons/sweps. Try it:
`player:Give("weapon_pistol")`

Example item(sh_box.lua):
```
ITEM.name = "Box"
ITEM.model = "models/props_junk/cardboard_box001a.mdl"

ITEM.functions.OpenBox = {
name = "Open",
tip = "Open a box",
onRun = function( item )
item.player:Give("weapon_pistol")
return true
end
}
```

**Comment by WMODEL** [comment]
ITEM.name = "Panzerfaust Safety Pin"
ITEM.model = "models/props_junk/cardboard_box001a.mdl"

ITEM.functions.OpenBox = {
name = "Open",
tip = "Open a box",
OnRun = function(item)
item.player:Give("weapon_752_panzerfaust")
return true
end
}

This is what I tried. And it won't work, I'm getting this script error.

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_item.lua:659: attempt to call field 'onRun' (a nil value)
  1. unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:659
   2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by art-gur** [comment]
Replace OnRun -> onRun

**Comment by WMODEL** [comment]
Thanks for the help! It works now.
