### ISSUE TITLE
Disabling tab icon, and chat textures

### ISSUE THREAD

**Issue by benmort38** [Chessnut/NutScript#738]
How does one go about removing the little spot where a player's face is displayed in the tab menu?

Also, chat textures in 1.1 don't work.

**Comment by Heyter** [comment]
try
http://pastebin.com/rUbLXwHt

**Comment by benmort38** [comment]
where do I put that?

**Comment by Heyter** [comment]
new fix.
https://nutscript.rocks/community/showthread.php?tid=4108&pid=5550#pid5550
