### ISSUE TITLE
Errors tossed when trying to add lua-generated item

### ISSUE THREAD

**Issue by overki11** [Chessnut/NutScript#739]
Hi, I'm developing a plugin to allow admins to generate items on-the-fly, and whenever I use the code and attempt to actually give it to the player, it tosses this error:

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_item.lua:429: attempt to index local 'item' (a nil value)

unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:429
func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:155
unknown - lua/includes/extensions/net.lua:32
Now, here is my code: (excuse any crappiness, i'm not the best coder)
function PLUGIN:setupNewItem(ply, itemData)
local itemID = "ki11custom_" .. string.lower(itemData.name:gsub("%s+", ""))
local newItem = nut.item.register(itemID, nil, nil, nil, false)
if(!newItem) then return end
newItem.name = itemData.name
newItem.desc = itemData.desc
newItem.model = itemData.model
nut.util.notify("Custom Item Created! Item UniqueID is: " .. itemID, ply)
if(itemData.addCopy) then
local c,b = ply:getChar():getInv():add(itemID)
if(!c) then
nut.util.notify("Tried to add copy of custom item, but no space!", ply)
else
nut.util.notify("Custom item added to inventory.", ply)
end
end
end

I know for sure that all fields are met. I even copied and pasted some code from modernrp doing the exact same thing (and manually replaced values to literals), and it still tossed this error when trying to add a generated item.

**Comment by Heyter** [comment]
using "Insert code" or paste here pastebin.com
nutscript die :(

**Comment by pmx625** [comment]
There is already a command for that: it is "/chargiveitem" only for admins.

**Comment by overki11** [comment]
You obviously do not understand what I am trying to do, pmx

**Comment by Russlyman** [comment]
This is for issues with the NutScript Framework, not coding troubles.

**Comment by overki11** [comment]
> This is for issues with the NutScript Framework, not coding troubles.

Yes, and this IS a problem with the NutScript framework. Creating dynamically generated items using NUTSCRIPT'S LIBRARY for doing so, causes errors. Unless I am somehow doing this wrong (I checked a ton), this feature of the framework is broken.

**Comment by Rubberbandits** [comment]
You have to get the actual item table, then network the changes. Each instance of an item creates it's own 'object'.

AKA, you need to show code before people can analyze whether or not you're doing it wrong.
