### ISSUE TITLE
F1 Bug

### ISSUE THREAD

**Issue by Hankshark03** [Chessnut/NutScript#741]
Hello, whenever I try to open the F1 menu for NS it opens both the NS menu and the Garry's Mod Spawn list menu. It shows this error in console.
[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45: attempt to perform arithmetic on a nil value
  1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45
   2. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:101
    3. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:81
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:569
Would appreciate some help

**Comment by TrishaDemilion** [comment]
We've been having this issue as well. It would be great to find a fix for this, but we've made a temporary fix, just hold the spawn menu key before pressing f1.
