### ISSUE TITLE
Faction HP on spawn

### ISSUE THREAD

**Issue by Vraxi** [Chessnut/NutScript#744]
I've tried multiple ways of setting the HP from reading through the forums and other peoples queries but have had 0 luck at settings factions HP on spawn. All I need is some simple instructions and that would help a lot! I've tried a hook with nothing happening and plugins which literally does nothing.

**Comment by Vraxi** [comment]
Please?

**Comment by Aberidius** [comment]
`ply:SetMaxHealth`
