### ISSUE TITLE
Problem with nut_storage

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#747]
Hi, i have a problem : when i open a storage i can use a item to infinity because the item does not disappear !

Thanks for anwsering me !

**Comment by nateabowman** [comment]
Any error? From what I remember, storage was messed up as it was from github. Ill test it on my server tomorrow when I wake up and verify.

**Comment by ghost** [comment]
Ok thanks

**Comment by ghost** [comment]
I solved the problem, thank you anyway !
