### ISSUE TITLE
Can't see "class" tab in the f1 menu

### ISSUE THREAD

**Issue by iliashassan** [Chessnut/NutScript#750]
Title says it at all basicly. And no it's not the schema that causes this, cause i tried the hl2rp schema chessnut provided and got the same problem.

**Comment by pmx625** [comment]
Create new a new class file and assign it to a faction.

How to create the file? Copy one of the existing ones and you will notice they are all named "sh_cp_...". You need to know your faction index. For example Combine's faction tag is "FACTION_CP". That is why the file uses "sh_cp_" in its name.

Once you do this, add to the file "CLASS.isDefault = true". Once you join the server, transfer your character to the faction you assigned the class to or create a new character on that same faction.
