### ISSUE TITLE
Models T-Posing

### ISSUE THREAD

**Issue by Springerz** [Chessnut/NutScript#754]
I am new to nutscript and the models I want to use for my server are T-Posing.

I have tried:
nut.anim.setModelClass("models/porky-da-corgi/starwars/mandalorians/bountyhunter.mdl", "player")
In my schema.
I have seen alot of issues about this but no fix for me.

Also is there a way where I dont have to do nut.anim.setModelClass and can make all models non T-Pose.

Help would be much appreciated.

**Comment by Arrow9867** [comment]
With the Mandalorian model, are there two different models for the same one? T-posing is often caused by people using the ID for a NPC and not a playermodel.
