### ISSUE TITLE
Character Stop-Starting When Walking

### ISSUE THREAD

**Issue by Arrow9867** [Chessnut/NutScript#755]
I recently coded my own HL2RP that I was going to use on a server, but then I noticed that (only) the citizen character would continuously stop-start as you would during a low FPS, but this occured during high FPS. 

This only happens as a citizen, no other character does this. If you know how to fix this please comment!

**Comment by pmx625** [comment]
What models are you using for the citizen faction? That may be it. Nutscript lags with certain models.
