### ISSUE TITLE
Vendors don't save after restart.

### ISSUE THREAD

**Issue by Gj465** [Chessnut/NutScript#757]
So after looking everywhere, I have not found anything on this. I can set down vendors and set them all up and they work fine, even when I change maps it still works fine. But the second I actually restart the server they are all erased. At first, I thought it was a database problem but the database stores everything else fine. It also bugs out with dispensers and other items like it.

**Comment by Shepardeon** [comment]
Hey, got the same problem, here it comes from the data saving system, I don't know what's causing it though... All I could find was that the server seems to delete the entities once a player joins after a fresh restart. I'm trying to solve that thing but... Yeah.

![sans titre](https://cloud.githubusercontent.com/assets/15271735/25781968/5963e910-3341-11e7-88e2-9c99d822b86a.png)

I solved this issue, if you're still want the solution here it is:

In nutscript/gamemode/core/hooks/sv_hooks.lua (line 658)

-> The game cleans up the map automatically, so we load the entities once the map have been cleaned (which was already coded in)
But now, we don't "save" the entities before cleaning up as they would save again once deleted by the clean up anyway (so, it's just glitchy)

```
function GM:PreCleanupMap()
	-- We can erase this function as it won't be used anyway
end

function GM:PostCleanupMap()
	hook.Run("LoadData")
end
```
In nutscript/gamemode/core/hooks/sv_hooks.lua (line 527)

-> We change how we first load every entity : we wait 2 seconds then we check if there is alread at least ONE entity created by nutscript, if there aren't any, we just call LoadData() to make sure it didn't failed the first time

```
timer.Simple(2, function()
		local found = false

		for k, v in pairs(ents.GetAll()) do
			if (v:GetClass():find("nut_")) then
				found = true
				break
			end
		end

		if (found != true) then
			hook.Run("LoadData")
		end
	end)
```
