### ISSUE TITLE
Business Menu Bug

### ISSUE THREAD

**Issue by pmx625** [Chessnut/NutScript#759]
I added cssweapons plugin to my schema, however, when I go to the business menu and go to the "Weapons" category, I do not see a scroll bar to scroll down in order to be able to see all the weapons listed in that category. Here it is an image (no errors show up).

https://files.gitter.im/Chessnut/NutScript/vVxz/thumb/blob.png

If someone could help me with this, I would really appreciate it!

**Comment by MrSylar59** [comment]
Hay, I fixed this issue today by editing cl_buisness in nutscript/gamemode/core/derma/ (look for line 167) and directly under, put this:

```
timer.Simple(0.01, function() 
	self.scroll:InvalidateLayout()
end)
```

**Comment by pmx625** [comment]
Thank you so much for your reply! It is good to see someone is still interest in NS! :)
