### ISSUE TITLE
Rest of factions not showing up.

### ISSUE THREAD

**Issue by kittylactose** [Chessnut/NutScript#761]
I have a total of 8 factions (don't judge) however on the character create screen it's only showing 6 of them and it seems like I can't scroll down to view the rest. (yes, they're all whitelisted) I want all of them to show so people who've managed to earn a spot on each faction can freely choose what they want without me having to whitelist and unwhitelist to remove a faction so the next one pops up. 

Is there a way to have the other factions show up or is six the limit?

**Comment by Shepardeon** [comment]
I guess it is possible to add a scrollbar to the menu (check gmod wiki, I'm not on my computer and can't check that), and if I remember well I think there is actually a scrollbar but it uses an old function ? (not sure though)
