### ISSUE TITLE
Issues I need help with. (1.1)

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#762]
Vendor bug:
So I this makes no error message or debug of some sort. First of all what is the proper way of making a vendor? Second when I spawn a vendor from the entities tab and give its items and rename it etc. After I restart the server and see if it is there. It is but when I create another one and restart the server only the first one is there. Sometimes the first one changes it name to the default one (John Doe) and its default model.

Vehicle Inventory Bug:
`
[ERROR] gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105: bad argument #2 to 'L' (no value)
  1. L - [C]:-1
   2. setInventory - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:105
    3. callback - gamemodes/nutscript/gamemode/core/derma/cl_inventory.lua:402
     4. DoClick - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:171
      5. unknown - lua/vgui/dlabel.lua:232

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_item.lua:412: attempt to index local 'icon' (a nil value)
  1. unknown - gamemodes/nutscript/gamemode/core/libs/sh_item.lua:412
   2. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:155
    3. unknown - lua/includes/extensions/net.lua:32
`

Vehicle code (sh_adder.lua) located in the schema/plugins/vehicles/items/vehicles/

ITEM.name = "Adder"
ITEM.desc = "A cool car."
ITEM.model = "models/tdmcars/gtav/adder.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.maxGas = 1000
ITEM.price = 35000
ITEM.vehicleData = {
	type = TYPE_GENERIC,
	model = ITEM.model,
	script = "scripts/vehicles/TDMCars/gtav/adder.txt",
	name = ITEM.name,
	physDesc = ITEM.physDesc,
	maxGas = ITEM.maxGas,
	seats = {
		{
			pos = Vector(16.971733093262, -10.549472808838, 4.3880672454834),
			ang = Angle(0, 0, 0),
		}
	}
}

This happens when I buy a vehicle of a Vendor then go to the inventory to spawn it. All items that are the same become one. If I pick up an item after buying the vehicle it does not appear in the inventory.

**Comment by Shepardeon** [comment]
Can you make a video of the issue ? I have trouble understanding what you mean.
Did you add some stuff except the item ? Nutscript seems to have troubles with your model from what I can see, try to change the models to see if it indeed comes from there.

Also, for the vendors I guess you should take a look at issue #757
