### ISSUE TITLE
Adding a "progress bar"

### ISSUE THREAD

**Issue by pmx625** [Chessnut/NutScript#763]
When a character dies I want the character to see a progress bar saying "You are regaining consciousness..."  , like on NS 1.0. I know I must edit this file: https://github.com/Chessnut/NutScript/blob/773501a9aac9db75209ca614dc8404c5c3dbe219/gamemode/core/libs/cl_hud.lua 
However what should I add to make it display the progress bar?

**Comment by MrSylar59** [comment]
From what I could see in the code, you would add a line somewhere (I'd put it in the death hook) looking like this:
```
Player:setAction("Your text", time, function() 
	/CALLBACK CODE/ 
end)
```
You can find an example in nutscript/plugins/doors/entities/weapons/nut_keys.lua (line 127)

**Comment by pmx625** [comment]
Thanks! I will test it tomorrow and see if it works!

**Comment by pmx625** [comment]
Hello. I have added these lines of code to cl_hud.lua under gamemode/core/libs directory where the code I want to edit is.
`local time = CurTime()
	local time2 = time + nut.config.get("spawnTime", 5)
	owner:setAction("You are regaining consciousness...", nil, nil, time, time2)`

When I join the server this error appears:
`[ERROR] gamemodes/nutscript/gamemode/core/libs/cl_hud.lua:40: attempt to call method 'setAction' (a nil value)
  1. drawDeath - gamemodes/nutscript/gamemode/core/libs/cl_hud.lua:40
   2. drawAll - gamemodes/nutscript/gamemode/core/libs/cl_hud.lua:50
    3. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:481
`

**Comment by MrSylar59** [comment]
In fact the setAction function is a serverside function, so you probably need to put it in your sv_hooks.lua and find or add the onPlayerDeath hook (I think it's the correct name)

**Comment by pmx625** [comment]
@MrSylar59 I dont need to add anything as this is already here...
https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/sh_util.lua

Now the question is how do we trigger it? Cause everytime someone dies it appears on the screen "You are Dead".

**Comment by MrSylar59** [comment]
https://github.com/Chessnut/NutScript/blob/1.1/gamemode/core/hooks/sv_hooks.lua#L407
