### ISSUE TITLE
Area titles

### ISSUE THREAD

**Issue by pmx625** [Chessnut/NutScript#764]
On Nutscript 1.0, everytime you entered a new area that was listed on the area manager, the name of that area, aswell as the current time were shown on the right side of the screen such as the nutscript and schema's authors names. 

https://github.com/Chessnut/NutScript/blob/master/plugins/areadisplay.lua
https://github.com/Chessnut/NutScript/blob/master/gamemode/core/sv_hooks.lua
The area name was displayed the same way the nutscript author was displayed, according to a function called nut.scroll.Send().

How can I add this function to NS 1.1 and make it show area names like in NS 1.0 instead of the way they show on NS 1.1?

**Comment by MrSylar59** [comment]
I think you will have to rewrite the addon completely, or rollback to NS 1.0 as the functions from NS 1.0 are no longer used in NS 1.1 for most part

**Comment by pmx625** [comment]
Thank you for your reply! :)
