### ISSUE TITLE
Is there any way of making a ......

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#765]
Is there any way to make a class that for example can only have 5 people in it?

**Comment by ghost** [comment]
CLASS.limit


Example:

CLASS.name = "Hitman"
CLASS.faction = FACTION_CITIZEN
CLASS.limit = 2

function CLASS:OnSet(client)
end
CLASS_HITMAN = CLASS.index

**Comment by Shepardeon** [comment]
Yes, I think if you do something like this:

```
function CLASS:onCanBe(client) 
	-- Code that returns true if there is still empty seats for the class and false if not
end
```
