### ISSUE TITLE
Class problem

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#766]
So is it possible to make when you choose a class then you respawn? Yes I know a bit mingy but it prevents abuse.

**Comment by Shepardeon** [comment]
```
function CLASS:OnPlayerJoinClass(client, self)
	client:Spawn()
end
```
should do alright

**Comment by Crabban** [comment]
Thaaank youuuu soooo much!!

**Comment by ghost** [comment]
Did not work
No errors. No nothing.

**Comment by Johnny7A2** [comment]
Go here: https://github.com/rebel1324/NutScript/pulls
