### ISSUE TITLE
Business Menu Removal 

### ISSUE THREAD

**Issue by Throlex** [Chessnut/NutScript#768]
Is there any way that I can completely remove the business menu from the F1 tab? I just want it to be restricted to all players. Can anyone walk me through how to do that?

**Comment by pmx625** [comment]
As I suggested you before, create a new flag. Whoever has that flag will be capable of viewing/purchasing items from the business menu.
Once you create it do not give it to regular players.
This is better as it does not make you mess with the core code and at the same time it enables you to restrict access to the business menu for staff members only.

**Comment by Throlex** [comment]
@pmx625 Thats helpful, but can you walk me through the commands I'll have to place into whatever folder?

**Comment by pmx625** [comment]
@Throlex Yes.

So you have all the item lua files present on the business menu in yourschemafolder/schema/items. In each LUA file add this line of code:
`ITEM.flag = k`

Once you do that, go to yourschemafolder/schema/ and open sh_schema.lua . Scroll all the way to the bottom and add the following line of code:
`nut.flag.add("k", "Restricted Items")`

Do note you can change "k" for any letter you want and "Restricted Items" for any other description you may prefer.

This way users that do not have the "k" flag will not be able to access the business menu but you and the people you want to be able to do so. Furthermore, if you wish to give an item to a player by running "/chargiveitem" command you will still be able to do so without them accessing the business menu.

Do note that for plugins such as "radio", etc you need to go to the folder of the plugin in yourschemafolder/plugins/folder/items and do the same thing you did in the items lua files in the other directory: Adding the line `ITEM.flag = "k"`

**Comment by Gh0stnelax** [comment]
I have figured out the fix for anyone who wants to know. No need for Throlex to see this as I am working with him on this server.

1. Go to the Nutscript folder in the gamemodes folder(NOT SCHEMA GAMEMODE FOLDER)
2. Once there go to gamemode>core>derma
3. Delete cl_bussiness

And done, simple :)
