### ISSUE TITLE
Faction Transfer not changing model

### ISSUE THREAD

**Issue by clingo** [Chessnut/NutScript#770]
I was wondering if anyone has code for switching the model to the correct faction model after using /plytransfer or if it just an error with my version of faction transfer or something.

Thank you for reading.

**Comment by Throlex** [comment]
You'll have to change the model manual using the /charsetmodel command afterwards.

**Comment by Shepardeon** [comment]
Or update the model in the command's onRun method (http://wiki.garrysmod.com/page/Entity/SetModel)

**Comment by clingo** [comment]
So like target:SetModel("") -- with something in obviously, or do i have to set the CharacterVar to keep the model for the character loads back into the server?
