### ISSUE TITLE
Props/Vendors despawning

### ISSUE THREAD

**Issue by Radioactiveboy** [Chessnut/NutScript#774]
I'm using NutScript 1.0, been trying to figure out what could be causing vendors to despawn on restart. Also the /setpersist command doesn't seem to be working and props are vanishing upon restat of the server. Obviously somewhat inconveniant and have yet to find a fix for this. Character data, inventories, ranks, all of that saves fine however. Just the map it would seem.

**Comment by Shepardeon** [comment]
Take a look at issue #757
I basically fixed it for NS 1.1, but the problem is the same for NS 1.0, my guess is that the solution won't be so different, try and see.
