### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by Aults1002** [Chessnut/NutScript#783]
When I join my server, it says this, I have not changed the Nutscript folder in any way and I know there is nothing wrong with my Schema.

Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/bombard_.ttf'
Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/ds-digii.ttf'
Failed to load custom font file 'e:/steam/steamapps/common/garrysmod/garrysmod/workshop/resource/fonts/mrb.ttf'
Failed to load custom font file 'e:\steam\steamapps\common\garrysmod\garrysmod\download\resource\fonts\clearsans-medium.ttf'
Failed to load custom font file 'e:\steam\steamapps\common\garrysmod\garrysmod\cache\workshop\resource\fonts\clearsans-medium.ttf'

I believe it is this, but there are no addons on the server at all either, so I think there is something major wrong with the Nutscript.

**Comment by rebel1324** [comment]
setup fastdl properly and we're not using any customfont but fontello icon font.
