### ISSUE TITLE
Can't set owner (HELP_

### ISSUE THREAD

**Issue by ghost** [Chessnut/NutScript#784]
Please help!

I have tried the nut_setowner and it does not work, it says 

** 'nut_setowner' has been deprecated in NutScript 1.1
** Instead, please install an admin mod and use that instead.

I have tried ULX and it says  

No response from the server (this may be an invalid command)

What do I do?

**Comment by art-gur** [comment]
Join to your server. Write next command in server console: ulx adduser NAME superadmin/admin/user/norank, where NAME is your nick.

**Comment by ghost** [comment]
Nick being steam name or Character name?

**Comment by art-gur** [comment]
If you in main menu - steam name, otherwise character name.

**Comment by ghost** [comment]
I have tried both, and it gives me the same damn thing.

**Comment by ghost** [comment]
ulx adduser John Becker superadmin

**Comment by ghost** [comment]
in the RCON console

**Comment by art-gur** [comment]
```
ulx adduser John Becker superadmin
```
Try to use quotes: ulx adduser "John Becker" "superadmin"

**Comment by ghost** [comment]
solved it, ulx adduser "john becker" superadmin

Thanks!

**Comment by SleepyMode** [comment]
Hey there mate,
please use the updated one.
https://github.com/rebel1324/NutScript/issues
