### ISSUE TITLE
Cant set the date to anything before the year 1970

### ISSUE THREAD

**Issue by Drahgoone** [Chessnut/NutScript#785]
Can't set the year to anything before 1970 or I get this error

[ERROR] gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45: attempt to perform arithmetic on a nil value
  1. get - gamemodes/nutscript/gamemode/core/libs/sh_date.lua:45
   2. setup - gamemodes/nutscript/gamemode/core/derma/cl_information.lua:135
    3. Init - gamemodes/nutscript/gamemode/core/derma/cl_menu.lua:71
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. unknown - gamemodes/nutscript/gamemode/core/hooks/cl_hooks.lua:600

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
