### ISSUE TITLE
bodygroups and skins enabled with items

### ISSUE THREAD

**Issue by Drahgoone** [Chessnut/NutScript#786]
Small issue, just something I noticed

If you enable an inventory item that changes your body group, and then relog, it is still enabled, and visible when you rejoin, which is nice and convenient because you don't have to re-enable it. However, with skins, upon re-joining, it will show as enabled, even though it is not. Skins don't seem to save as body groups do.

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
