### ISSUE TITLE
Picking up vehicles

### ISSUE THREAD

**Issue by SkyMulley** [Chessnut/NutScript#788]
Put some vehicles as entities in a vendor, but you can't get in them and drive them, it only says pickup. Is there another way to sell vehicles in a vendor or disable the pickup?

**Comment by rebel1324** [comment]
What do you mean?

**Comment by SkyMulley** [comment]
If you try and buy a vehicle from a Vendor and then place it down from the inventory. You then cannot enter the vehicle only pick it back up again. Is there an alternative to the Vendor or a way to disable picking up?

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
