### ISSUE TITLE
TFA weapons and Ammo.

### ISSUE THREAD

**Issue by Ripskilt** [Chessnut/NutScript#790]
I am trying to make ammo work with TFA weapons, how ever I am having some issues. I'll list them below.

TFA weapons when un-equipt and re-equipted get back their lost ammo, you can continue to do this to get unlimited ammo.

TFA Ammo - When I try to make ammo for the weapons (I only tried with the Sako 85 from the pack NMRIH) it does not work, they go into oblivion and nothing happens.

Code below -

Weapons -
ITEM.name = "Sako 85"
ITEM.desc = "A old worn hunting rifle"
ITEM.model = Model ("models/weapons/tfa_nmrih/w_fa_sako85.mdl")
ITEM.class = "tfa_nmrih_sako"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "y"

AMMO -

ITEM.name = ".357 Sniper Rounds"
ITEM.model = "models/items/sniper_round_box.mdl"
ITEM.ammo = "tfa_ammo_sniper_rounds" 
ITEM.ammoAmount = 30
ITEM.ammoDesc = "A Box that contains %s of .357 Sniper Rounds"
ITEM.price = 10
ITEM.category = "Ammunition"
ITEM.flag = "y"

**Comment by its-johnny** [comment]
https://github.com/rebel1324/NutScript

**Comment by rebel1324** [comment]
https://wiki.garrysmod.com/page/Structures/SWEP
```
string Ammo - Ammo type ("Pistol", "SMG1" etc)
number ClipSize - The maximum amount of bullets one clip can hold
number DefaultClip - Default ammo in the clip, making it higher than ClipSize will give player additional ammo on spawn
boolean Automatic - If true makes the weapon shoot automatically as long as the player has primary attack button held down
```

`SWEP.DefaultClip = 0`
