### ISSUE TITLE
Prop Persisting Corrupting Maps.

### ISSUE THREAD

**Issue by Ripskilt** [Chessnut/NutScript#795]
I am currently having a issue on my server with the persisting. Every time I persist a bunch of props on a map and then restart said map, the server no longer wants to launch. When I go into garrysmod/data/persist/ and remove the persist data file for that map it works again but all props are removed. I have no idea what is causing this issue and have been trying to figure it out for the past four days. I tried removing addons I though were the cause, I tried removing the prop persist tool which I also thought was the issue. I've even tried to see what errors my script may be having with the -condebug but nothing ever happens. So any help on this will be much appreciated.

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
