### ISSUE TITLE
Pacoutfit doesn't work with Nutscript 1.1

### ISSUE THREAD

**Issue by Quackers1** [Chessnut/NutScript#797]
So, this has been an issue for both me and my friend in modifying the 1.1 schema, and the problem we encounter only APPLYS to 1.1, as everything is roses in 1.0

pacoutfit just doesn't seem to work regarding model changes, things that require pac data work just fine, but anything regarding the model (skin, bodygroup, change in model entirely) just doesn't work. The items that are written (I.e, "Rebel Clothing") with the item model of a suitcase or something or other, will act like an equipable item just fine, however it does not DO anything when equipped, it just gives the green dot and nothing else. the intention of the item is to change the model, but keep the same face. The model addon Im using includes 7 different models for each Male (Male01-Male09), and Im using one of them for the base model (meaning to models to select when creating a character are all the same 'type" of the 7 models but with seperate male faces), all of the models include skins and bodygroups aswell. in the same way that if I do 

ITEM.replacements = {"group01", "group03"}

which changes from citizens to rebels, meaning if my model is
"models/Humans/Group01/male_09.mdl"
it changes to
"models/Humans/Group03/male_09.mdl"
(it only replaces a certain PART of the model)

in the model pack if I do 
ITEM.replacements = {"shirt", "closed_coat_tie"}

it will change my model from 
models/player/suits/male_09_shirt.mdl
to
models/player/suits/male_09_closed_coat_tie.mdl

and if the skin of my model is 0 and I want to have an item to make the skin 3, I make it so the code has the line
ITEM.newSkin = 3

Pretty straight forward right? well, maybe in 1.0 but something with changing it to 1.0 to 1.1 completly breaks it, for both the base hl2 models and addon models, only items with PACDATA included (i.e I make a hat in PAC3 and port the data into "ITEM.pacDATA = { } ) actually work and are put on the model, but anything related to editing the base model itself will not appear on the model and only just shows as "equipped" in inventory.

The code I am using is this(both have the same problem):

HL2 models:
ITEM.name = "Rebel Uniform"

ITEM.desc = "Armor made from makeshift materials"

ITEM.model = "models/props_c17/BriefCase001a.mdl"

ITEM.width = 1

ITEM.height = 1

ITEM.price = 50

ITEM.outfitCategory = "outfit"

ITEM.category = "Outfits"

ITEM.permit = "outfits"

--ITEM.pacData = {}

--ITEM.newSkin = 0

ITEM.replacements = {

	{"group01", "group02"}

}

Addon models:
ITEM.name = "Closed Suit & Tie"

ITEM.desc = "A closed suit with a tie."

ITEM.model = "models/props_c17/BriefCase001a.mdl"

ITEM.width = 1

ITEM.height = 1

ITEM.price = 50

ITEM.outfitCategory = "outfit"

ITEM.category = "Outfits"

ITEM.permit = "outfits"

--ITEM.pacData = {}

--ITEM.newSkin = 0

ITEM.replacements = {

	{"shirt", "closed_tie"}

}

I cannot find anything wrong with my code. if anyone could provide a solution I would appreciate it, this doesn't appear to just be me, because it also happens to my friend, aswell as on a public server

**Comment by Quackers1** [comment]
`ss`

**Comment by Quackers1** [comment]
I found the problem, I need to add the huge block of code in the pacoutfit "base" specificying the function use

**Comment by CallowayIsWeird** [comment]
Hey, just wondering what that "block of code" was, if you could help me fix this as well.

**Comment by Quackers1** [comment]
I'll send it when I get home, Just letting you know I saw this email

**Comment by DanyHimmler** [comment]
Hi, could you send this block of code also it'd help a lot, Thanks.

**Comment by DimitriNAllat** [comment]
could someone send me the block of code as well please, I can not find anywhere and I am using 1,1.
