### ISSUE TITLE
Playermodels hunching over

### ISSUE THREAD

**Issue by benmort38** [Chessnut/NutScript#800]
Happening for a lot of people without any errors in console. Schema also gives no errors at any point.

Playermodels that are known to work (about 90% of the ones in my pack) look hunched over until a player rejoins. Looks something like this:
[Hunched model](http://steamcommunity.com/sharedfiles/filedetails/?id=1256432316)

Never seen this before, was wondering if there's a known cause or fix.

The models T-Pose normally but I have it set to nut.anim.setModelClass("models/gonzo/battlelordsskins/white/whitebattlelord2.mdl", "player") for example, which fixes the t-posing but still gives me this other issue.

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
