### ISSUE TITLE
Character selection leads to black screen

### ISSUE THREAD

**Issue by Edelmann84** [Chessnut/NutScript#803]
After selecting any character I make, my screen goes entirely black, with no lua errors. I can force an error if I scroll and left click.

[ERROR] gamemodes/nutscript/plugins/wepselect.lua:150: attempt to index a nil value
  1. v - gamemodes/nutscript/plugins/wepselect.lua:150
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:412

This issue only started after I removed a workshop item.

**Comment by lechu2375** [comment]
> Delete plugin - best option. 
You have proper version of nutscript and plugin ?

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
