### ISSUE TITLE
icon Error

### ISSUE THREAD

**Issue by MrPolizei** [Chessnut/NutScript#804]
When i trying to make new Character icon is just error
But Model is not error it's actually working but icon is error, how to fix this? or
 There is another way to make new icons?

![test2](https://user-images.githubusercontent.com/35915477/35500765-e2d1fec0-051a-11e8-951f-3cd99fc3b92f.PNG)

**Comment by lechu2375** [comment]
https://github.com/rebel1324/NutScript
Issues with 1.1 post there.

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
