### ISSUE TITLE
NS - Unknown

### ISSUE THREAD

**Issue by Aults1002** [Chessnut/NutScript#805]
My server is not going into the right gamemode. There are 0 errors and I have no idea what's going on.

Auto detecting CPU
Using default binary: ./srcds_linux
FIND [/cstrike/*.vpk]
ADDING [/cstrike/cstrike_pak_000.vpk]
Adding Path: [/cstrike]
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
WS: Waiting for Steam to log us in....
WS: Fetching collection info...
Processing collection 729514349...
Collection 'HKG: WW2 RP'
72 new addons
WS: Finished!
WS: Processing 72 addons...
Processing addon 72: [Official] Precision Tool (104482086)...
Addon up to date, mounted!
Processing addon 71: SCars Slim (104483020)...
Addon up to date, mounted!
Processing addon 70: NPC Tools (104486597)...
Addon up to date, mounted!
Processing addon 69: WW2 American NPCs (104557094)...
Addon up to date, mounted!
Processing addon 68: Extended Spawnmenu (104603291)...
Addon up to date, mounted!
Processing addon 67: Easy Bodygroup Tool (104604943)...
Addon up to date, mounted!
Processing addon 66: WW2 Weapons (106550832)...
Addon up to date, mounted!
Processing addon 65: The sit anywhere script! (108176967)...
Addon up to date, mounted!
Processing addon 64: 3D2D Textscreens (109643223)...
Addon up to date, mounted!
Processing addon 63: Gmod Legs 3 (112806637)...
Addon up to date, mounted!
Processing addon 62: No Collide World (114297900)...
Addon up to date, mounted!
Processing addon 61: WW2 Transport Scars (146596882)...
Addon up to date, mounted!
Processing addon 60: NutScript Content (207739713)...
Addon up to date, mounted!
Processing addon 59: Simple ThirdPerson - Sliders & Fixes! (207948202)...
Addon up to date, mounted!
Processing addon 58: PermaProps (220336312)...
Addon up to date, mounted!
Processing addon 57: Improved Stacker (264467687)...
Addon up to date, mounted!
Processing addon 56: World War 2 Machine Gun Emplacements (409918642)...
Addon up to date, mounted!
Processing addon 55: Fortification Props Model Pack (422672588)...
Addon up to date, mounted!
Processing addon 54: WW2 Weapons II (428127970)...
Addon up to date, mounted!
Processing addon 53: TFA HUD (453346276)...
Addon up to date, mounted!
Processing addon 52: TFA Base [ Reduxed ] (415143062)...
Addon up to date, mounted!
Processing addon 51: UTime (657474627)...
Addon up to date, mounted!
Processing addon 50: Custom ULX Commands (718665054)...
Addon up to date, mounted!
Processing addon 49: Robotnik's TFA WW2 Western Front SWEPs Pack (527183258)...
Addon up to date, mounted!
Processing addon 48: Robotnik's TFA WW2 Eastern Front Pack (434445556)...
Addon up to date, mounted!
Processing addon 47: Angry's Infantry Mine (640894781)...
Addon up to date, mounted!
Processing addon 46: Day of Infamy: Miscellaneous and Fortification Props (964552587)...
Addon up to date, mounted!
Processing addon 45: Red Classics Flags (161448679)...
Addon up to date, mounted!
Processing addon 44: [simfphys] LUA Vehicles - Base (771487490)...
Addon up to date, mounted!
Processing addon 43: William's World War 2 Simfphys Collection (887455538)...
Addon up to date, mounted!
Processing addon 42: World War 2 German Focus Radio (827165950)...
Addon up to date, mounted!
Processing addon 41: Connect/Disconnect Messages (204105025)...
Addon up to date, mounted!
Processing addon 40: [simfphys] armed vehicles (831680603)...
Addon up to date, mounted!
Processing addon 39: ULib (557962238)...
Addon up to date, mounted!
Processing addon 38: ULX (557962280)...
Addon up to date, mounted!
Processing addon 37: Dynamic Resupply Entity (510084500)...
Addon up to date, mounted!
Processing addon 36: WW2 German NPCs II - Heer (497237153)...
Addon up to date, mounted!
Processing addon 35: WW2 German NPCs II - Waffen SS (504095596)...
Addon up to date, mounted!
Processing addon 34: World War 2 Sirens (681689949)...
Addon up to date, mounted!
Processing addon 33: Widgets Disabler (more CPU power!) (793317003)...
Addon up to date, mounted!
Processing addon 32: Seats Network Optimizer (622814666)...
Addon up to date, mounted!
Processing addon 31: Artillery Strike SWEP (683095612)...
Addon up to date, mounted!
Processing addon 30: Brutal Deaths (928802859)...
Addon up to date, mounted!
Processing addon 29: Immersion Sounds - Realistic Bullet Cracks and Whips (216217606)...
Addon up to date, mounted!
Processing addon 28: WAC Aircraft (104990330)...
Addon up to date, mounted!
Processing addon 27: 29th Infantry Division Pack (153550691)...
Addon up to date, mounted!
Processing addon 26: [TFA][AT] Kar 98k (1230930270)...
Addon up to date, mounted!
Processing addon 25: [TFA][AT] INS2 Shared Parts (866368346)...
Addon up to date, mounted!
Processing addon 24: Nazi Salute (1129575480)...
Addon up to date, mounted!
Processing addon 23: rnl_laststand (702465569)...
Addon up to date, mounted!
Processing addon 22: [V92B-W] R&L Parachute (895158385)...
Addon up to date, mounted!
Processing addon 21: gm_rhine (1289646999)...
Addon up to date, mounted!
Processing addon 20: Auto-Cleaning Decals [No ULX and more admins mod] (412608410)...
Addon up to date, mounted!
Processing addon 19: Resistance and Liberation Map Content (Part 1) (452042706)...
Addon up to date, mounted!
Processing addon 18: Resistance and Liberation Map Content (Part 2) (452075722)...
Addon up to date, mounted!
Processing addon 17: Resistance and Liberation Map Content (Part 3) (452078053)...
Addon up to date, mounted!
Processing addon 16: Resistance And Liberation: Miscellaneous Props (136409714)...
Addon up to date, mounted!
Processing addon 15: Resistance and Liberation Map Pack [World War 2] (452109731)...
Addon up to date, mounted!
Processing addon 14: Resistance and Liberation Extended Map Pack [World War 2] (452226991)...
Addon up to date, mounted!
Processing addon 13: rnl_stemariedumont (705416167)...
Addon up to date, mounted!
Processing addon 12: WW2 British Tank Crew (273634038)...
Addon up to date, mounted!
Processing addon 11: Brothers in Arms: Road to Hill 30 US Tank Crew (273199718)...
Addon up to date, mounted!
Processing addon 10: Infantry First Aid Kit (1144876357)...
Addon up to date, mounted!
Processing addon 9: US Army - Ranks- WW2 [Playermodel] by Neiremberg (1283094721)...
Addon up to date, mounted!
Processing addon 8: [WAC] Junkers Ju-87B Stuka BUFFED (1111593867)...
Addon up to date, mounted!
Processing addon 7: [WAC] Supermarine Spitfire (buffed) 24 (1129391718)...
Addon up to date, mounted!
Processing addon 6: WAC Community 5 (139224513)...
Addon up to date, mounted!
Processing addon 5: WAC Community 4 (128559085)...
Addon up to date, mounted!
Processing addon 4: WW2 German NPCs II - Luftwaffe (874600775)...
Addon up to date, mounted!
Processing addon 3: Call of Duty: United Offensive Bomber Crew (358550723)...
Addon up to date, mounted!
Processing addon 2: WW2 Commonwealth NPCs (104556969)...
Addon up to date, mounted!
Processing addon 1: Icy's Handheld M2 Browning (263575228)...
Addon up to date, mounted!
WS: Finished!
Adding Filesystem Addon '/home/container/garrysmod/addons/gredwitchs_base_1131455085'
Adding Filesystem Addon '/home/container/garrysmod/addons/plogs'
Adding Filesystem Addon '/home/container/garrysmod/addons/sh_flashbang'
Adding Filesystem Addon '/home/container/garrysmod/addons/ulib'
Adding Filesystem Addon '/home/container/garrysmod/addons/ulx'
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Changing gamemode to WW2 Axis VS Allies Roleplay (ww2axisvsalliesroleplay)
Network: IP 66.70.214.153, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
PREP OK
MDLCache: Failed load of .VVD data for props\prop_nature01\rock_set\rock_set05.mdl
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props/prop_nature01/rock_set/rock_set05.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_industrial_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_industrial_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_industrial_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_1_ascend.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_hill_cluster.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_res_2.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_buildings/row_corner_1.mdl)
Particles: Missing 'particles/muzzleflashes_test.pcf'
Particles: Missing 'particles/muzzleflashes_test_b.pcf'
Particles: Missing 'particles/impact_fx_fas.pcf'
__
_ __ / / ___ __ _ ___
| '_ \ / / / _ \ / _` / __|
| |_) / /__| (_) | (_| \__ \
| .__/\____/\___/ \__, |___/
|_| |___/
Version 2.7.1 by aStonedPenguin
///////////////////////////////
// Ulysses Library //
///////////////////////////////
// Loading... //
// shared/defines.lua //
// shared/misc.lua //
// shared/util.lua //
// shared/hook.lua //
// shared/table.lua //
// shared/player.lua //
// server/player.lua //
// server/bans.lua //
// shared/messages.lua //
// shared/commands.lua //
// server/concommand.lua //
// server/util.lua //
// shared/sh_ucl.lua //
// server/ucl.lua //
// server/phys.lua //
// server/player_ext.lua //
// server/entity_ext.lua //
// shared/plugin.lua //
// shared/cami_global.lua //
// shared/cami_ulib.lua //
// Load Complete! //
///////////////////////////////
[ULIB] Loading SHARED module: ulx_init.lua
///////////////////////////////
// ULX Admin Mod //
///////////////////////////////
// Loading... //
// sh_defines.lua //
// lib.lua //
// base.lua //
// sh_base.lua //
// log.lua //
// MODULE: slots.lua //
// MODULE: uteam.lua //
// MODULE: votemap.lua //
// MODULE: xgui_server.lua //
///////////////////////////////
// ULX GUI -- by Stickly Man //
///////////////////////////////
// Adding Main Modules.. //
// bans.lua //
// commands.lua //
// groups.lua //
// maps.lua //
// settings.lua //
// Adding Setting Modules.. //
// client.lua //
// server.lua //
// Adding Gamemode Modules.. //
// sandbox.lua //
// Loading Server Modules.. //
// sv_bans.lua //
// sv_groups.lua //
// sv_maps.lua //
// sv_sandbox.lua //
// sv_settings.lua //
// XGUI modules added! //
///////////////////////////////
// MODULE: cc_chat.lua //
// MODULE: cc_commandtable.lua//
// MODULE: cc_cvars.lua //
// MODULE: cc_effects.lua //
// MODULE: cc_fun.lua //
// MODULE: cc_hook.lua //
// MODULE: cc_menus.lua //
// MODULE: cc_notepad.lua //
// MODULE: cc_pgag.lua //
// MODULE: cc_rcon.lua //
// MODULE: cc_soundlist.lua //
// MODULE: cc_teleport.lua //
// MODULE: cc_util.lua //
// MODULE: cc_voting.lua //
// MODULE: chat.lua //
// MODULE: fun.lua //
// MODULE: menus.lua //
// MODULE: rcon.lua //
// MODULE: teleport.lua //
// MODULE: user.lua //
// MODULE: userhelp.lua //
// MODULE: util.lua //
// MODULE: vote.lua //
// end.lua //
// Load Complete! //
///////////////////////////////
[ACD] Successfully initialize.
---------------------------------
| Loading ServerSide PermaProps |
---------------------------------
permaprops/sv_lib.lua
permaprops/sv_menu.lua
permaprops/sv_permissions.lua
permaprops/sv_specialfcn.lua
permaprops/sv_sql.lua
-----------------------------
| Loading Shared PermaProps |
-----------------------------
---------------------------------
| Loading ClientSide PermaProps |
---------------------------------
permaprops/cl_drawent.lua
permaprops/cl_menu.lua
-------------------------------
M9KDamageMultiplier is missing! You may have hit the lua limit! Reverting multiplier to 1.
M9KDefaultClip is missing! You may have hit the lua limit!
LUA BRUTALLY RAPED
SIEGHAIL
[[WAC] Junkers Ju-87D Stuka] lua/entities/wac_pl_ju87b/init.lua:83: '<eof>' expected near 'end'
1. unknown - lua/entities/wac_pl_ju87b/init.lua:0
Couldn't include file 'entities/base_wire_entity.lua' (File not found) (@lua/entities/wac_seat_connector/init.lua (line 5))
Disabling widgets...
Widgets disabled!
Loaded A2S Cache
HTTP failed - ISteamHTTP isn't available!
[ERROR] gamemodes/ww2axisvsalliesroleplay/schema/factions/sh_allies_recruit.lua:10: '}' expected (to close '{' at line 8) near '"models/29thid/male4.mdl"'
1. unknown - gamemodes/ww2axisvsalliesroleplay/schema/factions/sh_allies_recruit.lua:0
Faction 'allies_recruit' is missing a name. You need to add a FACTION.name = "Name"
Faction 'allies_recruit' is missing a description. You need to add a FACTION.desc = "Description"
Faction 'allies_recruit' is missing a color. You need to add FACTION.color = Color(1, 2, 3)
[AddCSLuaFile] Couldn't find 'cl_hooks.lua' (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 21))
Couldn't include file 'sv_schema.lua' (File not found) (@gamemodes/nutscript/gamemode/core/sh_util.lua (line 9))
quest_honeya example will not work properly without "quest" plugin.
Making workshop map available for client download
ConVarRef room_type doesn't point to an existing ConVar
Unknown command "sv_tags"
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
env_soundscape_proxy can't find target soundscape: ''
Nav File is wrong or something (1)
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
No account token specified; logging into anonymous game server account. (Use sv_setsteamaccount to login to a persistent account.)
Server logging enabled.
Server logging data to file logs/L0204006.log
L 02/04/2018 - 15:47:03: Log file started (file "logs/L0204006.log") (game "/home/container/garrysmod") (version "6974")
Unknown command "sbox_allownpcs"
Unknown command "sbox_plpldamage"
Unknown command "sbox_playergod"
Unknown command "sbox_maxspawners"
Unknown command "sbox_maxturrets"
'banned_ip.cfg' not present; not executing.
'banned_user.cfg' not present; not executing.
NutScript has connected to the database.
Database Type: sqlite.
Connection to Steam servers successful.
Public IP is 66.70.214.153.
Assigned anonymous gameserver Steam ID [A-1:644726785(9600)].
VAC secure mode is activated.

**Comment by lechu2375** [comment]
"not going into the right gamemode" - You mean, server doesn't open schema or wrong name under server list ?

**Comment by Aults1002** [comment]
The schema works, but it won't go into the correct gamemode name, i'm trying to put it into a specific gamemode, but it goes into NS - Unknown

**Comment by lechu2375** [comment]
Remember this is outdated nutscript repo. 
1.1 is developed by rebel.
Do you have nameofyourschema.txt inside folder with schema? 
like modernrp/moderntp.txt

**Comment by rebel1324** [comment]
https://github.com/rebel1324/Nutscript/issues
