### ISSUE TITLE
tposing models.

### ISSUE THREAD

**Issue by PapaFitta** [Chessnut/NutScript#807]
Yes I know I have tried to set the class. This is what I put into schema

nut.anim.setModelClass("player", "models/half-dead/metroll/a1b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a2b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a3b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a4b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a5b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f1b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f2b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f3b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f4b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f6b1.mdl")

still tposing. I tried making a plugin and heres what the sh_plugin.lua looks like

PLUGIN.name = "tposefix"
PLUGIN.author = "Chessnut"
PLUGIN.desc = "is meant to fix gay tpose"

nut.anim.setModelClass("player", "models/half-dead/metroll/a1b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a2b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a3b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a4b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/a5b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f1b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f2b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f3b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f4b1.mdl")
nut.anim.setModelClass("player", "models/half-dead/metroll/f6b1.mdl")

I dont know what else I can do now. There are no npc models for these.

If someone out there actually replies to this please try to be in-depth and not vague please, thanks.

**Comment by rebel1324** [comment]
goto rebel1324/Nutscript
