### ISSUE TITLE
/plywhitelist not working + Error master branch

### ISSUE THREAD

**Issue by dragnort1** [Chessnut/NutScript#811]
When attempting to whitelist to a faction I get no message and no one is whitelisted.

This is the error:
ggggg: (IC)  /plywhitelist ggggg marine
 
[ERROR] gamemodes/nutscript/gamemode/sh_util.lua:149: bad argument #1 to 'lower' (string expected, got nil)
  1. lower - [C]:-1
   2. StringMatches - gamemodes/nutscript/gamemode/sh_util.lua:149
    3. onRun - gamemodes/nutscript/gamemode/sh_commands.lua:287
     4. RunCommand - gamemodes/nutscript/gamemode/libs/sh_commands.lua:54
      5. ParseCommand - gamemodes/nutscript/gamemode/libs/sh_commands.lua:137
       6. Process - gamemodes/nutscript/gamemode/libs/sh_chatbox.lua:391
        7. Run - gamemodes/nutscript/gamemode/core/sv_hooks.lua:229
         8. unknown - gamemodes/nutscript/plugins/chatbox/sh_chatbox.lua:324
          9. func - gamemodes/nutscript/gamemode/libs/external/sh_netstream.lua:119
           10. unknown - lua/includes/extensions/net.lua:32

I understand 1.1 is more updated however I want to use master branch thanks for any updates.

**Comment by rebel1324** [comment]
sorry, I can't answer anything about 1.0 because it's like 3 years old.

**Comment by dragnort1** [comment]
How would you forget something you worked on for years.

**Comment by rebel1324** [comment]
well we quit making 1.0 stuffs for at least 4 years

2018년 4월 12일 (목) 오후 5:57, dragnort1 <notifications@github.com>님이 작성:

**Comment by dragnort1** [comment]
So you don't have any idea what the issue for this could be?

**Comment by rebel1324** [comment]
unfortunately, no. i dont have idea.


2018년 4월 12일 (목) 오후 6:53, dragnort1 <notifications@github.com>님이 작성:
