### ISSUE TITLE
T posing models

### ISSUE THREAD

**Issue by SlayerClaux** [Chessnut/NutScript#812]
soooo... I'm new with nutscript, I'm learning but I came across this issue with the models that some of them work and others do T pose, I was searching how to solve it and most of the people say with nut.anim.SetModelClass but I don't know how to use it, if I could get some help I would apreciate it a lot.
And sorry if my english its not that good

**Comment by russianmtf** [comment]
https://github.com/Chessnut/NutScript/wiki/nut.anim
