### ISSUE TITLE
Loading Screen error

### ISSUE THREAD

**Issue by Starstriker112** [Chessnut/NutScript#816]
Hi, 
whenever I load into my server I get this error:
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Clear Sans Medium'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'Trebuchet18'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'boogaloo'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'Trebuchet24'!
Failed creating font 'dejavusansmono'!
Failed creating font 'TargetID'!

and I cant get past the loading screen but for some reason when I hit pause I can see the map the server is running just fine and know I have loaded in because I can hear sounds and everything.

**Comment by russianmtf** [comment]
You have something conflicting with other scripts.
