### ISSUE TITLE
TFA weapons not working, ns 1.1

### ISSUE THREAD

**Issue by hornedmarten** [Chessnut/NutScript#818]
trying to use tfa weapons with ns 1.1, every time i use giveitem in the top right corner i get two messages "false" and "invalid item". is there a solution for this or something im doing wrong with my stuff?

heres my weapon code:

ITEM.name = "M392 DMR"
ITEM.desc = "Created for the RP called Project Reclamation.. | "
ITEM.model = "models/ishi/halo_rebirth/weapons/unsc/w_m392.mdl"
ITEM.class = "tfa_rebirth_m392"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 1
ITEM.iconCam = {
	ang	= Angle(0.33879372477531, 270.15808105469, 0),
	fov	= 5.0470897275697,
	pos	= Vector(0, 200, -1)
}

**Comment by rebel1324** [comment]
Currently I'm working on TFA Base integration with TFA. stay tuned.
