### ISSUE TITLE
Attaching a Salary to a Playermodel

### ISSUE THREAD

**Issue by Faust723** [Chessnut/NutScript#822]
I am looking for a script or addon or a way to allow a Salary / nutPay to be attached to a specific player model.

Example:
Model 1 makes $30
Model 2 makes $35

So basically when a persons model is changed to Model 2, they should experience a pay bump by $5. Is this possible and if so, please direct me to someone who can build this for me.

**Comment by TVonWheels** [comment]
What was the fix?
